%   Copyright 2022 The MathWorks, Inc.

function typeId = selectOAuthTypeId(typeIdList)
typeId = listdlg(...
    "ListString", typeIdList, ...
    "ListSize", [300 100], ...
    "PromptString", getString(message("oauth_services:messages:SelectTypeIdPrompt")), ...
    "SelectionMode", "single");
if isempty(typeId)
    typeId = 0;
end
end
