classdef Constants
    %CONSTANTS contains constant values for the toolstrip Analyze Section
    %View and Controller classes.

    % Copyright 2021-2023 The MathWorks, Inc.

    properties (Constant)
        %% Columns
        % In general, a toolstrip column contains toolstrip UI elements
        % that are displayed one below the other (stacked vertically).

        % These column properties contain the width and alignment
        % information for each toolstrip column, which affects the
        % underlying UI elements' width and alignment.
        EmptyColumn = ...
            matlabshared.transportapp.internal.toolstrip.Manager.prepareEmptyToolstripColumn()

        AnalyzeColumns = [ ...
            matlabshared.transportapp.internal.toolstrip.Manager.prepareToolstripColumn( ...
                matlabshared.transportapp.internal.toolstrip.Manager.ButtonWidth, ...
                matlabshared.transportapp.internal.toolstrip.Manager.ButtonAlignment), ...
                ...
            matlabshared.transportapp.internal.toolstrip.Manager.prepareToolstripColumn( ...
                matlabshared.transportapp.internal.toolstrip.Manager.ButtonWidth, ...
                matlabshared.transportapp.internal.toolstrip.Manager.ButtonAlignment) ...
            ]

        %% Section Names
        AnalyzeSectionName = message("transportapp:toolstrip:analyze:AnalyzeSectionName").getString

        %% Label Names
        PlotButtonLabel = message("transportapp:toolstrip:analyze:PlotButtonLabel").getString
        SigAnButtonLabel = message("transportapp:toolstrip:analyze:SigAnButtonLabel").getString

        %% Tooltip Messages
        PlotButtonTooltip = message("transportapp:toolstrip:analyze:PlotButtonTooltip").getString
        SigAnButtonTooltip = message("transportapp:toolstrip:analyze:SigAnButtonTooltip").getString

        %% Column1 Elements
        PlotButtonProps = struct("Text", matlabshared.transportapp.internal.toolstrip.analyze.Constants.PlotButtonLabel,...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "Plot"), ...
            "Description", matlabshared.transportapp.internal.toolstrip.analyze.Constants.PlotButtonTooltip, ...
            "Enabled", true, ...
            "Tag", 'PlotButton')

        SigAnButtonProps = struct("Text", matlabshared.transportapp.internal.toolstrip.analyze.Constants.SigAnButtonLabel,...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "SignalAnalyzer"), ...
            "Description", matlabshared.transportapp.internal.toolstrip.analyze.Constants.SigAnButtonTooltip, ...
            "Enabled", true, ...
            "Tag", 'SigAnalyzerButton')

        %% Other Props
        NoLicenseOptionStringText = ...
            message("transportapp:toolstrip:analyze:SigAnOptionsNoLicense").getString

        NoDataSelectedOptionStringText = ...
            message("transportapp:toolstrip:analyze:SigAnOptionsNoRowSelected").getString

        OpenOption = ...
            string(message("transportapp:toolstrip:analyze:OpenOption").getString)
        OpenAnywayOption = ...
            string(message("transportapp:toolstrip:analyze:OpenAnywayOption").getString)
        NoOption = ...
            string(message("transportapp:toolstrip:analyze:NoOption").getString)

        SigAnUniqueID = "Shared_Transport_Apps"
    end
end
