classdef DialogBuilderConstants
    %DIALOGBUILDERCONSTANTS contains the constants that are common to the
    %Modal Dialog Window.

    % Copyright 2022-2023 The MathWorks, Inc.

    properties (Abstract, Constant)
        % Specifies the number of rows/sections in the Generate Resource
        % section of the modal window.
        GenerateResourceNumberRowsInDialog

        % Specifies the base grid layout of the modal window, depending on
        % the number of rows/sections in the Generate Resource section of
        % the modal window.
        BaseGridLayoutProperties

        % Specifies the Generate Resource panel's grid layout, depending on
        % the number of rows/sections in the Generate Resource section of
        % the modal window.
        GenerateResourcePanelGridLayoutProperties
    end

    properties (Constant)
        FigureProperties (1, 1) struct = struct (...
            "WindowStyle", "modal" ...
            )
        FigureWidth = 500
        FigureHeight = 500

        TestConnectionNumberRowsInDialog = 7

        TestConnectionPanelGridLayoutProperties = struct( ...
            "RowHeight", repmat("1x", 1, matlabshared.transportapp.internal.visamodaldialog.DialogBuilderConstants.TestConnectionNumberRowsInDialog), ...
            "ColumnWidth", ["5x", "2x", "3x", "2x", "2x"], ...
            "Padding", [10 10 10 10], ...
            "RowSpacing", 5, ...
            "ColumnSpacing", 10 ...
            )

        GenerateResourcePanelProperties = struct("Title", message("transportapp:visadevapp:GenerateResourcePanelName").getString(), ...
            "TitlePosition", "lefttop", ...
            "FontSize", 14, ...
            "FontWeight", "bold" ...
            )
        TestConnectionPanelProperties = struct("Title", message("transportapp:visadevapp:TestConnectionPanelName").getString(), ...
            "TitlePosition", "lefttop", ...
            "FontSize", 14, ...
            "FontWeight", "bold" ...
            )

        BoardNumberLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:BoardNumberName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:BoardNumberTooltip").getString) ...
            )
        BoardNumberEditFieldProperties = struct( ...
            "Value", "0", ...
            "Tag", "BOARD_NUMBER_EDIT_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:BoardNumberTooltip").getString) ...
            )

        IPAddressLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:IPAddressName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:IPAddressTooltip").getString) ...
            )

        IPAddressEditFieldProperties = struct( ...
            "Tag", "IP_ADDRESS_EDIT_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:IPAddressTooltip").getString) ...
            )

        DeviceIDLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:DeviceIDName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:DeviceIDTooltip").getString) ...
            )

        DeviceIDEditFieldProperties = struct( ...
            "Value", "0", ...
            "Tag", "DEVICE_ID_EDIT_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:DeviceIDTooltip").getString) ...
            )

        PortLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:PortName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:PortTooltip").getString) ...
            )

        PortEditFieldProperties = struct( ...
            "Value", "4880", ...
            "Tag", "PORT_EDIT_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:PortTooltip").getString) ...
            )

        GenerateButtonProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:GenerateButtonName").getString), ...
            "Tooltip", string(message("transportapp:visadevapp:GenerateButtonTooltip").getString), ...
            "Tag", "GENERATE_RESOURCE_BUTTON" ...
            )

        ResourceNameLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:ResourceNameName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:ResourceNameTooltip").getString) ...
            )

        ResourceNameEditFieldProperties = struct( ...
            "Editable", "off", ...
            "Tag", "RESOURCE_NAME_EDIT_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:ResourceNameTooltip").getString) ...
            )

        IdentificationLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:IdentificationName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:IdentificationTooltip").getString) ...
            )

        IdentificationEditFieldProperties = struct( ...
            "Value", message("transportapp:visadevapp:DefaultIdentificationString").string, ...
            "Tag", "IDENTIFICATION_EDIT_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:IdentificationTooltip").getString) ...
            )

        TestConnectionButtonProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:TestConnectionButtonName").getString), ...
            "Tooltip", string(message("transportapp:visadevapp:TestConnectionButtonTooltip").getString), ...
            "Tag", "TEST_CONNECTION_BUTTON" ...
            )

        ConnectionMessageLabelProperties = struct ( ...
            "WordWrap", "on", ...
            "FontWeight", "bold", ...
            "Text", "",...
            "Tag","CONNECTION_MESSAGE_LABEL"...
            )

        ModelLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:ModelName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:ModelTooltip").getString) ...
            )
        ModelEditFieldProperties = struct( ...
            "Editable", "off", ...
            "Tag", "MODEL_EDIT_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:ModelTooltip").getString) ...
            )

        VendorIDLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:VendorIDName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:VendorIDTooltip").getString) ...
            )
        VendorIDEditFieldProperties = struct( ...
            "Editable", "off", ...
            "Tag", "VENDOR_ID_FIELD", ...
            "Tooltip", string(message("transportapp:visadevapp:VendorIDTooltip").getString) ...
            )

        ConnectionStatusLabelProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:ConnectionStatusName").getString), ...
            "HorizontalAlignment", "right", ...
            "Tooltip", string(message("transportapp:visadevapp:ConnectionStatusTooltip").getString) ...
            )
        ConnectionStatusTextAreaProperties = struct( ...
            "Editable", "off", ...
            "Tag", "CONNECTION_STATUS_TEXT_AREA", ...
            "Tooltip", string(message("transportapp:visadevapp:ConnectionStatusTooltip").getString) ...
            )

        CancelButtonProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:CancelButtonName").getString), ...
            "Tooltip", string(message("transportapp:visadevapp:CancelButtonTooltip").getString), ...
            "Tag", "CANCEL_BUTTON" ...
            )

        ConfirmButtonProperties = struct( ...
            "Text", string(message("transportapp:visadevapp:ConfirmButtonName").getString), ...
            "Tooltip", string(message("transportapp:visadevapp:ConfirmButtonTooltip").getString), ...
            "Enable", "off", ...
            "Tag", "CONFIRM_BUTTON" ...
            )
    end
end
