classdef GenerateResource5FieldConstants < matlabshared.transportapp.internal.visamodaldialog.DialogBuilderConstants
    %GENERATERESOURCE3FIELDCONSTANTS is the specialized Constants class
    %that defines 5 attributes or fields in the Generate Resource Section
    %of the Modal Dialog Window.

    % Copyright 2022-2023 The MathWorks, Inc.

    properties (Constant)
        GenerateResourceNumberRowsInDialog = 5

        BaseGridLayoutProperties = struct( ...
            "RowHeight", ["5x", "7x", "0.7x"], ...
            "ColumnWidth", ["5x", "2x", "3x", "2x", "2x"], ...
            "Padding", [10 10 10 10], ...
            "RowSpacing", 5, ...
            "ColumnSpacing", 10 ...
            )

        GenerateResourcePanelGridLayoutProperties = struct( ...
            "RowHeight", repmat("1x", 1, matlabshared.transportapp.internal.visamodaldialog.GenerateResource5FieldConstants.GenerateResourceNumberRowsInDialog), ...
            "ColumnWidth", ["5x", "2x", "3x", "2x", "2x"], ...
            "Padding", [10 10 10 10], ...
            "RowSpacing", 5, ...
            "ColumnSpacing", 10 ...
            )
    end
end

