classdef GenerateResource6FieldConstants < matlabshared.transportapp.internal.visamodaldialog.DialogBuilderConstants
    %GENERATERESOURCE6FIELDCONSTANTS is the specialized Constants class
    %that defines 6 attributes or fields in the Generate Resource Section
    %of the Modal Dialog Window.

    % Copyright 2022-2023 The MathWorks, Inc.

    properties (Constant)
        GenerateResourceNumberRowsInDialog = 6

        BaseGridLayoutProperties = struct( ...
            "RowHeight", ["6x", "6.8x", "0.6x"], ...
            "ColumnWidth", ["5x", "2x", "3x", "2x", "2x"], ...
            "Padding", [10 10 10 10], ...
            "RowSpacing", 5, ...
            "ColumnSpacing", 10 ...
            );

        GenerateResourcePanelGridLayoutProperties = struct( ...
            "RowHeight", repmat("1x", 1, matlabshared.transportapp.internal.visamodaldialog.GenerateResource6FieldConstants.GenerateResourceNumberRowsInDialog), ...
            "ColumnWidth", ["5x", "2x", "3x", "2x", "2x"], ...
            "Padding", [10 10 10 10], ...
            "RowSpacing", 5, ...
            "ColumnSpacing", 10 ...
            )
    end
end

