classdef EventClassificationMaps 
%EventClassificationMaps - Maps relating RelativeAlignment to EventType

%   Copyright 2024 The MathWorks, Inc.

%#codegen
    properties (Constant)
        %RelativeAlignments - Ordered list of all RelativeAlignment properties
        %   Used as the keys for the dictionaries in this class
        RelativeAlignments = [nav.decomp.internal.RelativeAlignment.Opposite ...
            nav.decomp.internal.RelativeAlignment.Aligned ...
            nav.decomp.internal.RelativeAlignment.Unaligned ...
            nav.decomp.internal.RelativeAlignment.North ...
            nav.decomp.internal.RelativeAlignment.South];
        %RightUpMap - Classifies points where A is on the right and hole is Upper
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   on the right side of the plane and the hole direction is Upper
        RightUpMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.Ceiling ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.Out  ...
            nav.decomp.internal.EventType.Pinch]);
        %LeftUpMap - Classifies points where A is on the left and hole is Upper
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   on the left side of the plane and the hole direction is Upper
        LeftUpMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments,  ...
            [nav.decomp.internal.EventType.Ceiling ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.In  ...
            nav.decomp.internal.EventType.Split]);
        %NorthUpMap - Classifies points where A points North and hole is Upper
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   pointing North and the hole direction is Upper. Hole direction being
        %   Upper here means to the left of A
        NorthUpMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge]);
        %SouthUpMap - Classifies points where A points South and hole is Upper
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   pointing South and the hole direction is Upper. Hole direction being
        %   Upper here means to the right of A
        SouthUpMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.VertEdge  ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge]);
        %OriginUpMap - Classifies points where A is [0 0] and hole is Upper
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   [0 0] and the hole direction is Upper
        OriginUpMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.Ceiling ...
            nav.decomp.internal.EventType.Ceiling     ...
            nav.decomp.internal.EventType.Ceiling    ...
            nav.decomp.internal.EventType.VertEdge  ...
            nav.decomp.internal.EventType.VertEdge]);
        %RightLowMap - Classifies points where A is on the right and hole is Lower
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   on the right side of the plane and the hole direction is Lower
        RightLowMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.Floor     ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.Pinch  ...
            nav.decomp.internal.EventType.Out]);
        %LeftLowMap - Classifies points where A is on the left and hole is Lower
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   on the left side of the plane and the hole direction is Lower
        LeftLowMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.Floor ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.Split  ...
            nav.decomp.internal.EventType.In]);
        %NorthLowMap - Classifies points where A points North and hole is Lower
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   pointing North and the hole direction is Lower. Hole direction being
        %   lower here means to the right of A
        NorthLowMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge]);
        %SouthLowMap - Classifies points where A points South and hole is Lower
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   pointing South and the hole direction is Lower. Hole direction being
        %   lower here means to the left of A
        SouthLowMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge]);
        %OriginLowMap - Classifies points where A is [0 0] and hole is Lower
        %   Maps from B's RelativeAlignment to the EventType when A is
        %   [0 0] and the hole direction is Lower.
        OriginLowMap = dictionary(nav.decomp.internal.EventClassificationMaps.RelativeAlignments, ...
            [nav.decomp.internal.EventType.Floor ...
            nav.decomp.internal.EventType.Floor     ...
            nav.decomp.internal.EventType.Floor   ...
            nav.decomp.internal.EventType.VertEdge  ...
            nav.decomp.internal.EventType.VertEdge]);
    end
end

