classdef EventClassificationMatrices
%EventClassificationMatrices - Matrices relating RelativeAlignment to EventType

%   Copyright 2024 The MathWorks, Inc.

%#codegen
    properties (Constant)
        %LeftUpMat - Classifies points where A is on the left and hole is Upper
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   on the left side of the plane and the hole direction is Upper
        LeftUpMat = ...
            [nav.decomp.internal.EventType.Ceiling ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.In  ...
            nav.decomp.internal.EventType.Split];
        
        %RightUpMat - Classifies points where A is on the right and hole is Upper
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   on the right side of the plane and the hole direction is Upper
        RightUpMat = ...
            [nav.decomp.internal.EventType.Ceiling ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.Out  ...
            nav.decomp.internal.EventType.Pinch];

        %NorthUpMat - Classifies points where A points North and hole is Upper
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   pointing North and the hole direction is Upper. Hole direction being
        %   Upper here means to the left of A
        NorthUpMat = ...
            [nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge];

        %SouthUpMat - Classifies points where A points South and hole is Upper
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   pointing South and the hole direction is Upper. Hole direction being
        %   Upper here means to the right of A
        SouthUpMat = ...
            [nav.decomp.internal.EventType.VertEdge  ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge];

        %OriginUpMat - Classifies points where A is [0 0] and hole is Upper
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   [0 0] and the hole direction is Upper
        OriginUpMat = ...
            [nav.decomp.internal.EventType.Ceiling ...
            nav.decomp.internal.EventType.Ceiling     ...
            nav.decomp.internal.EventType.Ceiling    ...
            nav.decomp.internal.EventType.VertEdge  ...
            nav.decomp.internal.EventType.VertEdge];

        %LeftLowMat - Classifies points where A is on the left and hole is Lower
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   on the left side of the plane and the hole direction is Lower
        LeftLowMat = ...
            [nav.decomp.internal.EventType.Floor ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.Split  ...
            nav.decomp.internal.EventType.In];

        %RightLowMat - Classifies points where A is on the right and hole is Lower
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   on the right side of the plane and the hole direction is Lower
        RightLowMat = ...
            [nav.decomp.internal.EventType.Floor     ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.Pinch  ...
            nav.decomp.internal.EventType.Out];

        %NorthLowMat - Classifies points where A points North and hole is Lower
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   pointing North and the hole direction is Lower. Hole direction being
        %   lower here means to the right of A
        NorthLowMat = ...
            [nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.In     ...
            nav.decomp.internal.EventType.Pinch    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge];

        %SouthLowMat - Classifies points where A points South and hole is Lower
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   pointing South and the hole direction is Lower. Hole direction being
        %   lower here means to the left of A
        SouthLowMat = ...
            [nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.Out    ...
            nav.decomp.internal.EventType.Split    ...
            nav.decomp.internal.EventType.VertEdge ...
            nav.decomp.internal.EventType.VertEdge];

        %OriginLowMat - Classifies points where A is [0 0] and hole is Lower
        %   Mats from B's RelativeAlignment to the EventType when A is
        %   [0 0] and the hole direction is Lower.
        OriginLowMat = ...
            [nav.decomp.internal.EventType.Floor ...
            nav.decomp.internal.EventType.Floor     ...
            nav.decomp.internal.EventType.Floor   ...
            nav.decomp.internal.EventType.VertEdge  ...
            nav.decomp.internal.EventType.VertEdge];

        %UpClassificationMatrix55 - Maps aQuad, and bRelative to EventType for fillDirection==UPPER
        UpClassificationMatrix55 = [nav.decomp.internal.EventClassificationMatrices.LeftUpMat; 
            nav.decomp.internal.EventClassificationMatrices.RightUpMat; 
            nav.decomp.internal.EventClassificationMatrices.NorthUpMat; 
            nav.decomp.internal.EventClassificationMatrices.SouthUpMat; 
            nav.decomp.internal.EventClassificationMatrices.OriginUpMat];

        %LowClassificationMatrix55 - Maps aQuad, and bRelative to EventType for fillDirection==LOWER
        LowClassificationMatrix55 = [nav.decomp.internal.EventClassificationMatrices.LeftLowMat; 
            nav.decomp.internal.EventClassificationMatrices.RightLowMat; 
            nav.decomp.internal.EventClassificationMatrices.NorthLowMat; 
            nav.decomp.internal.EventClassificationMatrices.SouthLowMat; 
            nav.decomp.internal.EventClassificationMatrices.OriginLowMat];

        %AllClassificationMatrix552 - Maps aQuad, bRelative, and fillDirection to EventType
        AllClassificationMatrix552 = cat(3, ...
            nav.decomp.internal.EventClassificationMatrices.UpClassificationMatrix55, ...
            nav.decomp.internal.EventClassificationMatrices.LowClassificationMatrix55);

        %NextCeilDelta - Indicates direction to next ceil from each event
        %   Order corresponds to CEILING, IN, FLOOR, OUT, PINCH, SPLIT,
        %   VERTEDGE
        NextCeilDelta = [1 1 nan nan nan 1 nan];

        %NextCeilDelta - Indicates direction to next floor from each event
        %   Order corresponds to CEILING, IN, FLOOR, OUT, PINCH, SPLIT,
        %   VERTEDGE
        NextFloorDelta = [nan -1 -1 nan nan -1 nan];
    end
end

