function dlg = createModelDialog(name)
%This function is for internal use only. It may be removed in the future. 

%createModelDialog Helper utility to create a model uifigure based dialog window.

%   Copyright 2021-2023 The MathWorks, Inc.

if isunix
    % on unix platform modal window style specification is ignored. due to
    % this always on top figure style is used. Along with this to mimic
    % modal behavior the app is put to inaccessible state. This platform
    % dependent behavior should be changed once the modal window style is
    % supported on unix 
    dlg = uifigure('Name',name, ...
        'WindowStyle', 'alwaysontop', ...
        'HandleVisibility', 'off', ...
        'Visible', 'off', ...
        'Resize', 'off', ...
        'Units', 'pixels');
else
    % create uifigure with simimlar settings as questdlg utulity function
    dlg = uifigure('Name',name, ...
        'WindowStyle', 'modal', ...
        'HandleVisibility', 'off', ...
        'Visible', 'off', ...
        'Resize', 'off', ...
        'Units', 'pixels');
end
matlab.graphics.internal.themes.figureUseDesktopTheme(dlg);
end