function hButton = createIconButton(parent, tag, params, icon, iconSize)
%This function is for internal use only. It may be removed in the future. 

%createIconButton Helper utility to create a button with a customized
%   icon figure.

%   Copyright 2021-2023 The MathWorks, Inc.

hButton = uibutton(...
    parent,...
    'push',...
    'Tag', tag, ...
    'position', params.Position, ...
    'Enable', params.Enable, ...
    'Text', '', ...
    'Tooltip', params.TooltipString, ...
    'BusyAction','cancel',...
    'IconAlignment', params.IconAlignment ...
    );
matlab.graphics.internal.themes.specifyThemePropertyMappings(hButton,"BackgroundColor",params.BackgroundColor);
if length(iconSize)==1
    matlab.ui.control.internal.specifyIconID(hButton, icon, iconSize);
else
    matlab.ui.control.internal.specifyIconID(hButton, icon, iconSize(1), iconSize(2));
end
end