classdef Constants < ros.slros.internal.cgen.Constants
%This class is for internal use only. It may be removed in the future.

%cgen.Constants - Constants used for generating C++ ROS code

%   Copyright 2014-2024 The MathWorks, Inc.

%#codegen

    properties(Constant)

        NodeInterface = struct(...
            'HeaderFile', 'ros2nodeinterface.h', ...
            'SourceFile', 'ros2nodeinterface.cpp', ...
            'MainFile', 'main.cpp', ...
            'CommonHeader', 'slros2_initialize.h', ...
            'CommonCpp', 'slros2_initialize.cpp', ...
            'CommonCppTmpl',fullfile(fileparts(mfilename('fullpath')),'slros2_initialize.cpp.tmpl'), ...
            'HeaderTemplate', fullfile(fileparts(mfilename('fullpath')),'interface.h.tmpl'), ...
            'SourceFileTemplate',fullfile(fileparts(mfilename('fullpath')),'interface.cpp.tmpl'), ...
            'CommonHeaderTemplate', fullfile(fileparts(mfilename('fullpath')),'slros2_initialize.h.tmpl'), ...
            'MainTemplate', fullfile(fileparts(mfilename('fullpath')),'main.cpp.tmpl'), ...
            'NonresuableFcnHeaderTemplate', fullfile(fileparts(mfilename('fullpath')),'interface_nonreusablefcn.h.tmpl'), ...
            'NonresuableFcnSourceFileTemplate', fullfile(fileparts(mfilename('fullpath')),'interface_nonreusablefcn.cpp.tmpl') ...
                              )
        ROS2ModelInfoFile = ros.ros2.ProjectTool.getROS2ModelInfoFile;
        ROS2PredefinedCode = struct(...
            'ConversionUtilsHeaderFile','slros_msgconvert_utils.h', ...
            'CommonPubSubHeader','slros2_generic_pubsub.h',...
            'CommonServiceHeader','slros2_generic_service.h',...
            'CommonParamHeader','slros2_generic_param.h',...
            'CommonParamSource','slros2_generic_param.cpp',...
            'CommonTransformHeader','slros2_generic_transform.h', ...
            'CommonActionHeader','slros2_generic_action.h', ...
            'SlROS2ExecutorHeader', 'slros2_multi_threaded_executor.h', ...
            'SlROS2ExecutorSource', 'slros2_multi_threaded_executor.cpp', ...
            'Location',   fullfile(toolboxdir('ros'), 'slros2', 'src') ...
                                   )
    end

end
