//
// Copyright 2025 The MathWorks, Inc

// Added the below rules to silence the ESLint warnings

/* eslint-disable max-len */
/* eslint-disable no-template-curly-in-string */
/* eslint-disable quotes */
/* eslint-disable no-useless-escape */

//
// DO NOT MODIFY THIS FILE!!  This is a derived file.
// Instead, modify the English message catalog XML file "resources/ros/en/rosgraphapp/view.xml"
// Encoding: UTF-8
//

define({
    Actions: "액션",
    ClearFilters: "적용된 필터를 지우는 중...",
    ClearFiltersButton: "필터 지우기",
    CopyNameOption: "이름 복사",
    DataTypes: "메시지 유형",
    DescriptionActionSvcTopicChkBox: "액션과 관련된 디폴트 토픽과 서비스를 표시합니다",
    DescriptionAutoArrangehButton: "요소를 자동으로 정렬합니다",
    DescriptionConnectButton: "ROS 2 네트워크에 연결합니다",
    DescriptionDeadSinkChkBox: "subscriber는 있지만 publisher는 없는 토픽을 표시합니다",
    DescriptionDefaultChkBox: "/parameters_events 및 /rosout 토픽을 표시합니다",
    DescriptionDefaultSvcChkBox: "/describe_parameters, /get_parameter_types 및 ROS 2 네트워크와 관련된 기타 디폴트 서비스를 표시합니다",
    DescriptionDomainIdLabel: "ROS 2 네트워크 그래프",
    DescriptionExportBtn: "네트워크 그래프의 스냅샷을 내보냅니다",
    DescriptionKeyWordFilterTextArea: "하나 또는 여러 개의 키워드를 쉼표로 구분해 입력하고 Enter 키를 누르면 지정된 용어 중 하나라도 포함하는 요소를 검색합니다",
    DescriptionLastUpdatedLabel: "ROS 2 네트워크 그래프",
    DescriptionLayoutDropDown: "요소를 정렬할 레이아웃을 선택합니다",
    DescriptionLeafTopicChkBox: "publisher는 있지만 subscriber는 없는 토픽을 표시합니다",
    DescriptionNameSpaceSpinner: "시각적 계층 구조 구성을 위해 레이블이 지정된 직사각형에 노드를 중첩하도록 스핀 상자를 조정해 네임스페이스 깊이를 설정합니다",
    DescriptionPropertyPnl: "속성 인스펙터 패널",
    DescriptionRefreshButton: "ROS 2 네트워크를 새로 고칩니다",
    DescriptionUnreachableChkBox: "토픽을 퍼블리시하거나 구독하지 않는 노드, 서비스 서버 또는 클라이언트로 동작하는 노드, 또는 액션 서버 또는 클라이언트로 동작하는 노드를 표시합니다.",
    EnterNetworkDetails: "네트워크 세부 정보 입력",
    ErrorFailedToConnectToNetwork: "도메인 ID ${0}에 연결할 수 없습니다.",
    FilterButton: "필터 적용",
    FilterByButton: "고급 필터링 기준",
    FilterGraph: "ROS 2 네트워크를 필터링하는 중...",
    KeywordFilterPlaceholder: "키워드, 정규 표현식 또는 부정 키워드를 입력합니다.",
    KeywordFilterTooltip: "<b>키워드:</b> camera 또는 GPS와 같은 특정 단어가 포함된 엔터티를 포함합니다.<br> <b>정규 표현식:</b> 유연한 검색을 위해 .*camera.* 또는 gps.*와 같은 패턴을 사용하여 일치하는 엔터티를 찾습니다.<br> <b>제외:</b> 엔터티를 제외하려면 ~debug, ~camera와 같이 키워드 앞에 ~를 사용합니다.<br> <b>여러 개의 입력값:</b> 쉼표로 구분하여 여러 개의 필터를 입력합니다.",
    LabelSearch: "검색",
    LayoutBreadthfirst: "breadthfirst",
    LayoutCircle: "circle",
    LayoutConcentric: "concentric",
    LayoutCose: "cose",
    LayoutDagre: "dagre",
    LayoutGrid: "grid",
    LayoutKlay: "klay",
    LoadGraph: "ROS 도메인 ID ${0}에 대한 네트워크 세부 정보를 수집하는 중...",
    MessageFilterPlaceholder: "메시지 유형, 서비스 유형 또는 액션 유형 입력(예: sensor_msgs/Image)",
    MessageFilterTooltip: "하나 또는 여러 개의 메시지 유형, 서비스 유형, 액션 유형을 쉼표로 구분해서 입력하여 지정된 유형 중 하나 이상에 해당하는 요소를 필터링합니다.",
    NetworkDepthLabel: "네트워크 심도",
    Nodes: "노드",
    NumberSpinnerTooltip: "필터링된 엔터티 주변에 표시되는 연결된 엔터티 수준의 개수를 설정하려면 스핀 상자를 조정합니다.",
    PlaceHolderApplyKeywordFilter: "키워드를 입력하고 Enter 키 누르기",
    PropertyActClient: "액션 클라이언트",
    PropertyActClientNodes: "액션 클라이언트 노드",
    PropertyActServer: "액션 서버",
    PropertyActServerNodes: "액션 서버 노드",
    PropertyActType: "액션 유형",
    PropertyConnectionType: "연결 유형",
    PropertyDomainId: "도메인 ID",
    PropertyEntity: "엔터티",
    PropertyInformationUnavailable: "표시할 정보가 없음",
    PropertyName: "이름",
    PropertyNodeName: "노드 이름",
    PropertyNumberOfActions: "동작 개수",
    PropertyNumberOfNodes: "노드 개수",
    PropertyNumberOfServices: "서비스 개수",
    PropertyNumberOfTopics: "토픽 개수",
    PropertyParameters: "파라미터",
    PropertyPublisherNodes: "Publisher 노드",
    PropertyPublishesTo: "퍼블리시 대상",
    PropertyQOSDeadline: "QoS Deadline",
    PropertyQOSDepth: "QoS Depth",
    PropertyQOSDurability: "QoS Durability",
    PropertyQOSHistory: "QoS History",
    PropertyQOSLeaseDuration: "QoS Lease Duration",
    PropertyQOSLifespan: "QoS Lifespan",
    PropertyQOSLiveliness: "QoS Liveliness",
    PropertyQOSReliability: "QoS Reliability",
    PropertySubscriberNodes: "Subscriber 노드",
    PropertySubscribesTo: "구독 대상",
    PropertySvcClient: "서비스 클라이언트",
    PropertySvcClientNodes: "서비스 클라이언트 노드",
    PropertySvcServer: "서비스 서버",
    PropertySvcServerNodes: "서비스 서버 노드",
    PropertySvcType: "서비스 유형",
    PropertyTableKeys: "키",
    PropertyTableValues: "값",
    PropertyTopicName: "토픽 이름",
    PropertyTopicType: "토픽 유형",
    Ros2NetworkAnalyzerAppTitle: "ROS 2 네트워크 분석기",
    Services: "서비스",
    TextActionListTreeView: "액션",
    TextActionSvcTopicChkBox: "액션 토픽 및 액션 서비스",
    TextAdvancedFilterButton: "고급 \n필터",
    TextApplyKeywordFilterBtn: "필터 적용",
    TextAutoArrangeButton: "자동\n정렬",
    TextConnectButton: "연결",
    TextDeadSinkChkBox: "데드 싱크",
    TextDefaultChkBox: "도움말 초기 화면",
    TextDefaultSvcChkBox: "디폴트 서비스",
    TextEnterDomainIdBtn: "제출",
    TextExportBtn: "내보내기",
    TextLabelDomainId: "도메인 ID",
    TextLayoutLabel: "레이아웃",
    TextLeafTopicChkBox: "리프 토픽",
    TextNameSpaceSpinnerLbl: "네임스페이스",
    TextNodeListTreeView: "노드",
    TextRefreshButton: "새로 고침",
    TextServiceListTreeView: "서비스",
    TextTopicListTreeView: "토픽",
    TextUnreachableChkBox: "연결할 수 없는 노드",
    TitleConnectionSection: "네트워크 연결",
    TitleDoc: "ROS 2 네트워크 그래프",
    TitleDocGroup: "ROS 2 네트워크 그래프",
    TitleExportBtn: "내보내기",
    TitleFilterSection: "필터",
    TitleLayoutSection: "레이아웃",
    TitleNetworkBrowserPnl: "네트워크 브라우저",
    TitlePropertyPnl: "속성",
    TitleTabMain: "ROS 2 네트워크 분석기",
    TitleViewSection: "보기",
    Topics: "토픽",
    UpdateNetworkDepth: "네트워크 심도를 업데이트하는 중..."
});
