function initialize(this,Axes)
%INITIALIZE  Initialization for @UncertainTimeView class

%  Author(s): Craig Buhr
%  Copyright 1986-2010 The MathWorks, Inc.

[s1,s2,s3] = size(Axes); % Ny-by-Nu-by-2
Axes = reshape(Axes,[s1*s2 s3]);

UncertainMagPatch = zeros([s1 s2]);
UncertainPhasePatch = zeros([s1 s2]);


for ct=1:s1*s2       
   UncertainMagPatch(ct) = patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct,1),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
     UncertainPhasePatch(ct) = patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct,2),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
end

this.UncertainMagPatch = handle(UncertainMagPatch);
this.UncertainPhasePatch = handle(UncertainPhasePatch);


UncertainMagLines = zeros([s1 s2]);
UncertainPhaseLines = zeros([s1 s2]);

for ct=1:s1*s2
    UncertainMagLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
        'Parent',Axes(ct,1),...
        'Visible','off',...
        'Selected','off',...
        'XlimInclude','off', 'YlimInclude','on',...
        'HandleVisibility','off','HitTest','off',...
        'Color',[0.9804 .9*0.9804 0.8235]);
    UncertainPhaseLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
        'Parent',Axes(ct,2),...
        'Visible','off',...
        'Selected','off',...
        'XlimInclude','off', 'YlimInclude','on',...
        'HandleVisibility','off','HitTest','off',...
        'Color',[0.9804 .9*0.9804 0.8235]);
end

this.UncertainMagLines = handle(UncertainMagLines);
this.UncertainPhaseLines = handle(UncertainPhaseLines);
