function opts = buildXMLStructOptions(func)
%buildXMLStructOptions   Returns a struct containing common options for readstruct+XML.

%   Copyright 2020 The MathWorks, Inc.

    opts = struct("StructNodeName",       func.StructNodeName, ...
                  "StructSelector",       func.StructSelector, ...
                  "ImportAttributes",     func.ImportAttributes, ...
                  "AttributeSuffix",      func.AttributeSuffix, ...
                  "DetectTypes",          func.DetectTypes, ...
                  "DateLocale",           string(func.DateLocale), ...
                  "RegisteredNamespaces", func.RegisteredNamespaces, ...
                  "DetectNamespaces",     func.DetectNamespaces);

end
