function E = ambiguousNameException(functionName, callSiteInfo, argumentPosition, argumentName, names)
%

%   Copyright 2019-2021 The MathWorks, Inc.

E = matlab.internal.validation.RuntimeNameValueException.createExceptionForAmbiguousName(...
    functionName,...
    callSiteInfo,...
    argumentPosition,...
    argumentName,...
    'MATLAB:functionValidation:AmbiguousInputName',...
    names);
end
