classdef DefaultValueException < matlab.internal.validation.RuntimeArgumentException
%

%   Copyright 2019-2020 The MathWorks, Inc.

    methods
        function E = DefaultValueException(functionName, callSiteInfo, argumentPosition,...
                                           argumentName, errorID, errorMessage)
            E@matlab.internal.validation.RuntimeArgumentException(functionName, callSiteInfo, argumentPosition,...
                                                              argumentName, errorID, errorMessage);
        end
    end
    
    methods(Static)
        function E = createExceptionUsingID(functionName, callSiteInfo, argumentPosition,...
                                            argumentName, errorID, varargin)
            import matlab.internal.validation.DefaultValueException;
            preambleObject = message(DefaultValueException.PreambleID, argumentName);
            messageObject = message(errorID, preambleObject.getString, varargin{:});
            E = DefaultValueException(...
                functionName,...
                callSiteInfo,...
                argumentPosition,...
                argumentName,...
                errorID,...
                messageObject.getString);
        end

        function E = createExceptionUsingIDAndMessage(functionName, callSiteInfo, argumentPosition,...
                                                      argumentName, errorID, errorMessage)
            import matlab.internal.validation.DefaultValueException;
            preambleObject = message(DefaultValueException.PreambleID, argumentName);
            errorMessage = sprintf('%s %s', preambleObject.getString, errorMessage);
            E = DefaultValueException(...
                functionName,...
                callSiteInfo,...
                argumentPosition,...
                argumentName,...
                errorID,...
                errorMessage);
        end
        
        function E = createExceptionUsingCaughtException(functionName, callSiteInfo, argumentPosition,...
                                                         argumentName, CE)
            import matlab.internal.validation.DefaultValueException;
            preambleObject = message(DefaultValueException.PreambleID, argumentName);
            errorMessage = sprintf('%s %s', preambleObject.getString, CE.message);
            E = DefaultValueException(...
                functionName,...
                callSiteInfo,...
                argumentPosition,...
                argumentName,...
                CE.identifier,...
                errorMessage);
        end
    end
    
    properties(Constant, Access=private)
        PreambleID = 'MATLAB:functionValidation:PreambleForDefaultValueError'
    end
end
