function E = lessThanRequiredNumberOfArgumentsException(...
        functionName, callSiteInfo, numUserArgs, validArgs)
%

%   Copyright 2019-2021 The MathWorks, Inc.
    numRequired = sum([validArgs.required]);
    msg = message('MATLAB:functionValidation:NotEnoughInputs', numRequired - numUserArgs).getString;
    E = matlab.internal.validation.RuntimeInputsException.createInputsExceptionUsingIDAndMessage(...
        functionName,...
        numRequired,...
        'MATLAB:minrhs',...
        msg...
        );
end
