function E = numberOfInputsMismatchRepeats(functionName, ~, numberOfRepeatingArgs)
%

%   Copyright 2019-2020 The MathWorks, Inc.

    E = matlab.internal.validation.RuntimeInputsException.createExceptionUsingID(...
        functionName,...
        'MATLAB:functionValidation:RepeatingInputsNotInGroups',...
        numberOfRepeatingArgs...
        );
end
