function E = repeatingOutputNotCell(functionName, ~, ...
        argumentPosition, argumentName, argVal)

    import matlab.internal.validation.RuntimeOutputException

    E = RuntimeOutputException.createExceptionUsingID(...
        functionName,...
        struct.empty,... %% ignore callSiteInfo
        argumentPosition,...
        argumentName,...
        'MATLAB:functionValidation:RepeatingOutputNotCell',...
        class(argVal));
end