classdef RuntimeNameValueException < matlab.internal.validation.RuntimeArgumentException
%

%   Copyright 2019-2021 The MathWorks, Inc.

    methods
        function E = RuntimeNameValueException(functionName, callSiteInfo, argumentPosition,...
                                               argumentName, errorID, errorMessage)
            E@matlab.internal.validation.RuntimeArgumentException(functionName, callSiteInfo,...
                                                                  argumentPosition, argumentName,...
                                                                  errorID, errorMessage);
        end
    end

    methods(Static)
        function E = createExceptionUsingIDAndMessage(functionName, callSiteInfo, argumentPosition,...
                                                      argumentName, errorID, errorMessage)
            import matlab.internal.validation.RuntimeNameValueException;
            preambleObject = message(RuntimeNameValueException.InvalidValuePreamble, argumentName);
            errorMessage = sprintf('%s %s', preambleObject.getString, errorMessage);
            E = RuntimeNameValueException(...
                functionName,...
                callSiteInfo,...
                argumentPosition,...
                argumentName,...
                errorID,...
                errorMessage);
        end
        
        function E = createExceptionForUnrecognizedName(functionName, callSiteInfo, argumentPosition,...
                                                        argumentName, errorID, validNames)
            import matlab.internal.validation.RuntimeNameValueException;
            import matlab.internal.validation.Exception.genFormatedValuesForNamedArguments;
            formatedNames = genFormatedValuesForNamedArguments(validNames);
            preambleObject = message(RuntimeNameValueException.UnrecognizedNamePreamble, argumentName);
            errorMessage = sprintf('%s %s', preambleObject.getString, formatedNames);
            E = RuntimeNameValueException(...
                functionName,...
                callSiteInfo,...
                argumentPosition,...
                argumentName,...
                errorID,...
                errorMessage);
        end

        function E = createExceptionForAmbiguousName(functionName, callSiteInfo, argumentPosition,...
                                                     argumentName, errorID, validNames)
            import matlab.internal.validation.RuntimeNameValueException;
            import matlab.internal.validation.Exception.genFormatedValuesForNamedArguments;
            formatedNames = genFormatedValuesForNamedArguments(validNames);
            preambleObject = message(RuntimeNameValueException.AmbiguousNamePreamble, argumentName);
            errorMessage = sprintf('%s %s', preambleObject.getString, formatedNames);
            E = RuntimeNameValueException(...
                functionName,...
                callSiteInfo,...
                argumentPosition,...
                argumentName,...
                errorID,...
                errorMessage);
        end

        function E = createExceptionUsingCaughtException(functionName, callSiteInfo,...
                                                         argumentPosition, argumentName, CE)
            import matlab.internal.validation.RuntimeNameValueException;
            preambleObject = message(RuntimeNameValueException.InvalidValuePreamble, argumentName);
            errorMessage = sprintf('%s %s', preambleObject.getString, CE.message);
            E = RuntimeNameValueException(...
                functionName,...
                callSiteInfo,...
                argumentPosition,...
                argumentName,...
                CE.identifier,...
                errorMessage);
        end
    end
    
    properties(Constant, Access=private)
        UnrecognizedNamePreamble = 'MATLAB:functionValidation:PreambleForUnrecognizedNameError';
        AmbiguousNamePreamble = 'MATLAB:functionValidation:PreambleForAmbiguousNameError';
        InvalidValuePreamble = 'MATLAB:functionValidation:PreambleForInvalidNameArgumentValueError';
    end
end
    
