function T = setUnixOnlyPermsForTabularDisplay(obj, T, index, perms)
%

%   Copyright 2024 The MathWorks, Inc.

    import matlab.io.internal.filesystem.convertLogicalToPermissions;
    T(index, :).UserExecute = convertLogicalToPermissions(...
        "UserExecute", perms.UserExecute, obj);
    T(index, :).GroupRead = convertLogicalToPermissions(...
        "GroupRead", perms.GroupRead, obj);
    T(index, :).GroupWrite = convertLogicalToPermissions(...
        "GroupWrite", perms.GroupWrite, obj);
    T(index, :).GroupExecute = convertLogicalToPermissions(...
        "GroupExecute", perms.GroupExecute, obj);
    T(index, :).OtherRead = convertLogicalToPermissions(...
        "OtherRead", perms.OtherRead, obj);
    T(index, :).OtherWrite = convertLogicalToPermissions(...
        "OtherWrite", perms.OtherWrite, obj);
    T(index, :).OtherExecute = convertLogicalToPermissions(...
        "OtherExecute", perms.OtherExecute, obj);
end
