%Closure
% A class that represents an operation combined with its corresponding inputs.
%
% Properties:
%              Id: A unique ID.
%           IdStr: Unique ID between closure, promise and future.
%       Operation: The underlying operation of this closure.
%    InputFutures: An ordered list of ClosureFuture instances that
%                  represent each of the inputs to be given the operation.
%  OutputPromises: An ordered list of ClosurePromise instances that
%                  represent each of the outputs generated by the operation.
%
% Methods:
%  obj = Closure(inputFutures, operation, isPartitionIndependent)
%  constructs a closure from the given input futures and operation.
%  isPartitionIndependent is an optional logical scalar or vector of size
%  operation.NumOutputs specifying which of the output promises are
%  partition independent.
%
%  dependencies = getDirectDependencies(obj) Get a list of the closures
%  that this instance directly depends on.
%

% Copyright 2015-2022 The MathWorks, Inc.
