function p = supportsoftwarepathdef
%SUPPORTSOFTWAREPATHDEF Search path defaults.
%   SUPPORTSOFTWAREPATHDEF returns a string that can be used as 
% input to MATLABPATH in order to set the path.

  
%   Copyright 2015 The MathWorks, Inc.


% DO NOT MODIFY THIS FILE.  IT IS AN AUTOGENERATED FILE.  
% EDITING MAY CAUSE THE FILE TO BECOME UNREADABLE TO 
% THE PATHTOOL AND THE INSTALLER.

p = [...
%%% BEGIN ENTRIES %%%
        '<PLEASE FILL IN ONE DIRECTORY PER LINE>:',...
%%% END ENTRIES %%%
     ...
];

%%% Do not add the userpath to p.  
%%% That will always be done by MATLAB only!
