%mlreportgen.ppt.getDefaultNumberFormat Get default formatting for numeric
%data generated by PPT API
%
%    formatSpec = mlreportgen.ppt.getDefaultNumberFormat() returns the
%    default number format specification as a character vector. The
%    specification is a valid format specification for the sprintf
%    function. To set the default number format specification, use
%    mlreportgen.ppt.setDefaultNumberFormat.
%
%    See also mlreportgen.ppt.setDefaultNumberFormat, sprintf,
%    mlreportgen.ppt.Number, mlreportgen.ppt.NumberFormat

%    Copyright 2024 The MathWorks, Inc.
%    Built-in function