function setup(obj)
%

%   Copyright 2020-2021 The MathWorks, Inc.

ax=obj.getAxes;
obj.Axes=ax;
set(ax,'XTick',[],'YTick',[],'Box','On',...
    'Units','Points','ClippingStyle','rectangle',...
    'HitTest','on','Interactions',[zoomInteraction panInteraction])

axtoolbar(ax,'restoreview');

obj.Marker=matlab.graphics.primitive.world.Marker(...
    'Parent',ax,...
    'EdgeColorData',uint8([0;0;0;255]),...
    'FaceColorData',uint8([0;0;0;255]),...
    'FaceColorType','truecoloralpha',...
    'SizeBinding','discrete',...
    'AnchorPointClipping','off',...
    'Style','circle', ...
    'HitTest','on');

obj.HighlightMarker=matlab.graphics.primitive.world.Marker(...
    'Parent',ax,...
    'EdgeColorData',uint8([0;0;0;255]),...
    'FaceColorData',uint8([0;0;0;255]),...
    'FaceColorType','truecoloralpha',...
    'SizeBinding','discrete',...
    'AnchorPointClipping','off',...
    'Style','circle',...
    'Visible','off', ...
    'PickableParts','none');

font=matlab.graphics.general.Font('Name',obj.FontName,'Size',obj.FontSize);

obj.Text=matlab.graphics.primitive.world.Text(...
    'Parent',ax,...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'ColorData',uint8([obj.FontColor*255 255]'),...
    'Font',font,...
    'Visible','off',...
    'PickableParts','none');

addlistener(ax,'OuterPositionChanged',@(~,~)obj.changeChartPosition);

addlistener(ax.Title, 'String', 'PostSet', ...
    @(~,~)set(obj, 'Title', ax.Title.String_I));

obj.Legend=legend(ax,'location','northeastoutside','PickableParts','none');
obj.Legend.Visible=false;

obj.setupLingerListeners;

datatip = matlab.graphics.shape.internal.GraphicsTip(...
    'Parent', obj.Axes, 'HitTest','off', 'PickableParts', 'none',...
    'Visible','off');
datatip.ScribeHost.HitTest = 'off';
datatip.ScribeHost.PickableParts = 'none';
datatip.ScribeHost.getScribePeer.HitTest = 'off';
datatip.ScribeHost.getScribePeer.PickableParts = 'none';
obj.Datatip=datatip;
end

% LocalWords:  YTick truecoloralpha PickableParts northeastoutside
