
classdef CarlaScenario < ros.Message
    %CarlaScenario MATLAB implementation of carla_ros_scenario_runner_types/CarlaScenario
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_ros_scenario_runner_types/CarlaScenario' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '93d5e86b5b9801c6f04e8ec494ca17c3' % The MD5 Checksum of the message definition
        PropertyList = { 'Name' 'ScenarioFile' } % List of non-constant message properties
        ROSPropertyList = { 'name' 'scenario_file' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Name
        ScenarioFile
    end
    methods
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'CarlaScenario', 'Name');
            obj.Name = char(val);
        end
        function set.ScenarioFile(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'CarlaScenario', 'ScenarioFile');
            obj.ScenarioFile = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_ros_scenario_runner_types.CarlaScenario.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_ros_scenario_runner_types.CarlaScenario(strObj);
        end
    end
end
