
classdef CarlaScenarioList < ros.Message
    %CarlaScenarioList MATLAB implementation of carla_ros_scenario_runner_types/CarlaScenarioList
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_ros_scenario_runner_types/CarlaScenarioList' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '81800830fb5128ccb96838817ec89047' % The MD5 Checksum of the message definition
        PropertyList = { 'Scenarios' } % List of non-constant message properties
        ROSPropertyList = { 'scenarios' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.carla_ros_scenario_runner_types.CarlaScenario' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Scenarios
    end
    methods
        function set.Scenarios(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.carla_ros_scenario_runner_types.CarlaScenario.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.carla_ros_scenario_runner_types.CarlaScenario'};
            validateattributes(val, validClasses, validAttributes, 'CarlaScenarioList', 'Scenarios')
            obj.Scenarios = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_ros_scenario_runner_types.CarlaScenarioList.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_ros_scenario_runner_types.CarlaScenarioList(strObj);
        end
    end
end
