
classdef CarlaScenarioRunnerStatus < ros.Message
    %CarlaScenarioRunnerStatus MATLAB implementation of carla_ros_scenario_runner_types/CarlaScenarioRunnerStatus
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_ros_scenario_runner_types/CarlaScenarioRunnerStatus' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '740a173d5d748af3689ca68d3d3cd525' % The MD5 Checksum of the message definition
        PropertyList = { 'Status' } % List of non-constant message properties
        ROSPropertyList = { 'status' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        STOPPED = uint8(0)
        STARTING = uint8(1)
        RUNNING = uint8(2)
        SHUTTINGDOWN = uint8(3)
        ERROR = uint8(4)
    end
    properties
        Status
    end
    methods
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaScenarioRunnerStatus', 'Status');
            obj.Status = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_ros_scenario_runner_types.CarlaScenarioRunnerStatus.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_ros_scenario_runner_types.CarlaScenarioRunnerStatus(strObj);
        end
    end
end
