function c = getCharacteristics(this,PlotType)
%getCharacteristics Gets the characteristics associated with the plot type
% for the data source.

%  Copyright 2010-2015 The MathWorks, Inc.

switch PlotType
   case 'step'
      c(1) = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strPeakResponse'), ...
         'CharacteristicID', 'PeakResponse', ...
         'CharacteristicData', 'resppack.StepPeakRespData',...
         'CharacteristicView', 'resppack.StepPeakRespView', ...
         'CharacteristicGroup', 'Characteristic');
      if isa(this.Model,'idnlgrey')
         c(2) = struct(...
            'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strConfidenceRegion'),...
            'CharacteristicID', 'ConfidenceRegion', ...
            'CharacteristicData', 'resppack.ConfidenceRegionStepTimeData',...
            'CharacteristicView', 'resppack.ConfidenceRegionTimeView', ...
            'CharacteristicGroup', 'Characteristic');
      end
      
   case 'impulse'
      c(1) = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strPeakResponse'), ...
         'CharacteristicID', 'PeakResponse', ...
         'CharacteristicData', 'wavepack.TimePeakAmpData',...
         'CharacteristicView', 'wavepack.TimePeakAmpView', ...
         'CharacteristicGroup', 'Characteristic');
      
      if isa(this.Model,'idnlgrey')
         c(2) = struct(...
            'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strConfidenceRegion'), ...
            'CharacteristicID', 'ConfidenceRegion', ...
            'CharacteristicData', 'resppack.ConfidenceRegionImpulseTimeData',...
            'CharacteristicView', 'resppack.ConfidenceRegionTimeView', ...
            'CharacteristicGroup', 'Characteristic');
      end
      
   case 'lsim'
      c = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strPeakResponse'), ...
         'CharacteristicID', 'PeakResponse', ...
         'CharacteristicData', 'wavepack.TimePeakAmpData',...
         'CharacteristicView', 'wavepack.TimePeakAmpView', ...
         'CharacteristicGroup', 'Characteristic');
      
   otherwise
      c = [];
end
