
classdef GetMetadataResponse < ros.Message
    %GetMetadataResponse MATLAB implementation of ouster_ros/GetMetadataResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ouster_ros/GetMetadataResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'd37888e5a47bef783c189dec5351027e' % The MD5 Checksum of the message definition
        PropertyList = { 'Metadata' } % List of non-constant message properties
        ROSPropertyList = { 'metadata' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Metadata
    end
    methods
        function set.Metadata(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'GetMetadataResponse', 'Metadata');
            obj.Metadata = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ouster_ros.GetMetadataResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ouster_ros.GetMetadataResponse(strObj);
        end
    end
end
