
classdef SetConfigRequest < ros.Message
    %SetConfigRequest MATLAB implementation of ouster_ros/SetConfigRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ouster_ros/SetConfigRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '90949894c75d4db440cc7a08c4bf47dd' % The MD5 Checksum of the message definition
        PropertyList = { 'ConfigFile' } % List of non-constant message properties
        ROSPropertyList = { 'config_file' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ConfigFile
    end
    methods
        function set.ConfigFile(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SetConfigRequest', 'ConfigFile');
            obj.ConfigFile = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ouster_ros.SetConfigRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ouster_ros.SetConfigRequest(strObj);
        end
    end
end
