
classdef SetConfigResponse < ros.Message
    %SetConfigResponse MATLAB implementation of ouster_ros/SetConfigResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ouster_ros/SetConfigResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'b3532af339db184b4a6a974d00ee4fe6' % The MD5 Checksum of the message definition
        PropertyList = { 'Config' } % List of non-constant message properties
        ROSPropertyList = { 'config' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Config
    end
    methods
        function set.Config(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SetConfigResponse', 'Config');
            obj.Config = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ouster_ros.SetConfigResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ouster_ros.SetConfigResponse(strObj);
        end
    end
end
