function c = getCharacteristics(~,PlotType)
%getCharacteristics Gets the characteristics associated with the plot type
% for the data source

%  Copyright 1986-2016 The MathWorks, Inc.

%#function wavepack.FreqPeakGainData
%#function resppack.NoiseSpectrumPeakGainView
%#function wavepack.FreqPeakGainData
%#function resppack.NoiseSpectrumPeakGainView
%#function resppack.ConfidenceRegionSpectrumData
%#function resppack.ConfidenceRegionSpectrumView

switch PlotType
   case 'spectrum'
      c = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strPeakResponse'), ...
         'CharacteristicID', 'PeakResponse', ...
         'CharacteristicData', 'wavepack.FreqPeakGainData',...
         'CharacteristicView', 'resppack.NoiseSpectrumPeakGainView', ...
         'CharacteristicGroup', 'Characteristic');
      
      c(2) = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strConfidenceRegion'), ...
         'CharacteristicID', 'ConfidenceRegion', ...
         'CharacteristicData', 'resppack.ConfidenceRegionSpectrumData',...
         'CharacteristicView', 'resppack.ConfidenceRegionSpectrumView', ...
         'CharacteristicGroup', 'Characteristic');
   case 'spectrumcompareplot'
      % peak response
      c(1) = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strPeakResponse'), ...
         'CharacteristicID', 'PeakResponse', ...
         'CharacteristicData', 'wavepack.FreqPeakGainData',...
         'CharacteristicView', 'resppack.NoiseSpectrumPeakGainView', ...
         'CharacteristicGroup', 'Characteristic');
      
   otherwise
      assert(false,'"idnoisemodelsrc" only handles spectrum plots.')
end
