//
// Copyright 2025 The MathWorks, Inc

// Added the below rules to silence the ESLint warnings

/* eslint-disable max-len */
/* eslint-disable no-template-curly-in-string */
/* eslint-disable quotes */
/* eslint-disable no-useless-escape */

//
// DO NOT MODIFY THIS FILE!!  This is a derived file.
// Instead, modify the English message catalog XML file "resources/ros/en/rosgraphapp/view.xml"
// Encoding: UTF-8
//

define({
    Actions: "アクション",
    ClearFilters: "適用されたフィルターをクリア中...",
    ClearFiltersButton: "フィルターのクリア",
    CopyNameOption: "名前をコピー",
    DataTypes: "メッセージ タイプ",
    DescriptionActionSvcTopicChkBox: "アクションに関連する既定のトピックとサービスを表示します",
    DescriptionAutoArrangehButton: "要素を自動調整します",
    DescriptionConnectButton: "ROS 2 ネットワークに接続します",
    DescriptionDeadSinkChkBox: "サブスクライバーがあるがパブリッシャーがないトピックを表示します",
    DescriptionDefaultChkBox: "/parameters_events と /rosout のトピックを表示します",
    DescriptionDefaultSvcChkBox: "/describe_parameters、/get_parameter_types、および ROS 2 ネットワークに関連するその他の既定サービスを表示します",
    DescriptionDomainIdLabel: "ROS 2 ネットワーク グラフ",
    DescriptionExportBtn: "ネットワーク グラフのスナップショットをエクスポートします",
    DescriptionKeyWordFilterTextArea: "1 つ以上のキーワードをコンマで区切って入力し、Enter キーを押して指定したキーワードを 1 つ以上含む要素を検索します",
    DescriptionLastUpdatedLabel: "ROS 2 ネットワーク グラフ",
    DescriptionLayoutDropDown: "要素を配置するレイアウトを選択します",
    DescriptionLeafTopicChkBox: "パブリッシャーがあるがサブスクライバーがないトピックを表示します",
    DescriptionNameSpaceSpinner: "スピナーを調整して名前空間の深さを設定し、ラベル付き四角形にノードを入れ子にして階層構成を可視化します",
    DescriptionPropertyPnl: "[プロパティ インスペクター] パネル",
    DescriptionRefreshButton: "ROS 2 ネットワークをリフレッシュします",
    DescriptionUnreachableChkBox: "トピックにパブリッシュまたはサブスクライブしない、サービスのサーバーまたはクライアントとして機能しない、アクション サーバーまたはアクション クライアントとして機能しないノードを表示します。",
    EnterNetworkDetails: "ネットワークの詳細を入力",
    ErrorFailedToConnectToNetwork: "ドメイン ID ${0} に接続できません。",
    FilterButton: "フィルターの適用",
    FilterByButton: "次を基準にした高度なフィルター",
    FilterGraph: "ROS 2 ネットワークをフィルター処理中...",
    KeywordFilterPlaceholder: "キーワード、正規表現、または否定キーワードを入力します。",
    KeywordFilterTooltip: "<b>キーワード:</b> 特定の単語 (camera や GPS など) を含むエンティティを抽出します。<br> <b>正規表現:</b> パターン (*camera.*、gps.* など) を使用してエンティティを一致させ、柔軟な検索を行います。<br> <b>除外:</b> キーワードの前に ~ を使用すると (~debug や ~camera など)、エンティティが除外されます。<br> <b>複数入力:</b> 複数のフィルターを入力するには、コンマで区切って入力します。",
    LabelSearch: "検索",
    LayoutBreadthfirst: "breadthfirst",
    LayoutCircle: "circle",
    LayoutConcentric: "concentric",
    LayoutCose: "cose",
    LayoutDagre: "dagre",
    LayoutGrid: "grid",
    LayoutKlay: "klay",
    LoadGraph: "ROS ドメイン ID ${0} のネットワークの詳細を取得中...",
    MessageFilterPlaceholder: "メッセージのタイプ、サービスのタイプ、またはアクションのタイプを入力します。例: sensor_msgs/Image",
    MessageFilterTooltip: "1 つ以上のメッセージのタイプ、サービスのタイプ、アクションのタイプをコンマで区切って入力し、指定したタイプのうち 1 つ以上に該当する要素をフィルターで抽出します。",
    NetworkDepthLabel: "ネットワークの深さ",
    Nodes: "ノード",
    NumberSpinnerTooltip: "スピナーを調整して、フィルター済みのエンティティの周囲に表示される、接続済みのエンティティ レベルの数を設定します。",
    PlaceHolderApplyKeywordFilter: "キーワードを入力して Enter キーを押下",
    PropertyActClient: "アクション クライアント",
    PropertyActClientNodes: "アクション クライアント ノード",
    PropertyActServer: "アクション サーバー",
    PropertyActServerNodes: "アクション サーバー ノード",
    PropertyActType: "アクション タイプ",
    PropertyConnectionType: "接続タイプ",
    PropertyDomainId: "ドメイン ID",
    PropertyEntity: "エンティティ",
    PropertyInformationUnavailable: "情報は利用できません",
    PropertyName: "名前",
    PropertyNodeName: "ノード名",
    PropertyNumberOfActions: "アクション数",
    PropertyNumberOfNodes: "ノード数",
    PropertyNumberOfServices: "サービス数",
    PropertyNumberOfTopics: "トピック数",
    PropertyParameters: "パラメーター",
    PropertyPublisherNodes: "パブリッシャー ノード",
    PropertyPublishesTo: "パブリッシュ先",
    PropertyQOSDeadline: "QoS Deadline",
    PropertyQOSDepth: "QoS Depth",
    PropertyQOSDurability: "QoS Durability",
    PropertyQOSHistory: "QoS History",
    PropertyQOSLeaseDuration: "QoS Lease Duration",
    PropertyQOSLifespan: "QoS Lifespan",
    PropertyQOSLiveliness: "QoS Liveliness",
    PropertyQOSReliability: "QoS Reliability",
    PropertySubscriberNodes: "サブスクライバー ノード",
    PropertySubscribesTo: "サブスクライブ先",
    PropertySvcClient: "サービス クライアント",
    PropertySvcClientNodes: "サービス クライアント ノード",
    PropertySvcServer: "サービス サーバー",
    PropertySvcServerNodes: "サービス サーバー ノード",
    PropertySvcType: "サービス タイプ",
    PropertyTableKeys: "キー",
    PropertyTableValues: "値",
    PropertyTopicName: "トピック名",
    PropertyTopicType: "トピック タイプ",
    Ros2NetworkAnalyzerAppTitle: "ROS 2 ネットワーク アナライザー",
    Services: "サービス",
    TextActionListTreeView: "アクション",
    TextActionSvcTopicChkBox: "アクション トピックとアクション サービス",
    TextAdvancedFilterButton: "高度な\nフィルター",
    TextApplyKeywordFilterBtn: "フィルターの適用",
    TextAutoArrangeButton: "自動\n配置",
    TextConnectButton: "接続",
    TextDeadSinkChkBox: "デッド シンク",
    TextDefaultChkBox: "既定のトピック",
    TextDefaultSvcChkBox: "既定のサービス",
    TextEnterDomainIdBtn: "送信",
    TextExportBtn: "エクスポート",
    TextLabelDomainId: "ドメイン ID",
    TextLayoutLabel: "レイアウト",
    TextLeafTopicChkBox: "リーフ トピック",
    TextNameSpaceSpinnerLbl: "名前空間",
    TextNodeListTreeView: "ノード",
    TextRefreshButton: "リフレッシュ",
    TextServiceListTreeView: "サービス",
    TextTopicListTreeView: "トピック",
    TextUnreachableChkBox: "到達不能ノード",
    TitleConnectionSection: "ネットワーク接続",
    TitleDoc: "ROS 2 ネットワーク グラフ",
    TitleDocGroup: "ROS 2 ネットワーク グラフ",
    TitleExportBtn: "エクスポート",
    TitleFilterSection: "フィルター",
    TitleLayoutSection: "レイアウト",
    TitleNetworkBrowserPnl: "ネットワーク ブラウザー",
    TitlePropertyPnl: "プロパティ",
    TitleTabMain: "ROS 2 ネットワーク アナライザー",
    TitleViewSection: "ビュー",
    Topics: "トピック",
    UpdateNetworkDepth: "ネットワークの深さを更新中..."
});
