function axout = logo(parent)
% Plot the L-shaped membrane logo.

% Copyright 1984-2024 The MathWorks, Inc.

arguments
    parent {mustBeScalarOrEmpty} = gobjects(0)
end

if isempty(parent)
    parent = figure('Name', "MATLAB Logo", 'Theme', 'dark', ...
        'toolbar', 'none', 'menubar', 'none');
end

%% Colors used in the logo
blue = hex2rgb("#0076A8");
yellow = hex2rgb("#CCCC00");
darkred = hex2rgb("#E63333");

%% Create the Logo graphics
if isgraphics(parent,'tiledlayout')
    ax = nexttile(parent);
else
    ax = axes('Parent',parent, ...
        'Units','normalized',...
        'Position', [0 0 1 1.15]);
end

set(ax, ...
    'Visible','off',...
    'DataAspectRatio', [1 1 .9],...
    'XLim',[1 51], ...
    'YLim',[1 51], ...
    'ZLim',[-13 40], ...
    'View', [ -37 32 ]);

axis(ax,'vis3d')

Lm = membrane(1,81)*40;
xd = linspace(1,51,size(Lm,1));
yd = linspace(1,51,size(Lm,2));

surface(ax, xd, yd, Lm, Lm, ...
    'FaceColor', darkred,...
    'EdgeColor', 'none',...
    'FaceLighting', 'gouraud',...
    'BackFaceLighting','lit', ...
    'AmbientStrength',.3, ...
    'DiffuseStrength',.6, ...
    'SpecularStrength',1, ...
    'SpecularColorReflectance',1, ...
    'SpecularExponent',7,...
    'Clipping','off',...
    'Tag', 'TheMathWorksLogo');

%% Lights
% Use two lights for each color to provide the extra-bright specular lighting
% effects.
light(ax, 'Position',[40 100 20], ...
    'Style','local', ...
    'Color',blue);
light(ax, 'Position',[40 100 20], ...
    'Style','local', ...
    'Color',blue*.6);
light(ax, 'Position',[.5 -1 .4], ...
    'Color',yellow);
light(ax, 'Position',[.5 -1 .4], ...
    'Color',yellow*.1);

%% Interactions
% Provide restore view button, and keep only a subset of
% interaction modes enabled.
ax.Toolbar = axtoolbar(ax,{'RestoreView'});
rotate3d(ax,'on')

if nargout > 0
    axout = ax;
end
end
