classdef ReportLayout< mlreportgen.report.Layout
%REPORTLAYOUT Page layout generated by a report.
%    Instances of this object are created by reports and assigned to
%    their Layout property. You do not need to create this object
%    yourself.
%
%    ReportLayout properties:
%      Watermark        - Watermark to be displayed by pages in this layout
%      FirstPageNumber  - Number of first page in this layout
%      PageNumberFormat - Page number format (arabic, roman, etc.)
%      Landscape        - Orientation of pages in this layout
%      PageSize         - Height and width of pages in this layout
%      PageMargins      - Size of page margins in this layout
%      PageBorder       - Border of pages in this layout

 
    
    %    Copyright 2017-2021 The MathWorks, Inc.

    methods
        function out=ReportLayout
        end

    end
end
