classdef SectionTitle< mlreportgen.report.Title
%   SECTIONTITLE Generate a section title
%    An instance of this class can be created only by another reporter
%    called the owner. The instance fills a hole in a template that the
%    owner specifies with a title that the owner specifies via an
%    instance template and instance properties that it sets. For
%    example, a Section reporter (the owner) uses an instance of this
%    class to fill the Title hole in its template with a hierarchically
%    numbered title.
%
%    The title generated by an instance of this class consists of
%    static text and dynamic content. The static text is specified by
%    the instance template. The dynamic content is specified by the
%    instance Content, NumberPrefix, and NumberSuffix properties. If
%    the name of a template hole matches one of these property names,
%    this reporter fills the hole with the value property. For example,
%    if the title template contains a Content hole and a NumberPrefix
%    hole, this reporter fills those holes with the values of the
%    corresponding properties.
%
%    The owner specifies the location of the title template via the
%    instance TemplateSrc, TemplateName, and OutlineLevel properties.
%    The TemplateSrc specifies the source of a template file whose
%    template library contains the title template. The TemplateName
%    property specifies the root name of the title template. The
%    OutlineLevel property specifies the level in the report hierarchy
%    of the content generated by the owner. The SectionTitle instance
%    appends the OutlineLevel to the TemplateName to create the full
%    name of the title template. For example, the Section reporter
%    template library contains six numbered title templates, each
%    corresponding to a section level. The names of the templates are
%    SectionNumberedTemplate1, SectionNumberedTemplate2, etc. To
%    specify use the SectionNumberedTemplate1 template to generate a
%    section title, the Section reporter sets the SectionTitle
%    TemplateName property to SectionNumberedTemplate and the
%    OutlineLevel property to 1.
%
%    If the SectionTitle LinkTarget property is set, the instance
%    precedes the generated title with a link target having the
%    specified target id.
%
%    SectionTitle properties:
%      HoleId         - Name of title hole in owner template
%      Content        - Title text
%      NumberPrefix   - Prefix for a section number in the title
%      NumberSuffix   - Suffix for a section number in the title
%      Translations   - Translations for the title prefix and suffix
%      OutlineLevel   - Outline level of owner reporter
%      TemplateSrc    - SectionTitle reporter's template source
%      TemplateName   - Template root name
%      LinkTarget     - Hyperlink target for this reporter
%
%    See also mlreportgen.report.Section.getTitleReporter,
%    mlreportgen.report.Chapter.getTitleReporter

     
    %   Copyright 2017-2019 The MathWorks, Inc.

    methods
        function out=getClassFolder(~) %#ok<STOUT>
        end

        function out=updateImplTemplateName(~) %#ok<STOUT>
        end

    end
    properties
        % OutlineLevel Level of owner reporter in report section hierarchy
        %    Specifies level of section generated by the owner reporter in
        %    a report's section hierarchy. The SectionTitle appends the
        %    value of this property to the value of the TemplateName to
        %    create the full name of the title template. For example, if
        %    the TemplateName is SectionNumberedTitle and the OutlineLevel
        %    is 2, this reporter generates SectionNumberedTitle2 as the
        %    full name of the title template. The template library 
        %    specified by the TemplateSrc property must contain a template
        %    with the generated name. Otherwise, an error occurs.
        OutlineLevel;

    end
end
