classdef Title< mlreportgen.report.HoleReporter
%TITLE Title Reporter for other reporters like chapter, image, tables, etc.
%    An instance of this class can be created only by another reporter
%    called the owner. The instance fills a hole in a template that the
%    owner specifies with a title that the owner specifies via an
%    instance template and instance properties that it sets. For
%    example, the BaseTable reporter (the owner) uses an instance of
%    this class to fill the Title hole in its template with a
%    hierarchically numbered title.
%
%    The title generated by an instance of this class consists of
%    static text and dynamic content. The static text is specified by
%    the instance template. The dynamic content is specified by the
%    instance Content, NumberPrefix, and NumberSuffix properties. If
%    the name of a template hole matches one of these property names,
%    this reporter fills the hole with the value property. For example,
%    if the title template contains a Content hole and a NumberPrefix
%    hole, this reporter fills those holes with the values of the
%    corresponding properties.
%
%    The owner specifies the location of the title template via the
%    instance TemplateSrc and TemplateName properties. The TemplateSrc
%    specifies the source of a template file whose template library
%    contains the title template. The TemplateName property specifies
%    the name of the title template. For example, the BaseTable
%    reporter template library contains two numbered title templates,
%    one named BaseTableNumberedTitle for numbered tables and one named
%    BaseTableHierNumberedTitle for hierarchically numbered tables. The
%    BaseTable reporter specifies which template to use by setting this
%    reporter's TemplateSrc property to the BaseTable template and this
%    reporter's TemplateName property to the title template name.
%
%    The owner can also generate a hyperlink target in front of the
%    title by setting this reporter's LinkTarget to the id of the
%    link target.
%
%    Title properties:
%      HoleId         - Name of hole to be filled by this reporter
%      Content        - Content of hole to be filled by this reporter
%      NumberPrefix   - Prefix for the title content
%      NumberSuffix   - Suffix for the title content
%      Translations   - Translations for the title prefix and suffix
%      TemplateSrc    - Title reporter's template source
%      TemplateName   - Template name
%      LinkTarget     - Hyperlink target for this reporter
%
%    See also mlreportgen.report.BaseTable.getTitleReporter

     
    %   Copyright 2017-2021 The MathWorks, Inc.

    methods
        function out=getClassFolder(~) %#ok<STOUT>
        end

        function out=getImpl(~) %#ok<STOUT>
        end

    end
    properties
        % Content Content of hole to be filled by this reporter
        %    Specifies the content of the hole to be filled by this
        %    reporter. You can use any of the following to specify the
        %    hole content
        %
        %        - MATLAB string
        %        - character array
        %        - DOM object
        %        - 1xN or Nx1 array of strings or DOM objects
        %        - 1xN or Nx1 cell array of strings, character arrays,
        %          and/or DOM objects
        Content;

        % NumberPrefix Prefix for the title content
        %    Specifies the prefix for the title content. If nothing is
        %    specified, a default title prefix for the reporter, translated
        %    based on the report locale, is used.
        %
        % See also mlreportgen.report.Title.Translations,
        % mlreportgen.report.Report.Locale
        NumberPrefix;

        % NumberSuffix Suffix for the title content
        %    Specifies the suffix for the title content. If nothing is
        %    specified, a default title suffix for the reporter, translated
        %    based on the report locale, is used.
        %
        % See also mlreportgen.report.Title.Translations,
        % mlreportgen.report.Report.Locale
        NumberSuffix;

        % Translations Title translations
        %    Specifies translations for the content of the title 
        %    generated by this reporter. The value of this property
        %    is a structure containing three fields, each of which is
        %    empty by default:
        %
        %    Translations.NumberPrefixSuffix
        %
        %    If this field is empty (the default), title number prefixes
        %    and suffixes are not translated. To generate localized
        %    versions of the title's number prefix and suffix, the title
        %    owner sets this field to a MATLAB containers.Map object that
        %    maps a locale key to a struct containing the translations of
        %    the NumberPrefix and NumberSuffix. The value struct must
        %    contain the following fields:
        %
        %       Locale            - Locale id of the locale, e.g., 'en'
        %       TitleNumberPrefix - Locale-specific number prefix,
        %                           e.g., "Chapter "
        %       TitleNumberSuffix - Locale-specific number suffix, e.g.,
        %                           ". "
        %
        %    Translations.Content
        %
        %    If this field is empty, title content is not translated. To
        %    generate localized versions of the title content, the title
        %    reporter owner sets this field to a containers.Map object that
        %    maps a locale key to the translation of the title content. If
        %    the value of this field is not empty and the value of this
        %    reporter's Content property is empty, this reporter uses the
        %    Content map to look up a localized version of the title
        %    content.
        %
        %    Translation.Owner
        %
        %    This property is used to find a default title content 
        %    translation specified by the title owner reporter. It is for
        %    internal use only.
        %
        %    Note: If the specified translation map does not contain 
        %    translation for the specified report locale, "en" locale is
        %    used as the locale for the title, prefix, and suffix.
        %
        %    See also mlreportgen.report.Title.NumberPrefix,
        %    mlreportgen.report.Title.NumberSuffix,
        %    mlreportgen.report.Report.Locale,
        %    mlreportgen.report.ReporterBase.parseTranslation,
        %    mlreportgen.report.ReporterBase.getTranslation
        Translations;

    end
end
