%matlab.io.xml.transform.Transformer Defines an XML document transformer
%    transformer = Transformer() creates an XML document transformer.
%
%    Transformer methods:
%       clearStylesheetParams - Clear stylesheet parameters
%       compileStylesheet     - Compile a stylesheet
%       setStylesheetParam    - Set a stylesheet parameter
%       transform             - Transform an XML document
%       transformToString     - Transform XML document into a string    
%
%    Transformer properties:
%       IndentAmount               - Pretty print indent amount
%       ExternalSchemaLocation     - Location of schema using namespaces
%       ExternalNoNSSchemaLocation - Location of schema without namespaces
%       OutputEncoding             - Output character encoding scheme
%       UseValidation              - Validate input document and stylesheet
%       EntityResolver             - Resolver for stylesheet entities
%       Tracer                     - Stylesheet execution tracer
%
%    Transformer supports use of many but not all standard XPath functions
%    in stylesheets. See the help for matlab.io.xml.xpath.Evaluator
%    class for a list of supported XPath functions. Transformer also
%    supports the following standard xslt functions in stylesheets:
%
%    current
%    document
%    element-available
%    format-number
%    function-available
%    generate-id
%    key
%    system-property
%    unparsed-entity-uri
%
%    See https://www.w3.org/TR/xslt-10/#add-func for definitions and 
%    usage of these functions.
%
%    See also matlab.io.xml.xpath.Evaluator

%    Copyright 2020-2021 MathWorks, Inc.
%    Built-in class

%{
properties
     %IndentAmount Pretty print indent amount
     %    Specifies the number of spaces used to pretty print XML output
     %    generated by the transformer. The default is four spaces. The
     %    term pretty print refers to the use of new line and space
     %    characters in the transformed output to indicate XML document
     %    hierarchy. For example, the following output illustrates the use
     %    of pretty printing to represent a document hierarchy consisting
     %    of a para element containing a text element:
     %
     %    <para>
     %        <text>Hello World</text>
     %    </para>    
     %
     %    Note
     %
     %    A transformer pretty prints output only if the stylesheet 
     %    output element (xsl:output) specifies that the output 
     %    should be indented XML.
     %
     IndentAmount;

     %
     %ExternalSchemaLocation Location of external schema
     %    Specifies local file system path of schema to be used to 
     %    validate document to be transformed. Applies only to input
     %    documents that use namespaces to name elements and attributes.
     ExternalSchemaLocation;

     %ExternalNoNSSchemaLocation Location of no-namespace schema
     %    Specifies local file system path of schema to be used to 
     %    validate document to be transformed. Applies only to input
     %    documents that do not use namespaces to name elements and 
     %    attributes.
     ExternalNoNSSchemaLocation;
    
     %OutputEncoding Character encoding of output document
     %    Specifies character encoding used to encode transform output.
     %    Valid values are "UTF-8" (default) and "UTF-16". 
     OutputEncoding;

     %UseValidation Whether to validate input document and stylesheet
     %    If true (default is false), this property causes the
     %    transformer's transform method to validate the input document 
     %    and stylesheet.
     %    
     UseValidation;

    %EntityResolver Object that resolves stylesheet entity references
    %    The value of this property is empty by default. To enable a
    %    parser to resolve entities referenced by a stylesheet, 
    %    subclass matlab.io.xml.document.EntityResolver and set this
    %    property to an instance of the subclass.
    %
    %    See also matlab.io.xml.dom.EntityResolver
    EntityResolver;

    %Tracer Stylesheet execution tracer
    %    The value of this property is an object that enables you to
    %    trace execution of a stylesheet.
    %
    %    See also matlab.io.xml.transform.Tracer
    Tracer;

end
%}