function initialize(this, ax, gridsize)
%  INITIALIZE  Initializes the @timeplot objects.
%
%  INITIALIZE(H,AX,[M N]) creates an @axesgrid object of size MxN
%  to display response plots.

%  Author(s): Bora Eryilmaz
%  Copyright 1986-2011 The MathWorks, Inc.

% Axes geometry parameters
geometry = struct('HeightRatio',[],...
   'HorizontalGap', 16, 'VerticalGap', 16, ...
   'LeftMargin', 12, 'TopMargin', 20);

% Create @axesgrid object
this.AxesGrid = ctrluis.axesgrid(gridsize, ax, ...
   'Visible',     'off', ...
   'Geometry',    geometry, ...
   'LimitFcn',  {@updatelims this}, ...
   'Title',    getString(message('Controllib:plots:strTimeResponse')), ...
   'XLabel',  getString(message('Controllib:plots:strTime')),...
   'YLabel',  getString(message('Controllib:plots:strAmplitude')),...
   'XScale',  'linear',...
   'YScale',  'linear',...
   'XUnit',  'seconds');
             
% Generic initialization
init_graphics(this)

% Add listeners
addlisteners(this)