function h = ghandles(this)
%GHANDLES  Returns a 3-D array of handles of graphical objects associated
%          with a bodeview object.

%  Copyright 1986-2021 The MathWorks, Inc.
h = cat(4,...
   cat(3, this.MagCurves, this.PhaseCurves),...
   cat(3, this.MagPosArrows, this.PhasePosArrows),...
   cat(3, this.MagNegArrows, this.PhaseNegArrows),...
   cat(3, this.MagNyquistLines, this.PhaseNyquistLines));