function initialize(this,Axes)
%  INITIALIZE  Initializes @bodeview objects.

%  Author(s): Bora Eryilmaz, John Glass, Kamesh Subbarao
%  Copyright 1986-2021 The MathWorks, Inc.

% Get axes in which responses are plotted
[s1,s2,s3] = size(Axes);  % Ny-by-Nu-by-2
Axes = reshape(Axes,[s1*s2 s3]);

% Create mag & phase curves & nyquist lines
MagCurves = repmat(wrfc.createDefaultHandle,[s1,s2]);
MagPosArrows = repmat(wrfc.createDefaultHandle,[s1,s2]);
MagNegArrows = repmat(wrfc.createDefaultHandle,[s1,s2]);
MagNyquistLines = repmat(wrfc.createDefaultHandle,[s1,s2]);
PhaseCurves = repmat(wrfc.createDefaultHandle,[s1,s2]);
PhasePosArrows = repmat(wrfc.createDefaultHandle,[s1,s2]);
PhaseNegArrows = repmat(wrfc.createDefaultHandle,[s1,s2]);
PhaseNyquistLines = repmat(wrfc.createDefaultHandle,[s1,s2]);
for ct=1:s1*s2
   MagCurves(ct) = handle(line('XData', NaN, 'YData', NaN, ...
      'Parent', Axes(ct,1), 'Visible', 'off'));
   MagPosArrows(ct) = handle(patch(NaN,NaN,'w',...
      'Parent',Axes(ct,1),'Visible','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HitTest','off','HandleVisibility','off'));
   MagNegArrows(ct) = handle(patch(NaN,NaN,'w',...
      'Parent',Axes(ct,1),'Visible','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HitTest','off','HandleVisibility','off'));
   MagNyquistLines(ct) = handle(line('XData', NaN, 'YData', NaN, ...
      'Parent', Axes(ct,1), 'Visible', 'off' , ...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility', 'off', 'HitTest', 'off', 'Color', [0 0 0]));
   % Phase
   PhaseCurves(ct) = handle(line('XData', NaN, 'YData', NaN, ...
      'Parent', Axes(ct,2), 'Visible', 'off'));
   PhasePosArrows(ct) = handle(patch(NaN,NaN,'w',...
      'Parent',Axes(ct,2),'Visible','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HitTest','off','HandleVisibility','off'));
   PhaseNegArrows(ct) = handle(patch(NaN,NaN,'w',...
      'Parent',Axes(ct,2),'Visible','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HitTest','off','HandleVisibility','off'));
   PhaseNyquistLines(ct) = handle(line('XData', NaN, 'YData', NaN, ...
      'Parent', Axes(ct,2), 'Visible', 'off' , ...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility', 'off', 'HitTest', 'off', 'Color', [0 0 0]));
end
this.MagCurves = MagCurves;
this.MagPosArrows = MagPosArrows;
this.MagNegArrows = MagNegArrows;
this.MagNyquistLines = MagNyquistLines;
this.PhaseCurves = PhaseCurves;
this.PhasePosArrows = PhasePosArrows;
this.PhaseNegArrows = PhaseNegArrows;
this.PhaseNyquistLines = PhaseNyquistLines;