function initialize(this, ax, gridsize)
%  INITIALIZE  Initializes the @sigmaplot objects.

%  Author(s): K. Subbarao
%  Copyright 1986-2011 The MathWorks, Inc.

% Axes geometry parameters 
geometry = struct('HeightRatio',[],...
   'HorizontalGap', 16, 'VerticalGap', 16, ...
   'LeftMargin', 12, 'TopMargin', 20);

% Create @axesgrid object
this.AxesGrid = ctrluis.axesgrid([1 1], ax, ...
   'Visible',     'off', ...
   'Geometry',     geometry, ...
   'LimitFcn',    {@updatelims this}, ...
   'Title',       getString(message('Controllib:plots:strSingularValues')), ...
   'XLabel',      getString(message('Controllib:plots:strFrequency')),...
   'XScale',      'log',...
   'XUnit',       'rad/s',...
   'YLabel',      getString(message('Controllib:plots:strSingularValues')),...
   'YScale',      'linear',...
   'YUnit',       'dB');

% Generic initialization
init_graphics(this)

% Add standard listeners
addlisteners(this)

