%mlreportgen.dom.KeepWithinPage Keeps content generated by table within the same page
%    obj = KeepWithinPage() keeps content generated by table within the same page.
%
%    obj = KeepWithinPage(tf) keeps content generated by table within the same page
%    if tf is specified as true.
%
%    Note: this format applies only to Table, FormalTable and MATLABTable 
%          in Microsoft Word and PDF documents.
%
%    KeepWithinPage properties:
%        Id       - Id of this object
%        Tag      - Tag of this object
%        Value    - Whether to keep DOM object within the same page

%    Copyright 2022 Mathworks, Inc.
%    Built-in class

%{
properties
     %Value Whether to keep table within the same page
     %
     %      Valid values:
     %
     %      true  - keep table within the same page
     %      false - allow a page break between this table
     %
     Value;
     
     %Id Id of this object
     %      Id of this object.
     Id;

     %Tag Tag of this object
     %      Tag of this object.
     Tag;
end
%}