function bool = isobject(value)
%

% Copyright 2016-2020 The MathWorks, Inc.

bool = ...
    builtin('isobject',value) || ...
    isjava(value) || ...
    isa(value, 'function_handle') || ...
    isa(value, 'handle.handle');
end
