function names = allPluginMethodNames()
% This function is unsupported and might change or be removed without 
% notice in a future version.

% Copyright 2021-2023 The MathWorks, Inc.

names = [ ...
    "runTaskGraph", ...
    "createBuildFixture", ...
    "setupBuildFixture", ...
    "teardownBuildFixture", ...
    "createTaskContext", ...
    "runTask", ...
    "runTaskAction", ...
    "skipTask", ...
    ];
end

