function initialize(this, Parent)
%INITIALIZE  Initializes @SectorIndexView objects.


%  Copyright 2015 The MathWorks, Inc.


if ishghandle(Parent,'hggroup')
    set(Parent,'HitTest','off')
end

this.Curves = handle(patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Parent,...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]));