function initialize(this,Axes)
%INITIALIZE  Initialization for @TimePeakRespView class.

%  Copyright 2013-2015 The MathWorks, Inc.
sz = size(Axes);
nr = sz(1); nc = sz(2);
VLines = repmat(wrfc.createDefaultHandle,[nr,nc]);
HLines = repmat(wrfc.createDefaultHandle,[nr,nc]);
Points = repmat(wrfc.createDefaultHandle,[nr,nc]);
for ct = 1:nr*nc
   % Plot vertical lines
   VLines(ct) = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct),...
      'Visible','on',...
      'LineStyle','-.',...
      'Selected','off',...
      'XlimInclude','off', ...
      'YlimInclude','off',...
      'HandleVisibility','off', ...
      'HitTest','off'));
   matlab.graphics.internal.themes.specifyThemePropertyMappings(VLines(ct),...
       'Color',"--mw-graphics-colorNeutral-line-secondary");
   % Plot horizontal lines
   HLines(ct) = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct),...
      'Visible','on',...
      'LineStyle','-.',...
      'Selected','off',...
      'XlimInclude','off', ...
      'YlimInclude','off',...
      'HandleVisibility','off', ...
      'HitTest','off'));
   matlab.graphics.internal.themes.specifyThemePropertyMappings(HLines(ct),...
       'Color',"--mw-graphics-colorNeutral-line-secondary");
   
   % Plot characteristic points
   Points(ct) = handle(line(NaN,NaN,5,...
      'Parent',Axes(ct),...
      'XlimInclude','off',...
      'YlimInclude','off',...
      'Visible','off',...
      'Marker','o',...
      'MarkerSize',6,...
      'Tag','CharPoint'));
end

this.VLines = VLines;
this.HLines = HLines;
this.Points = Points;
this.PointTips = cell([nr nc]);
