function s = struct(h)
%STRUCT  Converts to structure

%   Copyright 1986-2004 The MathWorks, Inc.
s = struct(...
   'Color',h.Color,...
   'FontAngle',h.FontAngle,...
   'FontSize',h.FontSize,...
   'FontWeight',h.FontWeight,...
   'XColor',h.XColor,...
   'YColor',h.YColor,...
   'GridColor',h.GridColor);