classdef Constants
    %CONSTANTS contains the constant property values for the appspace
    %components.

    % Copyright 2020-2022 The MathWorks, Inc.

    properties(Constant)
        BaseGrid = struct( ...
            'RowHeight', ["1x", "1x"], ...
            'ColumnWidth', "1x", ...
            'Padding', [0 0 0 0], ...
            'RowSpacing', 0, ...
            'ColumnSpacing', 0 ...
            );

        %% CommunicationLog Panel
        CommunicationLogLayout = matlabshared.transportapp.internal.utilities.forms.AppSpaceGridLayout(1,1)
        CommunicationLog = struct("Title", message("transportapp:appspace:appspace:CommunicationLogName").getString(), ...
            "TitlePosition", "lefttop", ...
            "FontSize", 12, ...
            "FontWeight", "bold");

        %% Code Log Panel
        CodeLogLayout = matlabshared.transportapp.internal.utilities.forms.AppSpaceGridLayout(2,1)
        CodeLog = struct("Title", message("transportapp:appspace:appspace:CodeLogName").getString(), ...
            "TitlePosition", "lefttop", ...
            "FontSize", 12, ...
            "FontWeight", "bold");

        %% Property Inspector Panel
        PropertyInspectorGrid = struct( ...
            'RowHeight', "1x", ...
            'ColumnWidth', "1x", ...
            'Padding', [0 0 0 0], ...
            'RowSpacing', 0, ...
            'ColumnSpacing', 0 ...
            )
        PropertyInspectorLayout = matlabshared.transportapp.internal.utilities.forms.AppSpaceGridLayout()
    end
end
