function opts = buildJSONStructOptions(func)
%buildJSONStructOptions   Returns a struct containing common options for readstruct for JSON files.

%   Copyright 2023-2024 The MathWorks, Inc.

    opts = struct("StructNodeName",          func.StructNodeName, ...
                  "StructSelector",          func.StructSelector, ...
                  "DateLocale",              string(func.DateLocale), ...
                  "AllowComments",           func.AllowComments, ...
                  "AllowInfAndNaN",          func.AllowInfAndNaN, ...
                  "AllowTrailingCommas",     func.AllowTrailingCommas, ...
                  "OverflowToInfinity",      func.OverflowToInfinity, ...
                  "UseFullPrecision",        func.UseFullPrecision, ...
                  "HomogenizeArrayElements", func.HomogenizeArrayElements);

end
