classdef ArduinoDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
% Arduino data plugin for Hardware Manager app

% Copyright 2021-2024 The MathWorks, Inc.

    properties(Constant)
        AppletIcon = "arduinoExplorerApp"
        HardwareSetupIcon = "settings_hardware"
        MLArduinoIOBaseCode = "ML_ARDUINO"
        ProductShortName = "arduinoio"
        MLDocShortName = "matlab"
        TroubleshootingDocTopicID = "arduinoio_troubleshooting"
        ArdExplLearnMoreDocTopicID = "arduinoexplorer_intro"
        LearnMoreDocShortName = "matlab"
        MLHwSetupLearnMoreDocTopicID = "arduinoio_arduino_setup"
        SLDocShortName = "simulink"
        SLHwSetupLearnMoreDocTopicID = "arduino_setup"
        SLArduinoBaseCode = "ARDUINO"
        SimulinkBaseCode = "SL"

        % To Create Arduino Getting Started Example Data
        displayName = getString(message("hwmanagerapp:clientappdata:arduinoexplorer:slArduinoModelDisplayName"));
        description = getString(message("hwmanagerapp:clientappdata:arduinoexplorer:slArduinoModelDescription"));
        iconID = "examples";
        exampleName = "arduino/GettingStartedWithArduinoRHardwareExample";
        learnMoreLink = matlab.hwmgr.internal.data.DataFactory.createLinkData("learn more", "https://www.mathworks.com/help/simulink/supportpkg/arduino_ref/getting-started-with-arduino-hardware.html");      
        identifierReference = "arduino_gettingstarted identifier";
    end

    methods

        function obj = ArduinoDataPlugin()

        % Troubleshooting in MATLAB Support Package for Arduino
            troubleshootingLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
                obj.MLDocShortName, ...
                obj.TroubleshootingDocTopicID,...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:mlArduinoTroubleshooting")));

            % Learn more about Arduino Explorer and Arduino Hardware setup
            ardExplLearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
                obj.MLDocShortName, ...
                obj.ArdExplLearnMoreDocTopicID,...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:arduinoExplorerLearnMore")));

            mlArdHWSetuplLearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
                obj.MLDocShortName, ...
                obj.MLHwSetupLearnMoreDocTopicID,...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:mlArduinoHardwareSetupDescription")));

            slArdHWSetuplLearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
                obj.SLDocShortName, ...
                obj.SLHwSetupLearnMoreDocTopicID,...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:slArduinoHardwareSetupDescription")), ...
                "https://www.mathworks.com/help/simulink/setup-and-configuration-arduino.html");

            % Create Arduino Explorer applet data
            ardExplAppData = matlab.hwmgr.internal.data.DataFactory.createAppletData(...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:arduinoExplorerTitle")),...
                "arduinoioapplet.ArduinoExplorerApplet",...
                "matlab.hwmgr.plugins.ArduinoPlugin",...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:arduinoExplorerLearnMore")),...
                obj.AppletIcon, ardExplLearnMoreLink, troubleshootingLink,...
                "SupportPackageBaseCodes", obj.MLArduinoIOBaseCode);
            obj.addAppletData(ardExplAppData);

            % Create AddOn Data for the Simulink toolbox since Hardware
            % Setup (Simulink) depends on it
            slToolboxAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.SimulinkBaseCode,...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:slToolboxAddOnName")));
            obj.addAddOnData(slToolboxAddOnData);

            % Create AddOn Data for the MATLAB Support Package for Arduino Hardware
            mlArduinoioAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.MLArduinoIOBaseCode,...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:mlArduinoSPKGFullName")));
            obj.addAddOnData(mlArduinoioAddOnData);

            % Create AddOn Data for the MATLAB Support Package for Arduino Hardware
            slArduinoioAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.SLArduinoBaseCode,...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:slArduinoSPKGFullName")), ...
                obj.SimulinkBaseCode);
            obj.addAddOnData(slArduinoioAddOnData);

            mlHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
				getString(message("hwmanagerapp:clientappdata:arduinoexplorer:mlArduinoHardwareSetupTitle")),...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:mlArduinoHardwareSetupDescription")),...
                obj.HardwareSetupIcon,...
                mlArdHWSetuplLearnMoreLink,...
                "matlab.hwmgr.internal.hwsetup.register.ArduinoWorkflow",...
                'SupportPackageBaseCodes', obj.MLArduinoIOBaseCode, ...
                'WorkflowArgs', ["tripwire", "setup"]);

            obj.addHardwareSetupData(mlHardwareSetupData);

            slHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
				getString(message("hwmanagerapp:clientappdata:arduinoexplorer:slArduinoHardwareSetupTitle")),...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:slArduinoHardwareSetupDescription")),...
                obj.HardwareSetupIcon,...
                slArdHWSetuplLearnMoreLink,...
                "matlab.hwmgr.internal.hwsetup.register.ArduinoSLWorkflow",...
                "ToolboxBaseCodes", obj.SimulinkBaseCode, ...
                'SupportPackageBaseCodes', obj.SLArduinoBaseCode);

            obj.addHardwareSetupData(slHardwareSetupData);

            % Create the hardware keyword data

            % Set the "KeywordRelatedBaseCodes" NV pair since the app has a
            % dependency on the Arduino Support Package
            keywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData( ...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:arduinoKeyword")),...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:arduinoDescription")),...
                getString(message("hwmanagerapp:clientappdata:arduinoexplorer:arduinoTooltip")),...
                "HardwareType",...
                "KeywordRelatedBaseCodes",[obj.MLArduinoIOBaseCode, obj.SLArduinoBaseCode]);
            obj.addHardwareKeywordData(keywordData);

            featureData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
                obj.displayName, ...
                obj.description, ...
                obj.iconID, ...
                obj.learnMoreLink, ...
                obj.exampleName, ...
                [],...
                obj.identifierReference, ...
                "ToolboxBaseCodes", obj.SimulinkBaseCode, ...
                'SupportPackageBaseCodes', obj.SLArduinoBaseCode);
            obj.addExampleData(featureData);

        end
    end
end
