classdef EmbeddedLinuxExplorerDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
    %EMBEDDEDLINUXEXPLORERDATAPLUGIN data plugin class for the Embedded
    %Linux Explorer app
    
    % Copyright 2022-2023 The MathWorks, Inc.

    methods
        function obj = EmbeddedLinuxExplorerDataPlugin()
            % link to the trouble shooting connection page
            troubleshootingLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
                "soc", "embeddedLinuxExplorerTroubleshooting",...
                string(message("hwmanagerapp:clientappdata:embeddedlinuxexplorer:TroubleshootTitle").getString),...
                string(['https://www.mathworks.com/help/releases/R', version("-release"), '/soc/ref/embeddedlinuxexplorer-app.html']));

            % link to learn more
            learnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
                "soc", "app_embeddedlinuxexplorer",...
                string(message("hwmanagerapp:clientappdata:embeddedlinuxexplorer:AppName").getString),...
                string(['https://www.mathworks.com/help/releases/R', version("-release"), '/soc/ref/embeddedlinuxexplorer-app.html']));

            % applet data
            appletData = matlab.hwmgr.internal.data.DataFactory.createAppletData(...
                string(message("hwmanagerapp:clientappdata:embeddedlinuxexplorer:AppName").getString),...
                "soc.embeddedlinuxexplorer.Applet", "matlab.hwmgr.plugins.SoCPlugin",...
                string(message("hwmanagerapp:clientappdata:embeddedlinuxexplorer:Description").getString),...
                "embeddedLinuxExplorerApp",...
                learnMoreLink, troubleshootingLink, "ToolboxBaseCodes", "HW");
            obj.addAppletData(appletData);

            % AddOn Data
            socAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData(...
                "HW", "SoC Blockset");
            obj.addAddOnData(socAddOnData);

            % HardwareKeywordData
            map = containers.Map(["AMD-Xilinx", "Intel"], ...
                {"HW", "HW"});
            keywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData(...
                string(message("hwmanagerapp:clientappdata:embeddedlinuxexplorer:HWName").getString),...
                string(message("hwmanagerapp:clientappdata:embeddedlinuxexplorer:Description").getString),...
                string(message("hwmanagerapp:clientappdata:embeddedlinuxexplorer:Tooltip").getString),...
                "HardwareType", "Manufacturers", map);
            obj.addHardwareKeywordData(keywordData);
        end
    end
end