classdef ModbusExplorerDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
    %MODBUSEXPLORERPLUGINBASE is the Plugin class for the Modbus Explorer
    %app. It provides relevant app, hardware, and add-on information to
    %Hardware Manager.

    %   Copyright 2021-2024 The MathWorks, Inc.

    properties (Constant)
        %% Add-On Constants
        ProductCode (1, 1) string = "OT"
        ToolboxName (1, 1) string = message("hwmanagerapp:clientappdata:modbusexplorer:ToolboxName").getString

        %% AppletData Constants
        AppName (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:AppName").getString

        AppDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:AppDescription").getString

        AppIcon (1, 1) string =  "modbusExplorerApp"

        % Product name for documentation link creation.
        ProductShortName (1,1) string = "icomm"
        % Topic ID corresponding to Modbus Explorer App docmentation.
        ModbusExplorerAppDocTopicID (1,1) string = "modbus_explorer_app"

        % Learn More Link
        LearnMoreText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:LearnMoreText").getString
        LearnMoreURL (1, 1) string = ...
            "https://www.mathworks.com/help/icomm/ug/modbusexplorer-app.html"
        LearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ProductShortName, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ModbusExplorerAppDocTopicID, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.LearnMoreText, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.LearnMoreURL ...
            )

        % Troubleshooting Link.
        TroubleshootingText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:TroubleshootingText").getString
        TroubleshootingURL (1, 1) string = ...
            "https://www.mathworks.com/help/icomm/ug/modbusexplorer-app.html"
        TroubleShootingLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ProductShortName, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ModbusExplorerAppDocTopicID, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.TroubleshootingText, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.TroubleshootingURL ...
            )

        AppletClass (1, 1) string = "modbusapplet.ModbusApplet"
        PluginClass (1, 1) string = "matlab.hwmgr.plugins.IcommPlugin"

        %% ExampleData Constants
        CommunicatingWithClickPLCMODBUSExampleName (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:CommunicatingWithClickPLCMODBUSExampleName").getString

        CommunicatingWithClickPLCMODBUSExampleHeading (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:CommunicatingWithClickPLCMODBUSExampleHeading").getString

        CommunicatingWithClickPLCMODBUSExampleDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:CommunicatingWithClickPLCMODBUSExampleDescription").getString

        ExampleIcon (1, 1) string =  "examples"

        % Argument to pass into openExample
        CommunicatingWithClickPLCMODBUSArg = "icomm/CommunicatingWithClickPLCMODBUSExample"

        % Topic ID corresponding to Example docmentation.
        CommunicatingWithClickPLCMODBUSDocTopicID (1,1) string = "CommunicatingWithClickPLCMODBUSExample"

        CommunicatingWithClickPLCMODBUSLearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ProductShortName, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.CommunicatingWithClickPLCMODBUSDocTopicID, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.CommunicatingWithClickPLCMODBUSExampleName, ...
            "https://www.mathworks.com/help/icomm/ug/communicating-with-click-plc-modbus.html" ...
            )

        %% HelpDocData Constants
        ModbusHelpDocName (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:ModbusHelpDocName").getString

        ModbusHelpDocHeading (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:ModbusHelpDocHeading").getString

        ModbusHelpDocDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:ModbusHelpDocDescription").getString

        HelpDocIcon (1, 1) string =  "documentation"

        % Topic ID corresponding to Help docmentation.
        ModbusHelpDocTopicID (1,1) string = "MODBUS_HOME"

        ModbusHelpDocIdentifier (1, 1) string = "ModbusHelpDocData";

        ModbusHelpDocLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ProductShortName, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ModbusHelpDocTopicID, ...
            matlab.hwmgr.internal.data.plugins.ModbusExplorerDataPlugin.ModbusHelpDocName, ...
            "https://www.mathworks.com/help/icomm/modbus.html" ...
            )
        %% Hardware Keyword Constants
        HardwareKeyword (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:HardwareKeyword").getString

        HardwareDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:HardwareDescription").getString

        HardwareTooltip (1, 1) string = ...
            message("hwmanagerapp:clientappdata:modbusexplorer:HardwareTooltip").getString

        HardwareCategory (1, 1) matlab.hwmgr.internal.data.HardwareKeywordCategory = ...
            matlab.hwmgr.internal.data.HardwareKeywordCategory.InterfaceAndProtocol
    end

    methods
        function obj = ModbusExplorerDataPlugin()

            %% AddOn Data
            addOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.ProductCode, ...
                obj.ToolboxName ...
                );
            obj.addAddOnData(addOnData);

            %% HardwareKeywordData
            keywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData( ...
                obj.HardwareKeyword, ...
                obj.HardwareDescription, ...
                obj.HardwareTooltip, ...
                obj.HardwareCategory, ...
                "KeywordRelatedBaseCodes", obj.ProductCode ...
                );
            obj.addHardwareKeywordData(keywordData);

            %% AppletData
            appletData = matlab.hwmgr.internal.data.DataFactory.createAppletData( ...
                obj.AppName, ...
                obj.AppletClass, ...
                obj.PluginClass, ...
                obj.AppDescription, ...
                obj.AppIcon, ...
                obj.LearnMoreLink, ...
                obj.TroubleShootingLink, ...
                "ToolboxBaseCodes", obj.ProductCode ...
                );
            obj.addAppletData(appletData);

            %% ExampleData
            CommunicatingWithClickPLCMODBUSExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData( ...
                obj.CommunicatingWithClickPLCMODBUSExampleName, ...
                obj.CommunicatingWithClickPLCMODBUSExampleDescription,...
                obj.ExampleIcon, ...
                obj.CommunicatingWithClickPLCMODBUSLearnMoreLink, ...
                obj.CommunicatingWithClickPLCMODBUSArg, ...
                "DescriptionHeading", obj.CommunicatingWithClickPLCMODBUSExampleHeading, ...
                "ToolboxBaseCodes", obj.ProductCode ...
                );
            obj.addExampleData(CommunicatingWithClickPLCMODBUSExampleData);

            %% HelpDocData
            ModbusHelpDocData = matlab.hwmgr.internal.data.DataFactory.createHelpDocData( ...
                obj.ModbusHelpDocName, ...
                obj.ModbusHelpDocDescription,...
                obj.HelpDocIcon, ...
                obj.ModbusHelpDocLink, ...
                obj.ModbusHelpDocIdentifier,...
                "DescriptionHeading", obj.ModbusHelpDocHeading, ...
                "ToolboxBaseCodes", obj.ProductCode, ...
                "RelatedAddOnBaseCodes", obj.ProductCode ...
                );
            obj.addHelpDocData(ModbusHelpDocData);
        end
    end
end
