classdef RaspberryPiDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
    %RASPBERRYPIDATAPLUGIN data plugin class for Raspberry Pi apps

    % Copyright 2021-2024 The MathWorks, Inc.

    properties(Constant)
        MLBaseCode = "RASPPIIO"
        SLBaseCode = "RASPPI"
        SimulinkBaseCode = "SL"
    end

    methods
        function obj = RaspberryPiDataPlugin()

            troubleshootingLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                "raspberrypiio", "raspberrypi_resouce_monitor_app",...
                string(message("hwmanagerapp:clientappdata:raspberrypimonitor:TroubleshootTitle").getString), ...
                "https://www.mathworks.com/help/releases/R2022b/supportpkg/raspberrypi/ug/raspberrypiresourcemonitor-app.html");

            learnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                "raspberrypiio", "raspberrypi_resouce_monitor_app",...
                string(message("hwmanagerapp:clientappdata:raspberrypimonitor:AppName").getString), ...
                "https://www.mathworks.com/help/releases/R2022b/supportpkg/raspberrypi/ug/raspberrypiresourcemonitor-app.html");

            %% Applet Data
            appletIcon = "RaspberryPiResourceMonitorApp";
            officalAppName = string(message('hwmanagerapp:clientappdata:raspberrypimonitor:AppName').getString);
            descriptionOfApp = string(message('hwmanagerapp:clientappdata:raspberrypimonitor:Description').getString);
            raspiAppData = matlab.hwmgr.internal.data.DataFactory.createAppletData( ...
                officalAppName, "raspi.resourcemonitor.RaspiMonitoringApplet", ...
                "matlab.hwmgr.plugins.RaspiPlugin", descriptionOfApp, ...
                appletIcon, learnMoreLink, troubleshootingLink, ...
                "SupportPackageBaseCodes", obj.MLBaseCode);
            obj.addAppletData(raspiAppData);

            %% AddOn Data

            slToolboxAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.SimulinkBaseCode,...
                getString(message("hwmanagerapp:clientappdata:raspberrypimonitor:SLToolboxName")));
            obj.addAddOnData(slToolboxAddOnData);

            spkgName = string(message('hwmanagerapp:clientappdata:raspberrypimonitor:MLSpkgName').getString);
            raspiAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.MLBaseCode, spkgName);
            obj.addAddOnData(raspiAddOnData);

            spkgName = string(message('hwmanagerapp:clientappdata:raspberrypimonitor:SLSpkgName').getString);
            raspiAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.SLBaseCode, spkgName, ...
                obj.SimulinkBaseCode);
            obj.addAddOnData(raspiAddOnData);

            %% HardwareKeywordData
            hwName = string(message('hwmanagerapp:clientappdata:raspberrypimonitor:HWName').getString);
            tooltipInfo = string(message('hwmanagerapp:clientappdata:raspberrypimonitor:Tooltip').getString);
            keywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData( ...
                hwName, descriptionOfApp, tooltipInfo, "HardwareType","KeywordRelatedBaseCodes",[obj.MLBaseCode obj.SLBaseCode]);
            obj.addHardwareKeywordData(keywordData);

            %% HardwareSetupData
            hardwareSetupIconID = "settings_hardware";

            mlHwSetupLearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                "raspberrypiio", "raspberrypi_resouce_monitor_app",...
                string(message("hwmanagerapp:clientappdata:raspberrypimonitor:MLHardwareSetupTitle").getString), ...
                "https://www.mathworks.com/help/supportpkg/raspberrypiio/ug/install-support-for-raspberry-pi-hardware.html");

            mlHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
                getString(message("hwmanagerapp:clientappdata:raspberrypimonitor:MLHardwareSetupTitle")),...
                getString(message("hwmanagerapp:clientappdata:raspberrypimonitor:HardwareSetupDescription")),...
                hardwareSetupIconID,...
                mlHwSetupLearnMoreLink,...
                "matlab.hwmgr.internal.hwsetup.register.RaspberryPiWorkflow",...
                'SupportPackageBaseCodes', obj.MLBaseCode);
            obj.addHardwareSetupData(mlHardwareSetupData);

            slHwSetupLearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                "raspberrypi", "raspberrypi_resouce_monitor_app",...
                string(message("hwmanagerapp:clientappdata:raspberrypimonitor:SLHardwareSetupTitle").getString), ...
                "https://www.mathworks.com/help/supportpkg/raspberrypi/setup-and-configuration.html");

            slHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
                getString(message("hwmanagerapp:clientappdata:raspberrypimonitor:SLHardwareSetupTitle")),...
                getString(message("hwmanagerapp:clientappdata:raspberrypimonitor:HardwareSetupDescription")),...
                hardwareSetupIconID,...
                slHwSetupLearnMoreLink,...
                "matlab.hwmgr.internal.hwsetup.register.RaspberryPiWorkflow",...
                "ToolboxBaseCodes", obj.SimulinkBaseCode, ...
                'SupportPackageBaseCodes', obj.SLBaseCode);
            obj.addHardwareSetupData(slHardwareSetupData);

        end
    end
end
