classdef SDRDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
    %SDRDATAPLUGIN Data plugin class for SDR Hardware Manager integration.

    % Copyright 2024 The MathWorks, Inc.

    % Properties referenced statically by SDRDataPlugin
    properties(Constant,Hidden)
        RadioHardwareSetupDataIconID = "settings_hardware"
        RadioExampleDataIconID = "examples"
        RadioDocDataIconID = "help"

        %% Communications Toolbox Add-On properties
        CommunicationsToolboxBaseCode = "CM"

        %% ADALM-Pluto Radio properties
        PlutoRadioSupportPackageBaseCode = "PLUTO"
        PlutoRadioManufacturer = "Analog Devices"

        % Help link will be added using
        PlutoRadioHardwareSetupDataLearnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "sdrpluto_spsetup",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RadioHardwareSetupDataDisplayName")),...
            "https://www.mathworks.com/help/comm/plutoradio/ug/guided-host-radio-hardware-setup.html");

        PlutoRadioDocPageLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "sdrpluto_doccenter",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:PlutoRadioDocDataName")),...
            "https://www.mathworks.com/help/comm/plutoradio.html");

        FMBroadcastReceiverExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "FMBroadcastReceiverExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMBroadcastReceiverExampleDataName")),...
            "https://www.mathworks.com/help/comm/plutoradio/ug/fm-broadcast-receiver.html");

        CaptureRFDataExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "CaptureRFDataToBasebandFileUsingADALMPLUTORadioExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:CaptureRFDataExampleDataName")),...
            "https://www.mathworks.com/help/comm/plutoradio/ref/comm.sdrrxpluto-system-object.html#bvn859s-1_ex4");
        %% RTL-SDR Radio properties
        RTLRadioSupportPackageBaseCode = "RTLSDR"
        RTLRadioManufacturer = "Nooelec"

        RTLRadioDocPageLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "rtlsdr_doccenter",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RTLRadioDocDataName")),...
            "https://www.mathworks.com/help/comm/rtlsdrradio.html");

        FMReceptionWithRTLSDRRadioExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "FMReceptionWithRTLSDRRadioOnRaspberryPiHardwareSimulinkExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMReceptionWithRTLSDRRadioExampleDataName")),...
            "https://www.mathworks.com/help/comm/rtlsdrradio/ug/fm-reception-with-rtl-sdr-radio-on-raspberry-pi-hardware.html");

        %% USRP SPKG Radio properties
        USRPSPKGRadioSupportPackageBaseCode = "USRP"
        USRP200RadioManufacturer = "NI"

        USRP200RadioDocPageLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "sdru",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:USRP200RadioDocDataName")),...
            "https://www.mathworks.com/help/comm/usrpradio.html");

        FMDemodulationExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "FMSpectrumAnalysisAndDemodulationWithUSRPRadioExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMDemodulationExampleDataName")),...
            "https://www.mathworks.com/help/comm/usrpradio/ug/fm-demodulation-spectrum-analysis-with-usrp-radio.html");

        MultipleChannelIOExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "comm", ...
            "TransmissionOverMultipleChannelsWithSDRuSystemObjectExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:MultipleChannelIOExampleName")),...
            "https://www.mathworks.com/help/comm/usrpradio/ug/multiple-channel-input-and-output.html#mw_5a67f5e4-03c9-4077-b301-cb17ffc06c60");

        %% WT Radio HardwareSetup properties
        WTToolboxBaseCode = "WB"
        WTRadioSupportPackageBaseCode = "NI_USRP"
        WTRadioManufacturer = "NI"

        USRPWTRadioDocPageLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "wt", ...
            "WTLandingPage",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:WTToolboxAddOnDataFullName")),...
            "https://www.mathworks.com/help/wireless-testbench/index.html");

        LoopbackTransmitAndCaptureExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "wt", ...
            "LoopbackTransmitAndCaptureExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:LoopbackTransmitAndCaptureExampleDataName")),...
            "https://www.mathworks.com/help/wireless-testbench/gs/loopback-transmit-and-capture.html");

        TriggeredCaptureUsingEnergyDetectionExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "wt", ...
            "TriggeredCaptureUsingEnergyDetectionExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:TriggeredCaptureUsingEnergyDetectionExampleDataName")),...
            "https://www.mathworks.com/help/wireless-testbench/gs/triggered-capture-using-energy-detection.html");

        NIUSRPTargetingWorkflowExampleLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData(...
            "wt", ...
            "GettingStartedWithNIUSRPTargetingWorkflowExample",...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:NIUSRPTargetingWorkflowExampleDataName")),...
            "https://www.mathworks.com/help/wireless-testbench/ug/getting-started-with-ni-usrp-targeting-workflow.html");

        %% SDR HardwareKeywordData properties
        % Create a key/value pairs of manufacturer and support package basecode
        RadioKeys = ...
            ["ADALM-Pluto", ...
            "RTL-SDR", ...
            "USRP B200/B210", ...
            "USRP N200/N210/USRP2", ...
            "USRP E320", ...
            "USRP N300/N310/N320/N321", ...
            "USRP X300/X310", ...
            "USRP X410"];

        RadioValues = {...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioSupportPackageBaseCode, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioSupportPackageBaseCode, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode ...
            };

        ManufacturersMap = containers.Map(...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioKeys, ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioValues);
    end

    properties(Constant, Access = private)

        %% SDR DataPlugin properties
        SDRHardwareKeywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData( ...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:HardwareKeywordDataKeyword")), ...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:HardwareKeywordDataDescription")), ...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:HardwareKeywordDataTooltip")), ...
            "HardwareType", ...
            "ManufacturerPlaceholder", "Select your SDR (ADALM-Pluto, RTL-SDR, USRP)", ...
            "Manufacturers", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.ManufacturersMap);

        %% Communications Toolbox Add-On properties
        CommunicationToolboxAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode,...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:CommunicationsToolboxAddOnDataFullName")));

        %% Wireless Testbench Add-On properties
        WTToolboxAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTToolboxBaseCode,...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:WTToolboxAddOnDataFullName")));

        %% ADALM-Pluto Radio
        % HardwareSetup properties
        PlutoRadioHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RadioHardwareSetupDataDisplayName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:PlutoRadioHardwareSetupDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioHardwareSetupDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioHardwareSetupDataLearnMoreLink,...
            "matlab.hwmgr.internal.hwsetup.register.PlutoRadioWorkFlow",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioSupportPackageBaseCode);

        % FMBroadcastReceiverExample properties
        FMBroadcastReceiverExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMBroadcastReceiverExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMBroadcastReceiverExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.FMBroadcastReceiverExampleLink,...
            "comm/FMBroadcastReceiverExample", ...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioSupportPackageBaseCode);

        % CaptureRFDataExample properties
        CaptureRFDataExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:CaptureRFDataExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:CaptureRFDataExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CaptureRFDataExampleLink,...
            "plutoradio/CaptureRFDataToBasebandFileUsingADALMPLUTORadioExample", ...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioSupportPackageBaseCode);

        % PlutoHelpDocData properties
        PlutoHelpDocData = matlab.hwmgr.internal.data.DataFactory.createHelpDocData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:PlutoRadioDocDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:PlutoRadioDocDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioDocDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioDocPageLink,...
            "PlutoHelpDocData",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode,...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioSupportPackageBaseCode, ...
            "RelatedAddOnBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioSupportPackageBaseCode);

        % Add-On properties
        PlutoRadioAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.PlutoRadioSupportPackageBaseCode,...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:PlutoRadioAddOnDataFullName")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode);

        %% RTL-SDR Radio
        % HardwareSetup properties
        RTLRadioHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RadioHardwareSetupDataDisplayName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RTLRadioHardwareSetupDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioHardwareSetupDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioDocPageLink,...
            "matlab.hwmgr.internal.hwsetup.register.RTLSDRRadioWorkFlow",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioSupportPackageBaseCode);

        % RTLFMBroadcastReceiverExample properties
        RTLFMBroadcastReceiverExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMBroadcastReceiverExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMBroadcastReceiverExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.FMBroadcastReceiverExampleLink,...
            "comm/FMBroadcastReceiverExample",[],"RTLFMBroadcastReceiverExampleData",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioSupportPackageBaseCode);

        % FMReceptionWithRTLSDRRadio properties
        FMReceptionWithRTLSDRRadioExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMReceptionWithRTLSDRRadioExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMReceptionWithRTLSDRRadioExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.FMReceptionWithRTLSDRRadioExampleLink,...
            "comm/FMReceptionWithRTLSDRRadioOnRaspberryPiHardwareSimulinkExample",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioSupportPackageBaseCode);

        % RTLRadioHelpDocData properties
        RTLRadioHelpDocData = matlab.hwmgr.internal.data.DataFactory.createHelpDocData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RTLRadioDocDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RTLRadioDocDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioDocDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioDocPageLink,...
            "RTLRadioHelpDocData",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioSupportPackageBaseCode, ...
            'RelatedAddOnBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioSupportPackageBaseCode);

        % Add-On properties
        RTLRadioAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RTLRadioSupportPackageBaseCode,...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RTLRadioAddOnDataFullName")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode);

        %% USRP 200 Series Radio

        % HardwareSetup properties
        USRPSPKGRadioHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RadioHardwareSetupDataDisplayName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:USRPSPKGRadioHardwareSetupDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioHardwareSetupDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRP200RadioDocPageLink,...
            "matlab.hwmgr.internal.hwsetup.register.USRPRadioWorkflow",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode);

        % FMDemodulationExample properties
        FMDemodulationExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMDemodulationExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:FMDemodulationExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.FMDemodulationExampleLink,...
            "usrpradio/FMSpectrumAnalysisAndDemodulationWithUSRPRadioExample", ...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode);

        % MultipleChannelIOExample properties
        MultipleChannelIOExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:MultipleChannelIOExampleName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:MultipleChannelIOExampleDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.MultipleChannelIOExampleLink,...
            "usrpradio/TransmissionOverMultipleChannelsWithSDRuSystemObjectExample", ...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode);

        % USRPSPKGRadioHelpDocData properties
        USRPSPKGRadioHelpDocData = matlab.hwmgr.internal.data.DataFactory.createHelpDocData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:USRP200RadioDocDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:USRP200RadioDocDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioDocDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRP200RadioDocPageLink,...
            "USRPSPKGRadioHelpDocData",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode,...
            'RelatedAddOnBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode);

        % Add-On properties
        USRPSPKGRadioAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPSPKGRadioSupportPackageBaseCode,...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:USRPRadioAddOnDataFullName")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.CommunicationsToolboxBaseCode);

        %% USRP 300/400 Series Radio

        %%% NI USRP SPKG
        % HardwareSetup properties
        WTSeriesRadioHardwareSetupData = matlab.hwmgr.internal.data.DataFactory.createHardwareSetupData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:RadioHardwareSetupDataDisplayName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:WTRadiosSPKGHardwareSetupDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioHardwareSetupDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.USRPWTRadioDocPageLink,...
            "matlab.hwmgr.internal.hwsetup.register.WTWorkflow",...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode);

        % LoopbackTransmitAndCaptureExample properties
        LoopbackTransmitAndCaptureExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:LoopbackTransmitAndCaptureExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:LoopbackTransmitAndCaptureExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.LoopbackTransmitAndCaptureExampleLink,...
            "wt/LoopbackTransmitAndCaptureExample", ...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode);

        % TriggeredCaptureUsingEnergyDetectionExample properties
        TriggeredCaptureUsingEnergyDetectionExampleDataName = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:TriggeredCaptureUsingEnergyDetectionExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:TriggeredCaptureUsingEnergyDetectionExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.TriggeredCaptureUsingEnergyDetectionExampleLink,...
            "wt/TriggeredCaptureUsingEnergyDetectionExample", ...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode);

        % NIUSRPTargetingWorkflowExample properties
        NIUSRPTargetingWorkflowExampleData = matlab.hwmgr.internal.data.DataFactory.createExampleData(...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:NIUSRPTargetingWorkflowExampleDataName")),...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:NIUSRPTargetingWorkflowExampleDataDescription")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.RadioExampleDataIconID,...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.NIUSRPTargetingWorkflowExampleLink,...
            "wt/GettingStartedWithNIUSRPTargetingWorkflowExample", ...
            "ToolboxBaseCodes", matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTToolboxBaseCode, ...
            'SupportPackageBaseCodes', matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode);

        % Add-On properties
        WTRadioAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTRadioSupportPackageBaseCode,...
            getString(message("hwmanagerapp:plugins:sdrdataplugin:WTRadiosSPKGAddOnDataFullName")),...
            matlab.hwmgr.internal.data.plugins.SDRDataPlugin.WTToolboxBaseCode);
    end

    methods
        function obj = SDRDataPlugin()
            % Communications Toolbox Add-On
            obj.addAddOnData(obj.CommunicationToolboxAddOnData);

            % WT Toolbox Add-On
            obj.addAddOnData(obj.WTToolboxAddOnData);
            %% ADALM-Pluto

            % Radio Add-On
            obj.addAddOnData(obj.PlutoRadioAddOnData);

            % Radio Launchables Data
            obj.addHardwareSetupData(obj.PlutoRadioHardwareSetupData);
            obj.addExampleData(obj.FMBroadcastReceiverExampleData);
            obj.addExampleData(obj.CaptureRFDataExampleData);
            obj.addHelpDocData(obj.PlutoHelpDocData);

            %% RTL-SDR

            % Radio Add-On
            obj.addAddOnData(obj.RTLRadioAddOnData);

            % Radio Launchables Data
            obj.addHardwareSetupData(obj.RTLRadioHardwareSetupData);
            obj.addExampleData(obj.RTLFMBroadcastReceiverExampleData);
            % TODO g3443293
            % This example requires multiple SPKG so this will be removed
            % until g3127145 is implemented; The ExampleData will need to
            % be updated with the other supportpackages as well
            % obj.addExampleData(obj.FMReceptionWithRTLSDRRadioExampleData);
            obj.addHelpDocData(obj.RTLRadioHelpDocData);

            %% USRP SPKG Radios

            % Radio Add-On
            obj.addAddOnData(obj.USRPSPKGRadioAddOnData);

            % Radio Launchables Data
            obj.addHardwareSetupData(obj.USRPSPKGRadioHardwareSetupData);
            obj.addExampleData(obj.FMDemodulationExampleData);
            obj.addExampleData(obj.MultipleChannelIOExampleData);
            obj.addHelpDocData(obj.USRPSPKGRadioHelpDocData);

            %% USRP WT Radios

            % Radio Add-On
            obj.addAddOnData(obj.WTRadioAddOnData);

            % Radio Launchables Data
            obj.addHardwareSetupData(obj.WTSeriesRadioHardwareSetupData);
            obj.addExampleData(obj.LoopbackTransmitAndCaptureExampleData);
            obj.addExampleData(obj.TriggeredCaptureUsingEnergyDetectionExampleDataName);

            % TODO g3443293
            % This example requires multiple SPKG so this will be removed
            % until g3127145 is implemented; The ExampleData will need to
            % be updated with the other supportpackages as well
            % The example below regarding generating a bitstream is
            % supported only on a Linux Operating System
            % if ~ismac && isunix
            %     obj.addExampleData(obj.NIUSRPTargetingWorkflowExampleData);
            % end
            %% SDR DataPlugin Hardware Keyword Data
            obj.addHardwareKeywordData(obj.SDRHardwareKeywordData);
        end
    end
end

