classdef SerialExplorerDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
    %SERIALEXPLORERDATAPLUGIN is the data plugin class for the Serial
    % Explorer app

    % Copyright 2021-2023 The MathWorks, Inc.

    properties (Constant)
        %% AppletData Constants
        AppName (1, 1) string = ...
            message("hwmanagerapp:clientappdata:serialexplorer:AppName").getString

        AppDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:serialexplorer:ToolTipText").getString

        AppIcon (1, 1) string = ...
            "SerialExplorerApp"

        % Learn More Link
        LearnMoreText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:serialexplorer:AppName").getString

        % Troubleshooting Link
        TroubleshootingText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:serialexplorer:TroubleshootHeading").getString

        % ProductShortName and Doc Topic Ids
        ProductShortName (1, 1) string = "matlab"
        DocTopicId (1, 1) string = "serialExplorer"
        TroubleshootTopicId (1, 1) string = "serialTroubleshooting"

        AppletClass (1, 1) string = "transportapp.serialport.internal.SerialportApp"
        PluginClass (1, 1) string = "matlab.hwmgr.plugins.SerialportPlugin"

        %% Hardware Keyword Constants
        HardwareKeyword (1, 1) string = ...
            message("hwmanagerapp:clientappdata:serialexplorer:Keyword").getString

        HardwareDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:serialexplorer:KeywordDescription").getString

        HardwareTooltip (1, 1) string = ...
            message("hwmanagerapp:clientappdata:serialexplorer:ToolTipText").getString

        HardwareCategory (1, 1) matlab.hwmgr.internal.data.HardwareKeywordCategory = ...
            matlab.hwmgr.internal.data.HardwareKeywordCategory.InterfaceAndProtocol
    end

    methods
        function obj = SerialExplorerDataPlugin()
            %% Link Data
            learnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                obj.ProductShortName, obj.DocTopicId, ...
                obj.LearnMoreText);

            troubleshootingLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                obj.ProductShortName, obj.TroubleshootTopicId, ...
                obj.TroubleshootingText);
 
            %% Applet Data
            serialExplorerAppData = matlab.hwmgr.internal.data.DataFactory.createAppletData( ...
                obj.AppName, ...
                obj.AppletClass, ...
                obj.PluginClass, ...
                obj.AppDescription, ...
                obj.AppIcon, ...
                learnMoreLink, ...
                troubleshootingLink);
            obj.addAppletData(serialExplorerAppData);

            %% HardwareKeywordData
            keywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData( ...
                obj.HardwareKeyword, ...
                obj.HardwareDescription, ...
                obj.HardwareTooltip, ...
                obj.HardwareCategory, ...
                "AppletClasses",obj.AppletClass);
            obj.addHardwareKeywordData(keywordData);
        end
    end
end