classdef TCPIPExplorerDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
    %TCPIPEXPLORERDATAPLUGIN is the data plugin class for the TCP/IP
    % Explorer app

    % Copyright 2021-2023 The MathWorks, Inc.

    properties (Constant)
        %% AppletData Constants
        AppName (1, 1) string = ...
            message("hwmanagerapp:clientappdata:tcpipexplorer:AppName").getString

        AppDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:tcpipexplorer:ToolTipText").getString

        AppIcon (1, 1) string = ...
            "tcpIpExplorerApp"

        % Learn More Link
        LearnMoreText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:tcpipexplorer:AppName").getString

        % Troubleshooting Link
        TroubleshootingText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:tcpipexplorer:TroubleshootHeading").getString

        % ProductShortName and Doc Topic Ids
        ProductShortName (1, 1) string = "matlab"
        DocTopicId (1, 1) string = "tcpipExplorer"
        TroubleshootTopicId (1, 1) string = "tcpipTroubleshooting"

        AppletClass (1, 1) string = "transportapp.tcpclient.internal.TcpclientApp"
        PluginClass (1, 1) string = "matlab.hwmgr.plugins.TcpclientPlugin"

        %% Hardware Keyword Constants
        HardwareKeyword (1, 1) string = ...
            message("hwmanagerapp:clientappdata:tcpipexplorer:Keyword").getString

        HardwareDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:tcpipexplorer:KeywordDescription").getString

        HardwareTooltip (1, 1) string = ...
            message("hwmanagerapp:clientappdata:tcpipexplorer:ToolTipText").getString

        HardwareCategory (1, 1) matlab.hwmgr.internal.data.HardwareKeywordCategory = ...
            matlab.hwmgr.internal.data.HardwareKeywordCategory.InterfaceAndProtocol
    end

    methods
        function obj = TCPIPExplorerDataPlugin()
            %% Link Data
            learnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                obj.ProductShortName, obj.DocTopicId, ...
                obj.LearnMoreText);

            troubleshootingLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                obj.ProductShortName, obj.TroubleshootTopicId, ...
                obj.TroubleshootingText);

            %% Applet Data
            tcpipExplorerAppData = matlab.hwmgr.internal.data.DataFactory.createAppletData( ...
                obj.AppName, ...
                obj.AppletClass, ...
                obj.PluginClass, ...
                obj.AppDescription, ...
                obj.AppIcon, ...
                learnMoreLink, ...
                troubleshootingLink);
            obj.addAppletData(tcpipExplorerAppData);

            %% HardwareKeywordData
            keywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData( ...
                obj.HardwareKeyword, ...
                obj.HardwareDescription, ...
                obj.HardwareTooltip, ...
                obj.HardwareCategory, ...
                "AppletClasses",obj.AppletClass);
            obj.addHardwareKeywordData(keywordData);
        end
    end
end
