classdef UDPExplorerDataPlugin < matlab.hwmgr.internal.data.plugins.PluginBase
    %UDPEXPLORERDATAPLUGIN is the data plugin class for the UDP Explorer app

    % Copyright 2021-2023 The MathWorks, Inc.
 
    properties (Constant)
        %% Add-On Constants
        ProductCode (1, 1) string = "IC"
        ToolboxName (1, 1) string = message("hwmanagerapp:clientappdata:udpexplorer:ToolboxName").getString

        %% AppletData Constants
        AppName (1, 1) string = ...
            message("hwmanagerapp:clientappdata:udpexplorer:AppName").getString

        AppDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:udpexplorer:ToolTipText").getString

        AppIcon (1, 1) string = ...
            "UDPExplorerApp"

        % Learn More Link
        LearnMoreText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:udpexplorer:AppName").getString

        % Troubleshooting Link
        TroubleshootingText (1, 1) string = ...
            message("hwmanagerapp:clientappdata:udpexplorer:TroubleshootHeading").getString

        % ProductShortName and Doc Topic Ids
        ProductShortName (1, 1) string = "instrument"
        DocTopicId (1, 1) string = "udpExplorer"
        TroubleshootTopicId (1, 1) string = "udpTroubleshooting"

        AppletClass (1, 1) string = "transportapp.udpport.internal.UdpportApp"
        PluginClass (1, 1) string = "matlab.hwmgr.plugins.UdpportPlugin"

        %% Hardware Keyword Constants
        HardwareKeyword (1, 1) string = ...
            message("hwmanagerapp:clientappdata:udpexplorer:Keyword").getString

        HardwareDescription (1, 1) string = ...
            message("hwmanagerapp:clientappdata:udpexplorer:KeywordDescription").getString

        HardwareTooltip (1, 1) string = ...
            message("hwmanagerapp:clientappdata:udpexplorer:ToolTipText").getString

        HardwareCategory (1, 1) matlab.hwmgr.internal.data.HardwareKeywordCategory = ...
            matlab.hwmgr.internal.data.HardwareKeywordCategory.InterfaceAndProtocol
    end

    methods
        function obj = UDPExplorerDataPlugin()
            %% Link Data
            learnMoreLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                obj.ProductShortName, obj.DocTopicId, ...
                obj.LearnMoreText);

            troubleshootingLink = matlab.hwmgr.internal.data.DataFactory.createDocLinkData( ...
                obj.ProductShortName, obj.TroubleshootTopicId, ...
                obj.TroubleshootingText);
 
            %% Applet Data
            udpExplorerAppData = matlab.hwmgr.internal.data.DataFactory.createAppletData( ...
                obj.AppName, ...
                obj.AppletClass, ...
                obj.PluginClass, ...
                obj.AppDescription, ...
                obj.AppIcon, ...
                learnMoreLink, ...
                troubleshootingLink, ...
                "ToolboxBaseCodes", obj.ProductCode);
            obj.addAppletData(udpExplorerAppData);
 
            %% AddOn Data
            ictAddOnData = matlab.hwmgr.internal.data.DataFactory.createAddOnData( ...
                obj.ProductCode, ...
                obj.ToolboxName);
            obj.addAddOnData(ictAddOnData);

            %% HardwareKeywordData
            keywordData = matlab.hwmgr.internal.data.DataFactory.createHardwareKeywordData( ...
                obj.HardwareKeyword, ...
                obj.HardwareDescription, ...
                obj.HardwareTooltip, ...
                obj.HardwareCategory, ...
                "KeywordRelatedBaseCodes", obj.ProductCode);
            obj.addHardwareKeywordData(keywordData);
        end
    end
end
