function fcnDictionary = groupsummaryMethodName2FilterFcn()
% Returns a dictionary that maps method names to function handles. These
% functions determine whether that method is valid for a given data variable.
% For Pivot Table, this function also determines the full method list as
% well as the dropdown order.
%
% For use in ComputeByGroupTask and PivotTableTask
%
% FOR INTERNAL USE ONLY -- This feature is intentionally undocumented.
% Its behavior may change, or it may be removed in a future release.

%   Copyright 2023-2024 The MathWorks, Inc.

fcnDictionary = dictionary(...
    'sum',   @(x) isnumeric(x) || islogical(x) || ischar(x) || isduration(x),...
    'none',  @(x) ~(isnumeric(x) || islogical(x) || ischar(x) || isduration(x)),... % only offer when 'sum' isn't available
    'mean',  @(x) isnumeric(x) || islogical(x) || isdatetime(x) || isduration(x) || ischar(x),...
    'median',@(x) isnumeric(x) || islogical(x) || ischar(x) || isdatetime(x) || isduration(x) || (iscategorical(x) && isordinal(x)),...
    'mode',  @(x) isnumeric(x) || islogical(x) || ischar(x) || iscategorical(x) || isdatetime(x) || isduration(x),...
    'max',   @(x) isnumeric(x) || islogical(x) || ischar(x) || isdatetime(x) || isduration(x) || (iscategorical(x) && isordinal(x)),...
    'min',   @(x) isnumeric(x) || islogical(x) || ischar(x) || isdatetime(x) || isduration(x) || (iscategorical(x) && isordinal(x)),...
    'range', @(x) isnumeric(x) || islogical(x) || ischar(x) || isdatetime(x) || isduration(x),...
    'std',   @(x) isfloat(x) || islogical(x) || ischar(x) || isdatetime(x) || isduration(x),...
    'var',   @(x) isfloat(x) || islogical(x) || ischar(x),...
    'nnz',   @(x) isnumeric(x) || islogical(x) || ischar(x) || isduration(x) || iscalendarduration(x),...
    'nummissing',@(x) true,... %ismissing flows through for types w/o missing
    'numunique',@(x) (iscolumn(x) || isempty(x)) && (~isinteger(x) || isreal(x)) && (~iscell(x) || iscellstr(x)),...
    'CustomFunction',@(x) true); %#ok<ISCLSTR>