% WEBCONTAINERCONTROLLER Base class for all MATLAB Component Framework (MCF)
% web-based container controllers. Introduced to capture commonalities across
% all container controllers in terms of the use of MCF services, such as the
% Property Management Service (PMS) and the Event Handling Service (EHS).

%   Copyright 2014-2023 The MathWorks, Inc.
classdef WebContainerController < ...
        matlab.ui.internal.componentframework.WebComponentController & ...
        matlab.ui.internal.componentframework.services.core.identification.IdentificationService

    methods ( Access = 'public' )

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:       Constructor
        %
        %  Inputs:       model -> Model MCOS object for the web component.
        %                varargin{1} -> Parent controller.
        %                varargin{2) -> View.
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function obj = WebContainerController( model, varargin )
            % MATLAB Component Framework's (MCF) web-based container controller
            % constructor.
            obj = obj@matlab.ui.internal.componentframework.WebComponentController( model, varargin{:} );
        end
    end

    methods(Hidden, Access = 'public')
        % Determines the order that children are stored
        %
        % If true...
        %
        %   Then Children property is stored as [child 3, child 2, child 1]
        %
        %   where child 1 was added first, child 2 second, and child 3 last
        %
        %   Applies to majority of HG containers
        %
        % If false...
        %
        %   Then Children property is stored as [child 1, child 2, child 3]
        %
        %   where child 1 was added first, child 2 second, and child 3 last
        %
        %  Applies to order-based components like TabGroup and Menus

        % This needs to be a method instead of a property because child peerNode
        % processing starts even before the parent controller finishes intialization.
        % This is done in processProxyView() in DesignTimeParentingController
        % This is because childAdded events on ViewModel are never triggered
        % because JavaScript being single threaded - the event handlers
        % block access to the ViewModel
        function isChildOrderReversed = isChildOrderReversed(obj)
           isChildOrderReversed = true; 
        end

    end

    methods( Access = 'protected' )

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      defineViewProperties
        %
        %  Inputs:      None.
        %  Outputs:     None.
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function defineViewProperties( obj )
            % By leveraging MCF's Property Management Service (PMS), properties
            % pertaining to the view can be customized per web component and the
            % corresponding web controller.
            % This method defines view properties common to all containers.
        end

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      findModelFromChildId
        %
        %  Inputs:      id -> Unique identifier generated by MCF's Identification
        %                     Service.
        %  Outputs:     mcosHandle -> MCOS handle of the child found based on the
        %                             unique identifier.
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function mcosHandle = findModelFromChildId( obj, id )
            % Finds and returns the MCOS handle based on child's unique identifier
            % generated by MCF's Identification Service.
            mcosHandle = [];
            % Don't use obj.Model.Children in case HandleVisibility is off - g1504402
            children = allchild(obj.Model);
            for idx=1:numel( children )
                if strcmp( children(idx).getId(), id )
                    mcosHandle = children(idx);
                    break;
                end
            end
        end

    end

end
