classdef StructFieldsList
    %STRUCTFIELDSLIST Summary of this class goes here
    %   Detailed explanation goes here
    
    properties (Constant, Hidden)
        DefaultVisibleCols = ["Name", "Value", "Size", "Class"];
        SettingToContextMap = struct(...
            "MOTW_Workspace", true, ...
            "MOTW", true ...
        );
        FieldColumnsMap = struct(...
            "Class", "internal.matlab.variableeditor.FieldColumns.ClassCol",...
            "Max", "internal.matlab.variableeditor.FieldColumns.MaxCol",...
            "Mean", "internal.matlab.variableeditor.FieldColumns.MeanCol",...
            "Median", "internal.matlab.variableeditor.FieldColumns.MedianCol",...
            "Min", "internal.matlab.variableeditor.FieldColumns.MinCol",...
            "Mode", "internal.matlab.variableeditor.FieldColumns.ModeCol",...
            "Name", "internal.matlab.variableeditor.FieldColumns.NameCol",...
            "Range", "internal.matlab.variableeditor.FieldColumns.RangeCol",...
            "Size", "internal.matlab.variableeditor.FieldColumns.SizeCol",...
            "Std", "internal.matlab.variableeditor.FieldColumns.StdCol",...
            "Value", "internal.matlab.variableeditor.FieldColumns.ValueCol",...
            "Var", "internal.matlab.variableeditor.FieldColumns.VarCol",...
            "Visible", "internal.matlab.variableeditor.FieldColumns.VisibilityCol"...
        );
    end
end

