function tf = isSupportedDatatype(data)
%

% Copyright 2020 The MathWorks, Inc.

    tf = isstring(data) ...
        || isnumeric(data) ...
        || class(data) == "missing" ...
        || islogical(data) ...
        || ischar(data) ...
        || iscellstr(data) ...
        || isdatetime(data) ...
        || isduration(data) ...
        || iscalendarduration(data) ...
        || iscategorical(data);
end
