function validateXMLNameFirstCharacter(nameValue, elementName)
% The XML 1.0 Specification, Fifth Edition, limits the characters that can
% be used as the first character in an element or attribute name:
% https://www.w3.org/TR/xml/#NT-NameStartChar

% Copyright 2020 The MathWorks, Inc.

import matlab.io.xml.internal.write.inHexRange

% convert the name to char type
nameValue = char(nameValue);

firstNameChar = nameValue(1);

% 
if ~(startsWith(firstNameChar, "_") ...
    || startsWith(firstNameChar, ":") ...
    || isletter(firstNameChar) ...
    || inHexRange(firstNameChar, 0xC0, 0xD6) ...
    || inHexRange(firstNameChar, 0xD8, 0xF6) ...
    || inHexRange(firstNameChar, 0xF8, 0x2FF) ...
    || inHexRange(firstNameChar, 0x370, 0x37D) ...
    || inHexRange(firstNameChar, 0x37F, 0x1FFF) ...
    || inHexRange(firstNameChar, 0x200C, 0x200D) ...
    || inHexRange(firstNameChar, 0x2070, 0x218F) ...
    || inHexRange(firstNameChar, 0x2C00, 0x2FEF) ...
    || inHexRange(firstNameChar, 0x3001, 0xD7FF) ...
    || inHexRange(firstNameChar, 0xF900, 0xFDCF) ...
    || inHexRange(firstNameChar, 0xFDF0, 0xFFFD) ...
    || inHexRange(firstNameChar, 0x10000, 0xEFFFF))
    
    error(message("MATLAB:io:xml:common:InvalidFirstCharElementName", ...
        firstNameChar, elementName));
end

end