function clear(this)
%CLEAR  Clears data.

%  Author(s): P. Gahinet
%  Copyright 1986-2004 The MathWorks, Inc.

set(this, 'Stable', [], ...
	  'GainMargin' , [], ...
	  'PhaseMargin' , [], ...
	  'GMFrequency' , [], ...
	  'PMFrequency' , [], ...
	  'DelayMargin' , [], ...
	  'DMFrequency' , []);
