%mlreportgen.ppt.setDefaultNumberFormat Set default formatting of numeric
%data generated by PPT API
%
%    mlreportgen.ppt.setDefaultNumberFormat(formatSpec) sets the default
%    number format specification for the PPT API presentations. The
%    formatSpec can be specified as a character vector or a string scalar
%    and must be a valid format specification for the sprintf function. The
%    default specification applies for the duration of the MATLAB session
%    and applies to numbers in all the presentation elements, such as
%    paragraphs, tables, etc., and to the numbers represented by the
%    mlreportgen.ppt.Number objects. You can override the default
%    specification for one number or all numbers in the presentation
%    elements by using an mlreportgen.ppt.NumberFormat object.
%
%    Input Argument:
%        formatSpec - Format specification, specified as a character vector
%        or string scalar. The specification must be a valid format
%        specification for the sprintf function and use one of these
%        operators: %f, %e, %E, %g, %G.
%
%    Example:
%
%       % Set the default number format specification for the PPT API presentations
%       mlreportgen.ppt.setDefaultNumberFormat("%0.2f");
%
%       % Create a presentation
%       import mlreportgen.ppt.*
%       ppt = Presentation("myNumberPresentation.pptx");
%       open(ppt);
%
%       % Add two slides to the presentation
%       slide1 = add(ppt,"Title and Content");
%       slide2 = add(ppt,"Title and Table");
%
%       % Add title for the first slide
%       replace(slide1,"Title","Formatted numeric content");
%
%       % Create a paragraph with numeric content and add it to the first slide.
%       % Note: The number format specification is set by the package function.
%       para = Paragraph("The value of pi is: ");
%       append(para,Number(pi));
%       replace(slide1,"Content",para);
%
%       % Add title for the second slide
%       replace(slide2,"Title","Table with formatted numeric content");
%
%       % Create a table with numeric content and add it to the second slide.
%       % Note: The number format specification is set by the package function.
%       replace(slide2,"Table",Table({pi, pi; pi, pi}));
%
%       % Close and view the presentation
%       close(ppt);
%       rptview(ppt);
%
%    See also mlreportgen.ppt.getDefaultNumberFormat, sprintf,
%    mlreportgen.ppt.Number, mlreportgen.ppt.NumberFormat

%    Copyright 2024 The MathWorks, Inc.
%    Built-in function