function initialize(this,Axes)
%INITIALIZE  Initialization for @ConfidenceRegionResidCorrView class

%  Copyright 2015 The MathWorks, Inc.

[s1,s2] = size(Axes(:,:,1));
UncertainPatch = zeros([s1 s2]);
for ct = 1:s1*s2
   UncertainPatch(ct) = patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
end

this.UncertainPatch = handle(UncertainPatch);

UncertainLines = zeros([s1 s2]);
for ct=1:s1*s2
   UncertainLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'Color',[0.9804 .9*0.9804 0.8235]);
end
this.UncertainLines = handle(UncertainLines);
