function initialize(this,Axes)
%INITIALIZE  Initialization for @MinDiskMarginView class

%  Author(s): John Glass
%  Copyright 1986-2013 The MathWorks, Inc.

if ~isequal(size(Axes),[1 1 2])
   % Leave all properties empty for MIMO responses
   % RE: Can happen in Viewer with SISO and MIMO models
   return
end

%% Gain Margin Characteristics
this.MagPoints = handle(line(NaN,NaN,5,...
    'Parent',Axes(1),...
    'Visible','off',...
    'Marker','o',...
    'XLimInclude','off',...
    'YLimInclude','off',...
    'MarkerSize',6));
this.MagTips = wrfc.createDefaultHandle;

%% Phase Margin Characteristics
this.PhasePoints = handle(line(NaN,NaN,5,...
    'Parent',Axes(2),...
    'Visible','off',...
    'Marker','o',...
    'XLimInclude','off',...
    'YLimInclude','off',...
    'MarkerSize',6));
this.PhaseTips = wrfc.createDefaultHandle;
