function initialize(this, Axes)
%INITIALIZE  Initializes @hsvview objects.

%   Copyright 1986-2020 The MathWorks, Inc.
h = matlab.graphics.chart.primitive.Bar('XData',[],'YData',[],...
    'Parent', Axes, 'Visible', 'off', 'EdgeColor',[.8 0 0],'FaceColor',[.8 0 0],...
    'DisplayName',getString(message('Controllib:plots:strUnstableModes')));
this.InfiniteSV = h;

h = matlab.graphics.chart.primitive.Bar('XData',[],'YData',[],...
    'Parent', Axes, 'Visible', 'off', 'EdgeColor',[0 0 .6],'FaceColor',[0 0 .6],...
    'DisplayName',getString(message('Controllib:plots:strStableModes')));
this.FiniteSV = h;

h = handle(line('XData',[],'YData',[],...
    'Parent', Axes, 'Visible', 'off', 'Color',[1 0 1],...
    'LineWidth',2));
this.ErrorBnd = h;