function build(this)
%BUILD  Builds the IO Selector GUI.

%   Copyright 2013-2017 The MathWorks, Inc.

% Style variables
UIColor = get(0,'DefaultUIControlBackground');
PointsToPixels = 72/get(0,'ScreenPixelsPerInch');
StdUnit = 'points';

% Set font size and weight
if isunix
   FontSize = 10;
else
   FontSize = 8;
end

nu = length(this.InputName);
ny = length(this.OutputName);
FigWidth = 280;
FigHeight = 120+(max(ny, nu)*20);
FigPos = [120 120 FigWidth FigHeight];

Fig = figure('WindowStyle', 'normal','DockControls', 'off',...
   'Units', StdUnit,...
   'Position', PointsToPixels*FigPos,...
   'NumberTitle','off',...
   'IntegerHandle','off',...
   'HandleVisibility','Callback',...
   'Menu','none',...
   'Name',getString(message('Controllib:plots:strIOSelectorTitle')),...
   'Color',UIColor,...
   'CloseRequestFcn',{@LocalHide this},...
   'Visible','on',...
   'DefaultTextFontSize',FontSize);

% UI controls
uicontrol(Fig,...
   'Unit',StdUnit,...
   'Background',UIColor,...
   'Position',PointsToPixels*[FigWidth/2-65 10 60 20],...
   'Unit','normalized',...
   'Style','pushbutton',...
   'String',getString(message('Controllib:gui:strClose')),...
   'callback',{@LocalHide this});   

uicontrol(Fig,...
   'Unit',StdUnit,...
   'Background',UIColor,...
   'Position',PointsToPixels*[FigWidth/2+5 10 60 20],...
   'Unit','normalized',...
   'Style','pushbutton',...
   'String',getString(message('Controllib:gui:strHelp')),...
   'Callback',@localHelp);

L1p = [10 40 122 FigHeight-70];

L1 = uicontrol('Parent',Fig,...
   'Unit',StdUnit,...
   'Style', 'listbox',...
   'String',this.InputName,...
   'Position',PointsToPixels*L1p,...
   'Max',10,...
   'Units','norm',...
   'Callback',{@localSelectionChanged, 'Input', this},...
   'tag','InputList');

T1 = uicontrol('Parent',Fig,...
   'Unit',StdUnit,...
   'Style','Text',...
   'String',getString(message('Controllib:plots:strInputs')),...
   'Position',PointsToPixels*[L1p(1), L1p(2)+L1p(4), L1p(3), 15],...
   'BackgroundColor',UIColor*0.7,...
   'FontWeight','bold','Tag','InputLabel');

L2p = L1p; L2p(1) = L1p(1)+L1p(3)+15;

L2 = uicontrol('Parent',Fig,...
   'Unit',StdUnit,...
   'Style', 'listbox',...
   'String',this.OutputName,...
   'Position',PointsToPixels*L2p,...
   'Max',10,...
   'Units','norm',...
   'Callback',{@localSelectionChanged, 'Output', this},...
   'tag','OutputList');

T2 = uicontrol('Parent',Fig,...
   'Unit',StdUnit,...
   'Style','Text',...
   'String',getString(message('Controllib:plots:strOutputs')),...
   'Position',PointsToPixels*[L2p(1), L2p(2)+L2p(4), L2p(3), 15],...
   'BackgroundColor',UIColor*0.7,...
   'FontWeight','bold','Tag','OutputLabel');

this.Handles = struct(...
   'Figure', Fig,...
   'InputListbox', L1,...
   'OutputListbox', L2);
   
if nu==0
   set([L1;T1],'Enable','off')
elseif ny==0
   set([L2;T2],'Enable','off')
end

set(Fig,'ResizeFcn',{@localResize, L1, L2, T1, T2})

%--------------------------------------------------------------------------
function localResize(~,~,L1,L2,T1,T2)

set([L1;L2],'Units','Points');
Pos1 = get(L1,'Position');
Pos2 = get(L2,'Position');
set([L1;L2],'Units','Normalized');
set(T1, 'Position',[Pos1(1), Pos1(2)+Pos1(4), Pos1(3), 15])
set(T2, 'Position',[Pos2(1), Pos2(2)+Pos2(4), Pos2(3), 15])

%--------------------------------------------------------------------------
function localSelectionChanged(es,~,Type,this)
% Update object for list selection changes.

IsInput = strcmp(Type,'Input');
SelectedIndex = es.Value;
if IsInput
   Names = this.InputName;
else
   Names = this.OutputName;
end
Value = false(length(Names),1);
Value(SelectedIndex) = true;
if IsInput
   this.InputSelected = Value;
else
   this.OutputSelected = Value;
end

%--------------------------------------------------------------------------
function LocalHide(~,~,this)
this.Visible = 'off';

%--------------------------------------------------------------------------
function localHelp(varargin)
% CSH for I/O Selector
helpview('ident','iddata_plot_ioselector');
