function common_initialize(this, ax, gridsize)
%COMMON_INITIALIZE  Initializes the @noisespectrumplot objects. shaerd code
%between noisespectrumplot and plotpack.fspectrumplot.

%  Author(s): Rajiv Singh
%  Copyright 2011-2016 The MathWorks, Inc.

% Axes geometry parameters (main grid and 2x1 subgrid)
geometry = struct(...
   'HeightRatio',{[];[.53 .47]},...
   'HorizontalGap',{16;0},...
   'VerticalGap',{16;12},...
   'LeftMargin',{12;0},...
   'TopMargin',{20;0});

% Create @axesgrid object
this.AxesGrid = ctrluis.axesgrid(gridsize, ax, ...
   'Visible',     'off', ...
   'Geometry',    geometry, ...
   'LimitFcn',  {@updatelims this}, ...
   'LabelFcn',  {@LocalBuildLabels this}, ...
   'Title',    getString(message('Controllib:plots:strPowerSpectrum')), ...
   'XLabel',   getString(message('Controllib:plots:strFrequency')),...
   'XScale',   'log',...
   'XUnit',  'rad/s',...
   'YLabel', getString(message('Controllib:plots:strPower')),...
   'YScale',   'linear',...
   'YUnit',  'dB');

% Generic initialization
init_graphics(this)

% Add listeners
addlisteners(this)

%--------------------------------------------------------------------------
function LabelMap = LocalBuildLabels(this)
% Builds labels for Spectrum plots.
AxGrid = this.AxesGrid;

% Initialize label map
LabelMap = struct(...
   'XLabel',sprintf('%s %s',AxGrid.XLabel,LocalUnitInfo(AxGrid.XUnits)),...
   'XLabelStyle',AxGrid.XLabelStyle,...
   'YLabel',[],...
   'YLabelStyle',AxGrid.YLabelStyle,...
   'ColumnLabel',{AxGrid.ColumnLabel},...
   'ColumnLabelStyle',AxGrid.ColumnLabelStyle,...
   'RowLabel',[],...
   'RowLabelStyle',[]);

% Y label and row labels
MagLabel = {sprintf('%s%s',AxGrid.YLabel,LocalUnitInfo(AxGrid.YUnits))};

if prod(AxGrid.Size(1:2))>1
   % MIMO case: Mag goes to the YLabel field
   LabelMap.RowLabel = AxGrid.RowLabel;   
   LabelMap.RowLabelStyle = AxGrid.RowLabelStyle;   
   LabelMap.YLabel = MagLabel;
else
   % SISO case: Mag goes to the RowLabel field
   LabelMap.YLabel = '';
   LabelMap.RowLabel = MagLabel;
   LabelMap.RowLabelStyle = AxGrid.YLabelStyle;   
end

%--------------------------------------------------------------------------
function str = LocalUnitInfo(unit)
% Returns string capturing unit and transform info
if isempty(unit)
   str = '';
else
   str = sprintf(' (%s)',unit);
end
