function initialize(this,Axes)
%INITIALIZE  Initialization for @ConfidenceRegionSpectrumView class

%  Copyright 1986-2011 The MathWorks, Inc.

ny = size(Axes,1); % Ny-by-Ny
Axes = reshape(Axes,[ny*ny,1]);

UncertainMagPatch = zeros([ny ny]);

for ct = 1:ny^2
   UncertainMagPatch(ct) = patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct,1),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
end

this.UncertainMagPatch = handle(UncertainMagPatch);
UncertainMagLines = zeros([ny ny]);

for ct = 1:ny^2
   UncertainMagLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct,1),...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'Color',[0.9804 .9*0.9804 0.8235]);
end

this.UncertainMagLines = handle(UncertainMagLines);
