classdef Constants
    %CONSTANTS contain constant values for the toolstrip Communication Log
    %View and Controller classes.

    % Copyright 2021-2023 The MathWorks, Inc.
    properties (Constant)
        %% Columns
        % In general, a toolstrip column contains toolstrip UI elements
        % that are displayed one below the other (stacked vertically).

        % These column properties contain the width and alignment
        % information for each toolstrip column, which affects the
        % underlying UI elements' width and alignment.

        EmptyColumn = ...
            matlabshared.transportapp.internal.toolstrip.Manager.prepareEmptyToolstripColumn()

        CommunicationLogColumns = [...
            matlabshared.transportapp.internal.toolstrip.Manager.prepareToolstripColumn(80, "left"), ...
            matlabshared.transportapp.internal.toolstrip.Manager.prepareToolstripColumn( ...
                matlabshared.transportapp.internal.toolstrip.Manager.ButtonWidth, ...
                matlabshared.transportapp.internal.toolstrip.Manager.ButtonAlignment) ...
            ]

        %% Section Names
        CommunicationLogSectionName = message("transportapp:toolstrip:communicationlog:CommLogSectionName").getString

        %% Label Names
        DisplayLabel = message("transportapp:toolstrip:communicationlog:DisplayLabel").getString
        ClearLogButtonLabel = message("transportapp:toolstrip:communicationlog:ClearLogButtonLabel").getString

        %% Tooltip Messages
        DisplayTooltip = message("transportapp:toolstrip:communicationlog:DisplayTooltip").getString
        ClearLogButtonTooltip = message("transportapp:toolstrip:communicationlog:ClearLogButtonTooltip").getString

        %% Column1 Elements
        DisplayLabelProps = struct("Text", matlabshared.transportapp.internal.toolstrip.communicationlog.Constants.DisplayLabel, ...
            "Description", matlabshared.transportapp.internal.toolstrip.communicationlog.Constants.DisplayTooltip)

        DisplayDropDownOptions = [ ...
            "Default", ...
            "Binary", ...
            "ASCII", ...
            "Hexadecimal" ...
            ]

        DisplayDropDownProps = struct("Value", matlabshared.transportapp.internal.toolstrip.communicationlog.Constants.DisplayDropDownOptions(1), ...
            "Description", matlabshared.transportapp.internal.toolstrip.communicationlog.Constants.DisplayTooltip, ...
            "Tag", 'DisplayDropDown')

        %% Column2 Elements
        ClearLogButtonProps = struct("Text", matlabshared.transportapp.internal.toolstrip.communicationlog.Constants.ClearLogButtonLabel,...
            "Icon", matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository.getIcon("ict", "Clear"), ...
            "Description", matlabshared.transportapp.internal.toolstrip.communicationlog.Constants.ClearLogButtonTooltip, ...
            "Enabled", true, ...
            "Tag", 'ClearLogButton')

        %% Other Constants
        OptionStringText = ...
            message("transportapp:toolstrip:communicationlog:ClearLog").getString

        YesOption = ...
            string(message("transportapp:toolstrip:communicationlog:YesOption").getString)
        NoOption = ...
            string(message("transportapp:toolstrip:communicationlog:NoOption").getString)
    end
end
