
classdef CarlaWalkerControl < ros.Message
    %CarlaWalkerControl MATLAB implementation of carla_msgs/CarlaWalkerControl
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaWalkerControl' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'bd3de0306de3de4e7161a29868c1f9a7' % The MD5 Checksum of the message definition
        PropertyList = { 'Direction' 'Speed' 'Jump' } % List of non-constant message properties
        ROSPropertyList = { 'direction' 'speed' 'jump' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Vector3' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Direction
        Speed
        Jump
    end
    methods
        function set.Direction(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWalkerControl', 'Direction')
            obj.Direction = val;
        end
        function set.Speed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWalkerControl', 'Speed');
            obj.Speed = single(val);
        end
        function set.Jump(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWalkerControl', 'Jump');
            obj.Jump = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaWalkerControl.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaWalkerControl(strObj);
        end
    end
end
