
classdef CarlaTrafficLightStatus < ros.Message
    %CarlaTrafficLightStatus MATLAB implementation of carla_msgs/CarlaTrafficLightStatus
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaTrafficLightStatus' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'efe41b78c4438f29488e7ecfe6631a9b' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'State' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'state' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        RED = uint8(0)
        YELLOW = uint8(1)
        GREEN = uint8(2)
        OFF = uint8(3)
        UNKNOWN = uint8(4)
    end
    properties
        Id
        State
    end
    methods
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaTrafficLightStatus', 'Id');
            obj.Id = uint32(val);
        end
        function set.State(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaTrafficLightStatus', 'State');
            obj.State = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaTrafficLightStatus.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaTrafficLightStatus(strObj);
        end
    end
end
