
classdef CarlaEgoVehicleInfo < ros.Message
    %CarlaEgoVehicleInfo MATLAB implementation of carla_msgs/CarlaEgoVehicleInfo
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaEgoVehicleInfo' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7635942a53dfdf0edbbafc9eea467602' % The MD5 Checksum of the message definition
        PropertyList = { 'Wheels' 'CenterOfMass' 'Id' 'Type' 'Rolename' 'MaxRpm' 'Moi' 'DampingRateFullThrottle' 'DampingRateZeroThrottleClutchEngaged' 'DampingRateZeroThrottleClutchDisengaged' 'UseGearAutobox' 'GearSwitchTime' 'ClutchStrength' 'Mass' 'DragCoefficient' } % List of non-constant message properties
        ROSPropertyList = { 'wheels' 'center_of_mass' 'id' 'type' 'rolename' 'max_rpm' 'moi' 'damping_rate_full_throttle' 'damping_rate_zero_throttle_clutch_engaged' 'damping_rate_zero_throttle_clutch_disengaged' 'use_gear_autobox' 'gear_switch_time' 'clutch_strength' 'mass' 'drag_coefficient' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.carla_msgs.CarlaEgoVehicleInfoWheel' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Wheels
        CenterOfMass
        Id
        Type
        Rolename
        MaxRpm
        Moi
        DampingRateFullThrottle
        DampingRateZeroThrottleClutchEngaged
        DampingRateZeroThrottleClutchDisengaged
        UseGearAutobox
        GearSwitchTime
        ClutchStrength
        Mass
        DragCoefficient
    end
    methods
        function set.Wheels(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.carla_msgs.CarlaEgoVehicleInfoWheel.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.carla_msgs.CarlaEgoVehicleInfoWheel'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'Wheels')
            obj.Wheels = val;
        end
        function set.CenterOfMass(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'CenterOfMass')
            obj.CenterOfMass = val;
        end
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'Id');
            obj.Id = uint32(val);
        end
        function set.Type(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'Type');
            obj.Type = char(val);
        end
        function set.Rolename(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'Rolename');
            obj.Rolename = char(val);
        end
        function set.MaxRpm(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'MaxRpm');
            obj.MaxRpm = single(val);
        end
        function set.Moi(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'Moi');
            obj.Moi = single(val);
        end
        function set.DampingRateFullThrottle(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'DampingRateFullThrottle');
            obj.DampingRateFullThrottle = single(val);
        end
        function set.DampingRateZeroThrottleClutchEngaged(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'DampingRateZeroThrottleClutchEngaged');
            obj.DampingRateZeroThrottleClutchEngaged = single(val);
        end
        function set.DampingRateZeroThrottleClutchDisengaged(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'DampingRateZeroThrottleClutchDisengaged');
            obj.DampingRateZeroThrottleClutchDisengaged = single(val);
        end
        function set.UseGearAutobox(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'UseGearAutobox');
            obj.UseGearAutobox = logical(val);
        end
        function set.GearSwitchTime(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'GearSwitchTime');
            obj.GearSwitchTime = single(val);
        end
        function set.ClutchStrength(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'ClutchStrength');
            obj.ClutchStrength = single(val);
        end
        function set.Mass(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'Mass');
            obj.Mass = single(val);
        end
        function set.DragCoefficient(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaEgoVehicleInfo', 'DragCoefficient');
            obj.DragCoefficient = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaEgoVehicleInfo.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaEgoVehicleInfo(strObj);
        end
    end
end
