
classdef CarlaBoundingBox < ros.Message
    %CarlaBoundingBox MATLAB implementation of carla_msgs/CarlaBoundingBox
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaBoundingBox' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '17746d0996c54d9b8b0dfe6f3cd0b588' % The MD5 Checksum of the message definition
        PropertyList = { 'Center' 'Size' } % List of non-constant message properties
        ROSPropertyList = { 'center' 'size' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Center
        Size
    end
    methods
        function set.Center(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'CarlaBoundingBox', 'Center')
            obj.Center = val;
        end
        function set.Size(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'CarlaBoundingBox', 'Size')
            obj.Size = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaBoundingBox.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaBoundingBox(strObj);
        end
    end
end
