
classdef CarlaTrafficLightInfo < ros.Message
    %CarlaTrafficLightInfo MATLAB implementation of carla_msgs/CarlaTrafficLightInfo
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaTrafficLightInfo' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c303b00d6ff9db591d60b1662aec9d48' % The MD5 Checksum of the message definition
        PropertyList = { 'Transform' 'TriggerVolume' 'Id' } % List of non-constant message properties
        ROSPropertyList = { 'transform' 'trigger_volume' 'id' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.carla_msgs.CarlaBoundingBox' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Transform
        TriggerVolume
        Id
    end
    methods
        function set.Transform(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'CarlaTrafficLightInfo', 'Transform')
            obj.Transform = val;
        end
        function set.TriggerVolume(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.carla_msgs.CarlaBoundingBox'};
            validateattributes(val, validClasses, validAttributes, 'CarlaTrafficLightInfo', 'TriggerVolume')
            obj.TriggerVolume = val;
        end
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaTrafficLightInfo', 'Id');
            obj.Id = uint32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaTrafficLightInfo.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaTrafficLightInfo(strObj);
        end
    end
end
