
classdef CarlaActorList < ros.Message
    %CarlaActorList MATLAB implementation of carla_msgs/CarlaActorList
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaActorList' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a10ababa303f55dd50f485b995641f71' % The MD5 Checksum of the message definition
        PropertyList = { 'Actors' } % List of non-constant message properties
        ROSPropertyList = { 'actors' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.carla_msgs.CarlaActorInfo' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Actors
    end
    methods
        function set.Actors(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.carla_msgs.CarlaActorInfo.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.carla_msgs.CarlaActorInfo'};
            validateattributes(val, validClasses, validAttributes, 'CarlaActorList', 'Actors')
            obj.Actors = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaActorList.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaActorList(strObj);
        end
    end
end
