
classdef CarlaLaneInvasionEvent < ros.Message
    %CarlaLaneInvasionEvent MATLAB implementation of carla_msgs/CarlaLaneInvasionEvent
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaLaneInvasionEvent' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '3846cea49c4897522899dbda091314e8' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'CrossedLaneMarkings' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'crossed_lane_markings' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        LANEMARKINGOTHER = int32(0)
        LANEMARKINGBROKEN = int32(1)
        LANEMARKINGSOLID = int32(2)
    end
    properties
        Header
        CrossedLaneMarkings
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'CarlaLaneInvasionEvent', 'Header')
            obj.Header = val;
        end
        function set.CrossedLaneMarkings(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = int32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'CarlaLaneInvasionEvent', 'CrossedLaneMarkings');
            obj.CrossedLaneMarkings = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaLaneInvasionEvent.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaLaneInvasionEvent(strObj);
        end
    end
end
