
classdef CarlaStatus < ros.Message
    %CarlaStatus MATLAB implementation of carla_msgs/CarlaStatus
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/CarlaStatus' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '0a6e668a0d517dead8f5c68762fc1dab' % The MD5 Checksum of the message definition
        PropertyList = { 'Frame' 'FixedDeltaSeconds' 'SynchronousMode' 'SynchronousModeRunning' } % List of non-constant message properties
        ROSPropertyList = { 'frame' 'fixed_delta_seconds' 'synchronous_mode' 'synchronous_mode_running' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Frame
        FixedDeltaSeconds
        SynchronousMode
        SynchronousModeRunning
    end
    methods
        function set.Frame(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaStatus', 'Frame');
            obj.Frame = uint64(val);
        end
        function set.FixedDeltaSeconds(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaStatus', 'FixedDeltaSeconds');
            obj.FixedDeltaSeconds = single(val);
        end
        function set.SynchronousMode(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaStatus', 'SynchronousMode');
            obj.SynchronousMode = logical(val);
        end
        function set.SynchronousModeRunning(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaStatus', 'SynchronousModeRunning');
            obj.SynchronousModeRunning = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.CarlaStatus.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.CarlaStatus(strObj);
        end
    end
end
