
classdef GetBlueprintsRequest < ros.Message
    %GetBlueprintsRequest MATLAB implementation of carla_msgs/GetBlueprintsRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_msgs/GetBlueprintsRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '0665b698518980c549ffcc60283b661c' % The MD5 Checksum of the message definition
        PropertyList = { 'Filter' } % List of non-constant message properties
        ROSPropertyList = { 'filter' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Filter
    end
    methods
        function set.Filter(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'GetBlueprintsRequest', 'Filter');
            obj.Filter = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_msgs.GetBlueprintsRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_msgs.GetBlueprintsRequest(strObj);
        end
    end
end
