function [dsClsNames, fileBased, additionalParams] = getAvailableDatastores()
%getAvailableDatastores   Find the available datastore classes.
%   This function returns a cell array containing fully qualified names of
%   classes in the matlab.io.datastore package that are not abstract.

%   Copyright 2014-2020 The MathWorks, Inc.

% filter out abstract classes
% we expect all concrete classes in matlab.io.datastore to be datastores

availableDatastoreInfo = {
    % Class name                                % Is file based? % Additional parameters
    'matlab.io.datastore.ImageDatastore',       1,               {}      ; ...
    'matlab.io.datastore.TabularTextDatastore', 1,               {false} ; ...
    'matlab.io.datastore.SpreadsheetDatastore', 1,               {}      ; ...
    'matlab.io.datastore.ParquetDatastore',     1,               {}      ; ...
    'matlab.io.datastore.FileDatastore',        1,               {}      ; ...
    'matlab.io.datastore.DatabaseDatastore',    0,               {}      ; ...
    'matlab.io.datastore.KeyValueDatastore',    1,               {}      ; ...
    'matlab.io.datastore.TabularTextDatastore', 1,               {true}  ; ...
    'matlab.io.datastore.TallDatastore',        1,               {}        ...
};

dsClsNames = availableDatastoreInfo(:, 1)';
fileBased = cell2mat(availableDatastoreInfo(:, 2)');
additionalParams = availableDatastoreInfo(:, 3)';
end
