function viewer = createUnsavedFilesWarningDialog(root)
% Create warning dialog for unsaved changes.

% Copyright 2024 The MathWorks, Inc.

    import matlab.internal.project.unsavedchanges.TrackingLoadedFileProvider;
    import matlab.internal.cmlink.unsavedfiles.filter.unsavedInRootFolder;
    filter = @(files) unsavedInRootFolder(files, root);

    viewer = matlab.internal.project.unsavedchanges.ui.LoadedFileViewer(...
        TrackingLoadedFileProvider, ...
        filter, ...
        "FigureTitle", "shared_cmlink:view_core:OpenUnsavedFiles", ...
        "LabelSingleProblem", "shared_cmlink:view_core:SingleUnsavedFile", ...
        "LabelMultiProblem", "shared_cmlink:view_core:MultipleUnsavedFiles", ...
        "CancelButtonText", "MATLAB:project:view_unsaved_changes:Cancel", ...
        "AutoCloseUI", true);

    addlistener(viewer, "Close", @(~,~)delete(viewer));

end
