% Check if a value is a real object or not

% Copyright 2023 The MathWorks, Inc.

function isNonPrimitiveObject = checkNonPrimitiveObject(value)
    isNonPrimitiveObject = (~istabular(value) && ~isstring(value) && ...
        ~iscategorical(value) && ~iscell(value) && ...
        ~isdatetime(value) && ~isduration(value) && ...
        ~iscalendarduration(value) && ~ischar(value) && ...
        ~isstruct(value) && ~isa(value, 'collection') && ~isa(value, 'dataset')) && ...
        ((isobject(value) || (isnumeric(value) && ...
        ~internal.matlab.datatoolsservices.VariableUtils.isPrimitiveNumeric(value))));
end

