classdef RptFile< mlreportgen.report.Reporter & mlreportgen.report.internal.RptFileBase
%mlreportgen.report.RptFile Create a Report Explorer-based reporter
%   reporter = RptFile() creates an empty Report Explorer-based
%   reporter. Use the reporter's SetupFile property to specify a Report
%   Explorer setup (.rpt) file. You must specify the report setup file.
%   Adding an empty RptFile reporter object to a Report API report
%   produces an error. When added to a report, this reporter executes
%   the setup file to generate the report content, formats the content,
%   and includes the content in the Report API report. By default this
%   reporter uses a template corresponding to the default template used
%   by the Report Explorer's corresponding template-based output type.
%   For example, if the Report API's report output type is PDF, this
%   reporter uses a template corresponding to the Report Explorer's
%   PDF (from template) output type. To customize the appearance of the
%   content generated by this reporter, use this reporter's TemplateSrc
%   and TemplateName properties to specify a customized version of this
%   reporter's Word, PDF, or HTML template, depending on the report
%   output type.
%
%   reporter = RptFile(setupFile) creates a Report Explorer-based
%   reporter based on the specified Report Explorer setup (.rpt) file.
%
%   reporter = RptFile('p1', 'v1', 'p2', 'v2', ...) creates a Report
%   Explorer-based reporter and sets its properties (p1, p2, ...) to
%   the specified values (v1, v2, ...).
%
%   RptFile properties:
%     SetupFile             - Report setup file
%     TemplateSrc           - Source of this reporter's template
%     TemplateName          - Name of this reporter's template
%     LinkTarget            - Hyperlink target for this reporter's content
%
%   RptFile methods:
%     getClassFolder        - Get location of folder that contains this class
%     createTemplate        - Copy the default RptFile template
%     customizeReporter     - Subclasses RptFile for customization
%     getImpl               - Get DOM implementation for this reporter
%
%   Example:
%
%       % Create a report setup file "my_setup_file.rpt" on which to
%       % report on
%
%       % Create a report
%       rpt = mlreportgen.report.Report("MyReport", "pdf");
%
%       % Create a chapter
%       chap = mlreportgen.report.Chapter("RptFile Reporter Example");
%
%       % Create a RptFile reporter to report on "my_setup_file.rpt"
%       % report setup file content and add it to the chapter
%       rptFile = mlreportgen.report.RptFile("my_setup_file.rpt");
%       add(chap, rptFile);
%
%       % Add chapter to the report
%       add(rpt, chap);
%
%       % Close and view the report
%       close(rpt);
%       rptview(rpt);

     
    % Copyright 2018-2023 The MathWorks, Inc.

    methods
        function out=RptFile
        end

        function out=createTemplate(~) %#ok<STOUT>
            % template =
            % mlreportgen.report.RptFile.createTemplate(templatePath,type)
            %    is a static method that creates a copy of the RptFile
            %    reporter template specified by type at the location
            %    specified by templatePath. You can use this method to
            %    create a copy of a default RptFile reporter template to
            %    serve as a starting point for creating your own custom
            %    template.
        end

        function out=customizeReporter(~) %#ok<STOUT>
            % classfile = mlreportgen.report.RptFile.customizeReporter(toClasspath)
            %    is a static method that creates an empty class derived
            %    from the RptFile reporter class with the name toClasspath.
            %    You can use the generated class as a starting point for
            %    creating your own custom version of the RptFile reporter.
            %
            %    For example:
            %    mlreportgen.report.RptFile.customizeReporter("path_folder/MyRptFile.m")
            %    mlreportgen.report.RptFile.customizeReporter("+myApp/@RptFile")
        end

        function out=getClassFolder(~) %#ok<STOUT>
            % path = mlreportgen.report.RptFile.getClassFolder()
            %    returns the folder location which contains this class.
        end

        function out=getImpl(~) %#ok<STOUT>
            % Load the report setup file
        end

    end
end
