function supportedTCMap = getSupportedTCMap
%

%   Copyright 2019-2024 The MathWorks, Inc.

    supportedTCMap = containers.Map({'MSVC150',  'MSVC160', 'MSVC170',...
                                     'MSVCPP150', 'MSVCPP160', 'MSVCPP170',...
                                     'gcc', 'g++' },...
                                    {'NVIDIA CUDA (w/Microsoft Visual C++ 2017) | nmake (64-bit Windows)',...
                                     'NVIDIA CUDA (w/Microsoft Visual C++ 2019) | nmake (64-bit Windows)',...
                                     'NVIDIA CUDA (w/Microsoft Visual C++ 2022) | nmake (64-bit Windows)',...
                                     'NVIDIA CUDA (w/Microsoft Visual C++ 2017) | nmake (64-bit Windows)',...
                                     'NVIDIA CUDA (w/Microsoft Visual C++ 2019) | nmake (64-bit Windows)',...
                                     'NVIDIA CUDA (w/Microsoft Visual C++ 2022) | nmake (64-bit Windows)',...
                                     'NVIDIA CUDA | gmake (64-bit Linux)',...
                                     'NVIDIA CUDA | gmake (64-bit Linux)'});
end
