function initialize(this,Axes)
%INITIALIZE  Initialization for @FreqPeakRespView class

%  Author(s): John Glass
%  Copyright 1986-2010 The MathWorks, Inc.

[s1,s2] = size(Axes(:,:,1));
VLines = zeros([s1 s2]);
HLines = zeros([s1 s2]);
Points = zeros([s1 s2]);

for ct=1:s1*s2   
   % Plot vertical lines
   VLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct),...
      'Visible','off',...
      'LineStyle','-.',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility','off','HitTest','off');
   matlab.graphics.internal.themes.specifyThemePropertyMappings(VLines(ct),...
       'Color',"--mw-graphics-colorNeutral-line-secondary");
   %% Plot horizontal lines
   HLines(ct) = line([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Axes(ct),...
      'Visible','off',...
      'LineStyle','-.',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility','off','HitTest','off');
   matlab.graphics.internal.themes.specifyThemePropertyMappings(HLines(ct),...
       'Color',"--mw-graphics-colorNeutral-line-secondary");
   %% Plot characteristic points
   Points(ct) = line(NaN,NaN,[5],...
      'Parent',Axes(ct),...
      'XlimInclude','off',...
      'YlimInclude','off',...
      'Visible','off',...
      'Marker','o',...
      'MarkerSize',6);
end

this.VLines = handle(VLines);
this.HLines = handle(HLines);
this.Points = handle(Points);
this.PointTips = cell([s1 s2]);