classdef (Sealed) AppSpaceForm < matlabshared.transportapp.internal.utilities.forms.BaseForm
    %APPSPACEFORM class contains the appspace section details that are
    %needed to create the appspace section. This includes the names of all
    %the appspace section View and Controller classes, like the
    %CommunicationLogSectionView and CommunicationLogSectionController, and
    %the transport.

    % Copyright 2020-2022 The MathWorks, Inc.

    properties
       %% COMMUNICATION LOG SECTION
       CommunicationLogSectionView (1,1) matlabshared.transportapp.internal.utilities.forms.Entries = ...
           matlabshared.transportapp.internal.utilities.forms.Entries("matlabshared.transportapp.internal.appspace.communicationlog.View")

       CommunicationLogSectionController (1,1) matlabshared.transportapp.internal.utilities.forms.Entries = ...
           matlabshared.transportapp.internal.utilities.forms.Entries("matlabshared.transportapp.internal.appspace.communicationlog.Controller")

       %% PROPERTY INSPECTOR SECTION
       PropertyInspectorManager (1,1) matlabshared.transportapp.internal.utilities.forms.Entries = ...
           matlabshared.transportapp.internal.utilities.forms.Entries("matlabshared.transportapp.internal.appspace.propertyinspector.Manager")

       PropertyInspectorLayout (1,1) matlabshared.transportapp.internal.utilities.forms.AppSpaceGridLayout = ...
           matlabshared.transportapp.internal.utilities.forms.AppSpaceGridLayout(1, 1);

       PropertyInspectorParentProps struct = struct( ...
           'ColumnWidth', "1x", ...
           'RowHeight', "1x", ...
           'Padding', [0 0 0 0] ...
           );

       PropertyInspectorSidePanelProperties struct = struct( ...
           "Tag", "PropertyInspectorSidePanel", ... % This needs to be a unique string
           "Title", string(message("transportapp:appspace:appspace:PropertyInspectorName").getString), ...
           "Maximizable", false, ...
           "Collapsible", false, ...
           "Collapsed", true, ...
           "Region", "right", ...
           "PermissibleRegions", "right" ...
           )

       PropertyInspectorSidePanel

       % The Read Warning ID's for the transport that the shared_app will
       % show a dialog for whenever a read timeout warning happens.
       ReadWarningIDs (1,:) string
    end
end
