%mlreportgen.dom.TemplateTextStyle Style that formats text
%    style = TemplateTextStyle() creates a text style object with an empty
%    name. You must set the object's Name property to use the style.
%
%    style = TemplateTextStyle(name) creates a text style and sets its Name
%    property to name. Add this style to the Stylesheet object specified by
%    a template's Stylesheet property. This causes the style to be included
%    in the stylesheet of the generated template file. Set the StyleName
%    property of a Text object to the name of this style to apply the style
%    to the text generated by a document that uses the template.
%
%    TemplateTextStyle properties:
%        Name                   - Name of this style
%        Formats                - DOM formatting objects that define this style
%        Id                     - Id of this style
%        Tag                    - Tag of this style
%
%    Example:
%
%     import mlreportgen.dom.*;
%     t = Template("myTemplate","pdf");
%     open(t);
%
%     % Create a text style
%     textStyle = TemplateTextStyle("myTextStyle");
%     % Define formats for the text style
%     textStyle.Formats = [Bold, Color("blue")];
%     % Add style to the stylesheet
%     addStyle(t.Stylesheet,textStyle);
%
%     % Close the template
%     close(t);
%
%     % Use the style from the template
%
%     % Create a document using the generated template
%     d = Document("myDoc","pdf","myTemplate");
%     open(d);
%
%     % Create a text object
%     txt = Text("example text");
%     % Set the style name
%     txt.StyleName = "myTextStyle";
%
%     % Add the text to the document
%     append(d,txt);
%
%     % Close and view the document
%     close(d);
%     rptview(d);
%
%     See also mlreportgen.dom.Template, mlreportgen.dom.TemplateStylesheet 

%    Copyright 2023 The MathWorks, Inc.
%    Built-in class

%{
properties

    %Name Name of this style
    %     Name of the style, specified as a string. The name may only 
    %     include alphanumerics, "-", or "_" characters.
    Name;

end
%}