%#codegen
function validateMeasurementMatrix(value, objname, len)

%   Copyright 2015-2018 The MathWorks, Inc.

validateattributes(value, ...
    {'numeric'}, ...
    {'real', 'finite', 'nonsparse', '2d'},...
    objname, 'z_matrix');

if nargin >= 3
    isInvalidZSize = ~(isempty(value) || size(value, 2) == len ...
        || all(size(value) == [len, 1]));
    coder.internal.errorIf(...
        isInvalidZSize, ...
        'shared_tracking:KalmanFilter:invalidZSize', len, len);
end
end
