function initialize(this, Parent)
%

%  Copyright 1986-2012 The MathWorks, Inc.
if ishghandle(Parent,'hggroup')
    set(Parent,'HitTest','off')
end

this.Patch = handle(patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Parent,...
      'Visible','off',...
      'Selected','off',...
      'XlimInclude','off', 'YlimInclude','off',...
      'HandleVisibility','off','HitTest','off'));