function initialize(this,Groups)
%INITIALIZE  Initialization for @SpectralBoundView class

%  Author(s): Craig Buhr
%   Copyright 1986-2012 The MathWorks, Inc.

% Create empty curves
[Ny,Nu] = size(Groups);
set(Groups,'HitTest','off');

% Create empty patches
SpectralRadiusPatch = zeros(Ny*Nu,1); 
SpectralAbscissaPatch = zeros(Ny*Nu,1);
for ct = 1:Ny*Nu
   SpectralRadiusPatch(ct,1) = patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Groups(ct),...
      'Visible','off',...
      'Selected','off',...%      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
  
  SpectralAbscissaPatch(ct,1) =  patch([NaN,NaN],[NaN,NaN],[-10,-10],...
      'Parent',Groups(ct),...
      'Visible','off',...
      'Selected','off',...%      'XlimInclude','off', 'YlimInclude','on',...
      'HandleVisibility','off','HitTest','off',...
      'FaceColor',[0.9804 .9*0.9804 0.8235],'EdgeColor',[0.9804 .9*0.9804 0.8235]);
  
end
this.SpectralRadiusPatch = reshape(handle(SpectralRadiusPatch),[Ny Nu]);
this.SpectralAbscissaPatch = reshape(handle(SpectralAbscissaPatch),[Ny Nu]);

