classdef (Sealed) ICTIconRepository < matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository
    %ICTICONREPOSITORY is the specialized icon-repository class for ICT.

    % Copyright 2023 The MathWorks, Inc.

    %% Implementing abstract properties of IconRepository
    properties (Constant)

        % A dictionary of Icon ID and corresponding icon fullpath (old-style)
        % or icon id (new-style). Eventually, all icons will have an
        % icon-id (new-style) and the old-style icons will be removed.

        IconDictionary = dictionary( ...
            ... %% Main App Icons
            "Write", "arrowActionEast_digits", ...
            "Read", "arrowActionWest_digits", ...
            "WriteRead", "arrowActionWestArrowActionEast", ...
            "Flush", "clear_database", ...
            "Clear", "clear", ...
            "Plot", "plot", ...
            "SignalAnalyzer", "signalAnalyzerApp", ...
            "ExportButton", "export", ...
            "ExportScript", "export_script", ...
            "ExportRow", "export_data", ...
            "ExportTable", "export_table", ...
            ...
            ... %% Modal Tab Icons
            "Settings", "settings", ...
            "VisaTestConnection", "edit_check", ...
            "Help", "help", ...
            ...
            ... %% App Gallery Icons
            "SerialExplorerAppGallery", "SerialExplorerApp", ...
            "TCPIPExplorerAppGallery", "tcpIpExplorerApp", ...
            "UDPExplorerAppGalley", "UDPExplorerApp", ...
            "VisaExplorerAppGallery", "visaExplorerApp", ...
            "InstrumentExplorerAppGallery", "instrumentExplorerApp" ...
            )
    end

    %% Other constants
    properties (Constant)
        % Icon Paths where all the toolbox icons are present.
        % NOTE - THESE PATHS WILL BE REMOVED ONCE THE THEMEABLE ICONS ARE
        % AVAILABLE
        SharedTransportPath = fullfile(matlabroot, "toolbox", "shared", "transportapp", "icons")
    end
end

