function  mustBeValidDependencyType(deps)
%

%   Copyright 2024 The MathWorks, Inc.

    if ~isa(deps, "matlab.mpm.Package") && ~matlab.mpm.internal.istext(deps) && ...
        ~isa(deps, "matlab.mpm.Dependency") && ~isa(deps, "matlab.mpm.PackageSpecifier")
        error("mpm:arguments:InvalidArgumentType", ...
              message("mpm:arguments:InvalidArgumentTypeOneOf", ...
                      "Dependency", ...
                      message("mpm:arguments:InvalidArgumentFourTypes", ...
                              "string", ...
                              "matlab.mpm.Package", ...
                              "matlab.mpm.PackageSpecifier", ...
                              "matlab.mpm.Dependency").string()).string());
    end
end
