classdef GraphicsColor < handle
    % GraphicsColor    
    %
    % Creates a themeable graphics color based on order
    % and state. Returns a semantic name, as well as RGB values for a
    % specific theme.
    %
    %   c = controllib.plot.internal.utils.GraphicsColor(2,"secondary");
    %   c.SemanticName
    %
    %       ans = 
    %
    %           "--mw-graphics-colorOrder-2-secondary"
    %
    %   getRGB(c,matlab.graphics.internal.themes.darkTheme)
    %
    %       ans =
    %
    %           0.6353    0.2627    0.0078
    %
    %
    % Create vector of Semantic Color Names
    %
    %   semanticNames = controllib.plot.internal.utils.GraphicsColor([2 5],["primary","secondary"]).SemanticName
    %
    %       semanticNames = 
    % 
    %           4×1 string array
    % 
    %               "--mw-graphics-colorOrder-2-primary"
    %               "--mw-graphics-colorOrder-2-secondary"
    %               "--mw-graphics-colorOrder-5-primary"
    %               "--mw-graphics-colorOrder-5-secondary"
    %
    %
    %   allSemanticNames = controllib.plot.internal.utils.GraphicsColor(1:12,"all").SemanticName
    %
    %       allSemanticNames = 
    % 
    %           48×1 string array
    % 
    %               "--mw-graphics-colorOrder-1-primary"
    %               "--mw-graphics-colorOrder-1-secondary"
    %               "--mw-graphics-colorOrder-1-tertiary"
    %               "--mw-graphics-colorOrder-1-quaternary"
    %               "--mw-graphics-colorOrder-2-primary"
    %               "--mw-graphics-colorOrder-2-secondary"
    %               .
    %               .
    %               "--mw-graphics-colorOrder-12-quaternary"


    % Copyright 2023 The MathWorks, Inc.

    properties (Dependent)
        SemanticName
    end

    properties (Access = private)
        Order (1,:) double
        State (1,:) string
        SemanticColorOrder (1,1) dictionary = createSemanticColorOrderDictionary()
    end

    methods
        function this = GraphicsColor(order,state)
            arguments
                order (1,:) double {mustBeMember(order,1:12)}
                state (1,:) string {mustBeMember(state,["primary","secondary","tertiary","quaternary","all"])} ...
                    = "primary"
            end
            this.Order = order;
            if state == "all"
                this.State = ["primary","secondary","tertiary","quaternary"];
            else
                this.State = state;
            end
        end

        function SemanticName = get.SemanticName(this)
            SemanticName = repmat("",length(this.Order)*length(this.State),1);
            ctr = 1;
            for kOrder = 1:length(this.Order)
                for kState = 1:length(this.State)
                    SemanticName(ctr) = this.SemanticColorOrder(this.Order(kOrder) + this.State(kState));
                    ctr = ctr+1;
                end
            end
            
        end

        function RGB = getRGB(this,theme)
            arguments
                this
                theme matlab.graphics.theme.GraphicsTheme
            end
            RGB = matlab.graphics.internal.themes.getAttributeValue(theme,this.SemanticName);
        end
    end
end

function d = createSemanticColorOrderDictionary()
d = dictionary(1+"primary",     "--mw-graphics-colorOrder-1-primary",...
               1+"secondary",   "--mw-graphics-colorOrder-1-secondary",...
               1+"tertiary",    "--mw-graphics-colorOrder-1-tertiary",...
               1+"quaternary",  "--mw-graphics-colorOrder-1-quaternary",...
               2+"primary",     "--mw-graphics-colorOrder-2-primary",...
               2+"secondary",   "--mw-graphics-colorOrder-2-secondary",...
               2+"tertiary",    "--mw-graphics-colorOrder-2-tertiary",...
               2+"quaternary",  "--mw-graphics-colorOrder-2-quaternary",...
               3+"primary",     "--mw-graphics-colorOrder-3-primary",...
               3+"secondary",   "--mw-graphics-colorOrder-3-secondary",...
               3+"tertiary",    "--mw-graphics-colorOrder-3-tertiary",...
               3+"quaternary",  "--mw-graphics-colorOrder-3-quaternary",...
               4+"primary",     "--mw-graphics-colorOrder-4-primary",...
               4+"secondary",   "--mw-graphics-colorOrder-4-secondary",...
               4+"tertiary",    "--mw-graphics-colorOrder-4-tertiary",...
               4+"quaternary",  "--mw-graphics-colorOrder-4-quaternary",...
               5+"primary",     "--mw-graphics-colorOrder-5-primary",...
               5+"secondary",   "--mw-graphics-colorOrder-5-secondary",...
               5+"tertiary",    "--mw-graphics-colorOrder-5-tertiary",...
               5+"quaternary",  "--mw-graphics-colorOrder-5-quaternary",...
               6+"primary",     "--mw-graphics-colorOrder-6-primary",...
               6+"secondary",   "--mw-graphics-colorOrder-6-secondary",...
               6+"tertiary",    "--mw-graphics-colorOrder-6-tertiary",...
               6+"quaternary",  "--mw-graphics-colorOrder-6-quaternary",...
               7+"primary",     "--mw-graphics-colorOrder-7-primary",...
               7+"secondary",   "--mw-graphics-colorOrder-7-secondary",...
               7+"tertiary",    "--mw-graphics-colorOrder-7-tertiary",...
               7+"quaternary",  "--mw-graphics-colorOrder-7-quaternary",...
               8+"primary",     "--mw-graphics-colorOrder-8-primary",...
               8+"secondary",   "--mw-graphics-colorOrder-8-secondary",...
               8+"tertiary",    "--mw-graphics-colorOrder-8-tertiary",...
               8+"quaternary",  "--mw-graphics-colorOrder-8-quaternary",...
               9+"primary",     "--mw-graphics-colorOrder-9-primary",...
               9+"secondary",   "--mw-graphics-colorOrder-9-secondary",...
               9+"tertiary",    "--mw-graphics-colorOrder-9-tertiary",...
               9+"quaternary",  "--mw-graphics-colorOrder-9-quaternary",...
               10+"primary",     "--mw-graphics-colorOrder-10-primary",...
               10+"secondary",   "--mw-graphics-colorOrder-10-secondary",...
               10+"tertiary",    "--mw-graphics-colorOrder-10-tertiary",...
               10+"quaternary",  "--mw-graphics-colorOrder-10-quaternary",...
               11+"primary",     "--mw-graphics-colorOrder-11-primary",...
               11+"secondary",   "--mw-graphics-colorOrder-11-secondary",...
               11+"tertiary",    "--mw-graphics-colorOrder-11-tertiary",...
               11+"quaternary",  "--mw-graphics-colorOrder-11-quaternary",...
               12+"primary",     "--mw-graphics-colorOrder-12-primary",...
               12+"secondary",   "--mw-graphics-colorOrder-12-secondary",...
               12+"tertiary",    "--mw-graphics-colorOrder-12-tertiary",...
               12+"quaternary",  "--mw-graphics-colorOrder-12-quaternary");
               
end