function names = supportedTypeNames()
    % SUPPORTEDTYPENAMES get the list of names which are supported types for import.
    
    % Copyright 2016-2017 The MathWorks, Inc.
    names ={'double',...
            'single',...
            'int8',...
            'uint8',...
            'int16',...
            'uint16',...
            'int32',...
            'uint32',...
            'int64',...
            'uint64',...
            'char',...
            'string',...
            'datetime',...
            'duration',...
            'categorical',...
            'logical'};
end

