//
// Copyright 2025 The MathWorks, Inc

// Added the below rules to silence the ESLint warnings

/* eslint-disable max-len */
/* eslint-disable no-template-curly-in-string */
/* eslint-disable quotes */
/* eslint-disable no-useless-escape */

//
// DO NOT MODIFY THIS FILE!!  This is a derived file.
// Instead, modify the English message catalog XML file "en/rosgraphapp/view.xml"
// Note, that Non-English message catalog XML files are derived from their English counterpart.
//
// Encoding: UTF-8

define({
    root:
({
    Actions: "Actions",
    ClearFilters: "Clearing applied filters...",
    ClearFiltersButton: "Clear Filters",
    CopyNameOption: "Copy Name",
    DataTypes: "Message Types",
    DescriptionActionSvcTopicChkBox: "Show default topics and services related to actions",
    DescriptionAutoArrangehButton: "Auto arrange the elements",
    DescriptionConnectButton: "Connect to ROS 2 Network",
    DescriptionDeadSinkChkBox: "Show topics with subscribers but no publishers",
    DescriptionDefaultChkBox: "Show /parameters_events and /rosout topics",
    DescriptionDefaultSvcChkBox: "Show /describe_parameters, /get_parameter_types, and other default services related to ROS 2 network",
    DescriptionDomainIdLabel: "ROS 2 Network Graph",
    DescriptionExportBtn: "Export snapshot of the network graph",
    DescriptionKeyWordFilterTextArea: "Input one or multiple keywords, separated by commas and press enter to search for elements containing at least one of the specified terms",
    DescriptionLastUpdatedLabel: "ROS 2 Network Graph",
    DescriptionLayoutDropDown: "Select a layout to arrange the elements",
    DescriptionLeafTopicChkBox: "Show topics with publishers but no subscribers",
    DescriptionNameSpaceSpinner: "Adjust the spinner to set namespace depth to nest nodes in labeled rectangles for visual hierarchical organization",
    DescriptionPropertyPnl: "Property Inspector Panel",
    DescriptionRefreshButton: "Refresh the ROS 2 Network",
    DescriptionUnreachableChkBox: "Show nodes that do not publish or subscribe to topics, or act as service servers or clients, or act as action servers or clients.",
    EnterNetworkDetails: "Enter Network Details",
    ErrorFailedToConnectToNetwork: "Unable to connect to Domain ID ${0}.",
    FilterButton: "Apply Filters",
    FilterByButton: "Advanced Filter By",
    FilterGraph: "Filtering ROS 2 Network...",
    KeywordFilterPlaceholder: "Input keywords, regular expressions or negative keywords.",
    KeywordFilterTooltip: "<b>Keyword:</b> Include entities that contain specific words, such as camera or GPS.<br> <b>Regular Expression:</b> Match entities using patterns like .*camera.* or gps.* for flexible searching.<br> <b>Exclude:</b> Use ~ before a keyword to exclude entities, like ~debug and ~camera.<br> <b>Multiple Inputs:</b> Enter multiple filters by separating them with commas.",
    LabelSearch: "Search",
    LayoutBreadthfirst: "breadthfirst",
    LayoutCircle: "circle",
    LayoutConcentric: "concentric",
    LayoutCose: "cose",
    LayoutDagre: "dagre",
    LayoutGrid: "grid",
    LayoutKlay: "klay",
    LoadGraph: "Acquiring network details for ROS Domain ID ${0}...",
    MessageFilterPlaceholder: "Input message types, service types or action types. e.g: sensor_msgs/Image",
    MessageFilterTooltip: "Input one or multiple message types, service types, and action types, separated by commas to filter the elements corresponding to at least one of the specified types.",
    NetworkDepthLabel: "Network Depth",
    Nodes: "Nodes",
    NumberSpinnerTooltip: "Adjust the spinner to set the number of connected entity levels displayed around the filtered entities.",
    PlaceHolderApplyKeywordFilter: "Input keywords and press enter",
    PropertyActClient: "Action clients",
    PropertyActClientNodes: "Action client nodes",
    PropertyActServer: "Action servers",
    PropertyActServerNodes: "Action server nodes",
    PropertyActType: "Action type",
    PropertyConnectionType: "Connection type",
    PropertyDomainId: "Domain ID",
    PropertyEntity: "Entity",
    PropertyInformationUnavailable: "Information not available",
    PropertyName: "Name",
    PropertyNodeName: "Node name",
    PropertyNumberOfActions: "Number of actions",
    PropertyNumberOfNodes: "Number of nodes",
    PropertyNumberOfServices: "Number of services",
    PropertyNumberOfTopics: "Number of topics",
    PropertyParameters: "Parameters",
    PropertyPublisherNodes: "Publisher nodes",
    PropertyPublishesTo: "Publishes to",
    PropertyQOSDeadline: "QoS Deadline",
    PropertyQOSDepth: "QoS Depth",
    PropertyQOSDurability: "QoS Durability",
    PropertyQOSHistory: "QoS History",
    PropertyQOSLeaseDuration: "QoS Lease Duration",
    PropertyQOSLifespan: "QoS Lifespan",
    PropertyQOSLiveliness: "QoS Liveliness",
    PropertyQOSReliability: "QoS Reliability",
    PropertySubscriberNodes: "Subscriber nodes",
    PropertySubscribesTo: "Subscribes to",
    PropertySvcClient: "Service clients",
    PropertySvcClientNodes: "Service client nodes",
    PropertySvcServer: "Service servers",
    PropertySvcServerNodes: "Service server nodes",
    PropertySvcType: "Service type",
    PropertyTableKeys: "Keys",
    PropertyTableValues: "Values",
    PropertyTopicName: "Topic name",
    PropertyTopicType: "Topic type",
    Ros2NetworkAnalyzerAppTitle: "ROS 2 Network Analyzer",
    Services: "Services",
    TextActionListTreeView: "Actions",
    TextActionSvcTopicChkBox: "Action Topics and Action Services",
    TextAdvancedFilterButton: "Advanced \nFilters",
    TextApplyKeywordFilterBtn: "Apply Filter",
    TextAutoArrangeButton: "Auto\nArrange",
    TextConnectButton: "Connect",
    TextDeadSinkChkBox: "Dead Sinks",
    TextDefaultChkBox: "Default Topics",
    TextDefaultSvcChkBox: "Default Services",
    TextEnterDomainIdBtn: "Submit",
    TextExportBtn: "Export",
    TextLabelDomainId: "Domain ID",
    TextLayoutLabel: "Layout",
    TextLeafTopicChkBox: "Leaf Topics",
    TextNameSpaceSpinnerLbl: "Namespace",
    TextNodeListTreeView: "Nodes",
    TextRefreshButton: "Refresh",
    TextServiceListTreeView: "Services",
    TextTopicListTreeView: "Topics",
    TextUnreachableChkBox: "Unreachable Nodes",
    TitleConnectionSection: "Network Connection",
    TitleDoc: "ROS 2 Network Graph",
    TitleDocGroup: "ROS 2 Network Graph",
    TitleExportBtn: "Export",
    TitleFilterSection: "Filter",
    TitleLayoutSection: "Layout",
    TitleNetworkBrowserPnl: "Network Browser",
    TitlePropertyPnl: "Properties",
    TitleTabMain: "ROS 2 Network Analyzer",
    TitleViewSection: "View",
    Topics: "Topics",
    UpdateNetworkDepth: "Updating network depth..."
}),
    "ja-jp": true,
    "ko-kr": true
});
