function [checks, groupIds] = codeAnalyzerChecks()
%codeAnalyzerChecks gets a table of checks used by the Code Compatibility Report.

%   Copyright 2017-2021 The MathWorks, Inc.

    configFile = matlab.internal.codecompatibilityreport.getConfigFile();
    caChecks = builtin('_getCodeAnalyzerChecks', char(configFile));
    caChecks = caChecks([caChecks.isEnabled]);
    activeChecks = struct2table(caChecks);

    % Get documentation commands for checks
    docColumn = matlab.internal.codecompatibilityreport.documentationColumn(activeChecks);

    columnNames = {'Identifier','Description','Documentation','Severity','CategoryIdentifier','CategoryDescription', ...
                   'ReleaseAnnounce', 'ReleaseWarn', 'ReleaseError', 'ReleaseChange', };
    checks = table( categorical(activeChecks{:,'MessageIdentifier'}), ...
                    string(activeChecks{:,'MessageDescription'}), ...
                    docColumn, ...
                    categorical(activeChecks{:,'Severity'}), ...
                    categorical(activeChecks{:,'CategoryIdentifier'}), ...
                    string(activeChecks{:,'CategoryDescription'}), ...
                    string(activeChecks{:,'ReleaseAnnounce'}), ...
                    string(activeChecks{:,'ReleaseWarn'}), ...
                    string(activeChecks{:,'ReleaseError'}), ...
                    string(activeChecks{:,'ReleaseChange'}), ...
                    'VariableNames', columnNames);
    groupIds = string(unique(checks.CategoryIdentifier))';
end
