function [text,fcnName] = getGroupExampleFcnText(app,type)
% Create an example function to be used as the method for each grouping
% function in the ComputeByGroupTask

%   Copyright 2021-2024 The MathWorks, Inc.

if app.IsTabularInput
    inputText = getMsgText('InputTable','x');
else
    inputText = getMsgText('InputArray','x');
end

switch type
    case 'groupsummary'
        fcnName = 'mySummaryFcn'; 
        text = ['function y = ' fcnName '(x)' newline ...
            '% ' inputText newline ...
            '% ' getMsgText('SummaryOutput','y') newline ...
            '% ' getMsgText('SummaryExample') newline ...
            'y = nnz(isoutlier(x));' newline ...
            'end'];
           
    case 'grouptransform'
        fcnName = 'myTransformFcn';
        text = ['function y = ' fcnName '(x)' newline ...
            '% ' inputText newline ...
            '% ' getMsgText('TransformOutput','y','x') newline ...
            '% ' getMsgText('TransformExample1') newline ...
            'y = x./mean(x);' newline ...
            '% ' getMsgText('TransformExample2') newline ...
            '% y = mean(x);' newline ...
            'end'];
    case 'groupfilter'
        fcnName = 'myFilterFcn';
        text = ['function tf = ' fcnName '(x)' newline ...
            '% ' inputText newline ...
            '% ' getMsgText('FilterOutput','tf','x') newline ...
            '% ' getMsgText('FilterExample1') newline ...
            'tf = mean(x) > 10;' newline ...
            '% ' getMsgText('FilterExample2') newline ...
            '% tf = ~isoutlier(x);' newline ...
            'end'];
end

text = [newline, text, newline];
end

function s = getMsgText(msgId,varargin)
% gets the appropriate char from the message catalog
s = getString(message(['MATLAB:tableui:groupingCodeComment' msgId],varargin{:}));
end
