function signal = createEmptySignal()
% Helper to create empty structure for signal

% Copyright 2020 The MathWorks, Inc.
signal = struct('Construction','',...
    'Value',[],...
    'SubSource','',...
    'Source','',...
    'Length',[],...
    'Column',[],...
    'Name','',...
    'Interval',[],...
    'Size',[0 0],...
    'Transposed',false);
end