/**:
    ros__parameters:
      # LiDAR setting
      pointCloudTopic: "input_cloud"
      sensor: velodyne    # lidar sensor type, 'velodyne' or 'ouster' or 'livox'
      N_SCAN: 32          # number of lidar channel (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
      Horizon_SCAN: 1800  # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048, Livox Horizon: 4000)
      # IMU setting
      imuTopic: "imu"
      imuAccNoise: 3.9939570888238808e-03
      imuGyrNoise: 1.5636343949698187e-03
      imuAccBiasN: 6.4356659353532566e-05
      imuGyrBiasN: 3.5640318696367613e-05
      imuGravity: 9.80511
      extrinsicTrans: [0.0, 0.0, 0.0]
      extrinsicRot: [ 1.0, 0.0, 0.0,
                      0.0, 1.0, 0.0,
                      0.0, 0.0, 1.0]
      extrinsicRPY: [ 1.0,  0.0, 0.0,
                      0.0, 1.0, 0.0,
                      0.0, 0.0, 1.0]

scan_matcher:
    ros__parameters:
      global_frame_id: "map"
      robot_frame_id: "base_link"
      registration_method: "NDT"
      ndt_resolution: 1.0
      ndt_num_threads: 0
      trans_for_mapupdate: 1.0
      vg_size_for_input: 0.3
      vg_size_for_map: 0.3
      use_min_max_filter: false
      map_publish_period: 1.0
      num_targeted_cloud: 20
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qw: 0.707
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: -0.707
      use_imu: true
      use_odom: false
      debug_flag: false

graph_based_slam:
    ros__parameters:
      registration_method: "GICP"
      ndt_resolution: 1.0
      ndt_num_threads: 0
      voxel_leaf_size: 0.3
      loop_detection_period: 1000
      threshold_loop_closure_score: 1.0
      distance_loop_closure: 2.0
      range_of_searching_loop_closure: 5.0
      search_submap_num: 2
      num_adjacent_pose_cnstraints: 3
      use_save_map_in_loop: false
