% Copyright 2025 The MathWorks, Inc.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% THIS FILE WAS GENERATED FROM THE FOLLOWING SCRIPT:                %
% toolbox/shared/cxxfe/parser_m/gen-getCxxCompToCCompInfoPair.pl    %
%                                                                   %
% DO NOT EDIT IT. YOUR CHANGES WILL BE LOST.                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [infoPair, c2CxxCompPair] = getCxxCompToCCompInfoPair()

% For each supported C++ compiler, provides:
%  - The supported compatible compiler.
%  - Whether the C++ compiler compiles .c files as C++
%  - The variable that should be used to specify options (COMPFLAGS or CXXFLAGS)
switch computer('arch')
    case 'glnxa64'
        infoPair = {...
            'g++', {'gcc', true, 'CXXFLAGS', {'-x c++'}}; ...
            };
        c2CxxCompPair = {...
            'gcc', 'g++'; ...
            };
    case 'maca64'
        infoPair = {...
            'Clang++', {'Clang', true, 'CXXFLAGS', {'-x c++'}}; ...
            };
        c2CxxCompPair = {...
            'Clang', 'Clang++'; ...
            };
    case 'maci64'
        infoPair = {...
            'Clang++', {'Clang', true, 'CXXFLAGS', {'-x c++'}}; ...
            };
        c2CxxCompPair = {...
            'Clang', 'Clang++'; ...
            };
    case 'win64'
        infoPair = {...
            'INTELCPP20MSVCPP2017', {'INTELC20MSVS2017', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP20MSVCPP2019', {'INTELC20MSVS2019', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP21MSVCPP2017', {'INTELC21MSVS2017', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP21MSVCPP2019', {'INTELC21MSVS2019', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP22MSVCPP2017', {'INTELC22MSVS2017', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP22MSVCPP2019', {'INTELC22MSVS2019', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP22MSVCPP2022', {'INTELC22MSVS2022', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP23MSVCPP2019', {'INTELC23MSVS2019', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP23MSVCPP2022', {'INTELC23MSVS2022', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP24MSVCPP2019', {'INTELC24MSVS2019', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP24MSVCPP2022', {'INTELC24MSVS2022', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP25MSVCPP2019', {'INTELC25MSVS2019', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'INTELCPP25MSVCPP2022', {'INTELC25MSVS2022', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'mingw64-g++', {'mingw64', true, 'CXXFLAGS', {'-x c++'}}; ...
            'MinGW64SDK10+', {'mingw64', true, 'CXXFLAGS', {'-x c++'}}; ...
            'MSVCPP150', {'MSVC150', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'MSVCPP160', {'MSVC160', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            'MSVCPP170', {'MSVC170', false, 'COMPFLAGS', {'/TP', '/Tp'}}; ...
            };
        c2CxxCompPair = {...
            'INTELC20MSVS2017', 'INTELCPP20MSVCPP2017'; ...
            'INTELC20MSVS2019', 'INTELCPP20MSVCPP2019'; ...
            'INTELC21MSVS2017', 'INTELCPP21MSVCPP2017'; ...
            'INTELC21MSVS2019', 'INTELCPP21MSVCPP2019'; ...
            'INTELC22MSVS2017', 'INTELCPP22MSVCPP2017'; ...
            'INTELC22MSVS2019', 'INTELCPP22MSVCPP2019'; ...
            'INTELC22MSVS2022', 'INTELCPP22MSVCPP2022'; ...
            'INTELC23MSVS2019', 'INTELCPP23MSVCPP2019'; ...
            'INTELC23MSVS2022', 'INTELCPP23MSVCPP2022'; ...
            'INTELC24MSVS2019', 'INTELCPP24MSVCPP2019'; ...
            'INTELC24MSVS2022', 'INTELCPP24MSVCPP2022'; ...
            'INTELC25MSVS2019', 'INTELCPP25MSVCPP2019'; ...
            'INTELC25MSVS2022', 'INTELCPP25MSVCPP2022'; ...
            'MSVC150', 'MSVCPP150'; ...
            'MSVC160', 'MSVCPP160'; ...
            'MSVC170', 'MSVCPP170'; ...
            'mingw64', 'mingw64-g++'; ...
            };
    otherwise
        infoPair = cell(0, 2);
        c2CxxCompPair = cell(0, 2);
end
