function initialize(this, Axes)
%INITIALIZE  Initializes @sigmaview objects.

%  Copyright 1986-2021 The MathWorks, Inc.

% Create single curve (number varies with data)
this.Curves = handle(line('XData', NaN, 'YData', NaN, ...
   'Parent', Axes, 'Visible', 'off'));
this.PosArrows = handle(patch(NaN,NaN,'w',...
   'Parent',Axes,'Visible','off',...
   'HitTest','off','HandleVisibility','off', ...
   'XlimInclude','off','YlimInclude','off'));
this.NegArrows = handle(patch(NaN,NaN,'w',...
   'Parent',Axes,'Visible','off',...
   'HitTest','off','HandleVisibility','off', ...
   'XlimInclude','off','YlimInclude','off'));
this.NyquistLine = handle(line('XData', NaN, 'YData', NaN, ...
   'Parent', Axes, 'Visible', 'off', 'HandleVisibility', 'Off', ...
   'XlimInclude','off','YlimInclude','off'));