# Copyright 2024 The MathWorks, Inc.

include $(BUILD_HARNESS)/makerules/sandbox_root.mk
include $(MAKE_INCLUDE_DIR)/module_interface.mk

SLEXPORTPREVIOUS_DIR = $(SANDBOX_ROOT)/toolbox/shared/robotics/robotslcore/slexportprevious
include $(SANDBOX_ROOT)/toolbox/simulink/slexportprevious/slexportprevious.mk
