
classdef CarlaWaypoint < ros.Message
    %CarlaWaypoint MATLAB implementation of carla_waypoint_types/CarlaWaypoint
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_waypoint_types/CarlaWaypoint' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '99235d247406855b2598c797ec698ae4' % The MD5 Checksum of the message definition
        PropertyList = { 'Pose' 'RoadId' 'SectionId' 'LaneId' 'IsJunction' } % List of non-constant message properties
        ROSPropertyList = { 'pose' 'road_id' 'section_id' 'lane_id' 'is_junction' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pose
        RoadId
        SectionId
        LaneId
        IsJunction
    end
    methods
        function set.Pose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWaypoint', 'Pose')
            obj.Pose = val;
        end
        function set.RoadId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWaypoint', 'RoadId');
            obj.RoadId = int32(val);
        end
        function set.SectionId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWaypoint', 'SectionId');
            obj.SectionId = int32(val);
        end
        function set.LaneId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWaypoint', 'LaneId');
            obj.LaneId = int32(val);
        end
        function set.IsJunction(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CarlaWaypoint', 'IsJunction');
            obj.IsJunction = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_waypoint_types.CarlaWaypoint.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_waypoint_types.CarlaWaypoint(strObj);
        end
    end
end
