
classdef GetWaypointRequest < ros.Message
    %GetWaypointRequest MATLAB implementation of carla_waypoint_types/GetWaypointRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_waypoint_types/GetWaypointRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '68ff00ebc14ac99f5a5137e25226d94e' % The MD5 Checksum of the message definition
        PropertyList = { 'Location' } % List of non-constant message properties
        ROSPropertyList = { 'location' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Point' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Location
    end
    methods
        function set.Location(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'GetWaypointRequest', 'Location')
            obj.Location = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_waypoint_types.GetWaypointRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_waypoint_types.GetWaypointRequest(strObj);
        end
    end
end
