
classdef GetWaypointResponse < ros.Message
    %GetWaypointResponse MATLAB implementation of carla_waypoint_types/GetWaypointResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_waypoint_types/GetWaypointResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1339f512e2455f75636d936d50861b4f' % The MD5 Checksum of the message definition
        PropertyList = { 'Waypoint' } % List of non-constant message properties
        ROSPropertyList = { 'waypoint' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.carla_waypoint_types.CarlaWaypoint' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Waypoint
    end
    methods
        function set.Waypoint(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.carla_waypoint_types.CarlaWaypoint'};
            validateattributes(val, validClasses, validAttributes, 'GetWaypointResponse', 'Waypoint')
            obj.Waypoint = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_waypoint_types.GetWaypointResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_waypoint_types.GetWaypointResponse(strObj);
        end
    end
end
