/*
 * Copyright 2024 The MathWorks, Inc.
 */

#ifndef _TMW_BUILTINS_ARM_32_H_
#define _TMW_BUILTINS_ARM_32_H_

#pragma tmw no_emit
#pragma tmw code_instrumentation off
#pragma tmw push(builtins)

#if defined(__ARM_32BIT_STATE)
#if GNU_GE(7) || defined(__tmw_clang__)
PST_LINK_C void __builtin_arm_cdp(unsigned,unsigned,unsigned,unsigned,unsigned,unsigned);
PST_LINK_C void __builtin_arm_cdp2(unsigned,unsigned,unsigned,unsigned,unsigned,unsigned);
#endif
#if GNU_GE2(8,2) || defined(__tmw_clang__)
PST_LINK_C void __builtin_arm_ldc(unsigned,unsigned,const void*);
PST_LINK_C void __builtin_arm_ldc2(unsigned,unsigned,const void*);
PST_LINK_C void __builtin_arm_ldc2l(unsigned,unsigned,const void*);
PST_LINK_C void __builtin_arm_ldcl(unsigned,unsigned,const void*);
PST_LINK_C void __builtin_arm_stc(unsigned,unsigned,void*);
PST_LINK_C void __builtin_arm_stc2(unsigned,unsigned,void*);
PST_LINK_C void __builtin_arm_stc2l(unsigned,unsigned,void*);
PST_LINK_C void __builtin_arm_stcl(unsigned,unsigned,void*);
#endif
#if (defined(__GNUC__) && !defined(__tmw_clang__)) || defined(__tmw_clang__)
PST_LINK_C unsigned int __builtin_arm_usadd8(unsigned int, unsigned int);
#endif

#if defined(__GNUC__) && !defined(__tmw_clang__)
#if defined(__GNUC__) && !defined(__tmw_clang__)
PST_LINK_C void __builtin_cxa_end_cleanup(void) __attribute((noreturn));
#endif
#if GNU_GE(10)
PST_LINK_C int __builtin_arm_get_fpscr_nzcvqc(void);
PST_LINK_C int __builtin_arm_qadd(int,int);
PST_LINK_C int __builtin_arm_qadd16(int,int);
PST_LINK_C int __builtin_arm_qadd8(int,int);
PST_LINK_C int __builtin_arm_qasx(int,int);
PST_LINK_C int __builtin_arm_qsax(int,int);
PST_LINK_C int __builtin_arm_qsub(int,int);
PST_LINK_C int __builtin_arm_qsub16(int,int);
PST_LINK_C int __builtin_arm_qsub8(int,int);
PST_LINK_C int __builtin_arm_sadd16(int,int);
PST_LINK_C int __builtin_arm_sadd8(int,int);
PST_LINK_C int __builtin_arm_sasx(int,int);
PST_LINK_C int __builtin_arm_saturation_occurred(void);
PST_LINK_C unsigned __builtin_arm_sel(unsigned,unsigned);
PST_LINK_C void __builtin_arm_set_fpscr_nzcvqc(int);
PST_LINK_C void __builtin_arm_set_saturation(int);
PST_LINK_C int __builtin_arm_shadd16(int,int);
PST_LINK_C int __builtin_arm_shadd8(int,int);
PST_LINK_C int __builtin_arm_shasx(int,int);
PST_LINK_C int __builtin_arm_shsax(int,int);
PST_LINK_C int __builtin_arm_shsub16(int,int);
PST_LINK_C int __builtin_arm_shsub8(int,int);
PST_LINK_C int __builtin_arm_smlabb(int,int,int);
PST_LINK_C int __builtin_arm_smlad(int,int,int);
PST_LINK_C int __builtin_arm_smladx(int,int,int);
PST_LINK_C long long __builtin_arm_smlald(int,int,long long);
PST_LINK_C long long __builtin_arm_smlaldx(int,int,long long);
PST_LINK_C int __builtin_arm_smlatb(int,int,int);
PST_LINK_C int __builtin_arm_smlatt(int,int,int);
PST_LINK_C int __builtin_arm_smlawb(int,int,int);
PST_LINK_C int __builtin_arm_smlawt(int,int,int);
PST_LINK_C int __builtin_arm_smlsd(int,int,int);
PST_LINK_C int __builtin_arm_smlsdx(int,int,int);
PST_LINK_C long long __builtin_arm_smlsld(int,int,long long);
PST_LINK_C long long __builtin_arm_smlsldx(int,int,long long);
PST_LINK_C int __builtin_arm_smuad(int,int);
PST_LINK_C int __builtin_arm_smuadx(int,int);
PST_LINK_C int __builtin_arm_smusd(int,int);
PST_LINK_C int __builtin_arm_smusdx(int,int);
PST_LINK_C int __builtin_arm_ssax(int,int);
PST_LINK_C int __builtin_arm_ssub16(int,int);
PST_LINK_C int __builtin_arm_ssub8(int,int);
PST_LINK_C int __builtin_arm_sxtab16(int,int);
PST_LINK_C int __builtin_arm_sxtb16(int);
PST_LINK_C unsigned __builtin_arm_uadd16(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uadd8(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uasx(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uhadd16(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uhadd8(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uhasx(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uhsax(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uhsub16(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uhsub8(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uqadd16(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uqadd8(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uqasx(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uqsax(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uqsub16(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uqsub8(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_usad8(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_usada8(unsigned,unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_usat(int,unsigned);
PST_LINK_C unsigned __builtin_arm_usax(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_usub16(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_usub8(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uxtab16(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_uxtb16(unsigned);
PST_LINK_C int __builtin_mve_sqrshr_si(int,int);
PST_LINK_C long long __builtin_mve_sqrshrl_sat48_di(long long,int);
PST_LINK_C long long __builtin_mve_sqrshrl_sat64_di(long long,int);
PST_LINK_C unsigned __builtin_mve_sqshl_si(unsigned long long,const int);
PST_LINK_C unsigned long long __builtin_mve_sqshll_di(unsigned long long,const int);
PST_LINK_C unsigned __builtin_mve_srshr_si(unsigned long long,const int);
PST_LINK_C unsigned long long __builtin_mve_srshrl_di(unsigned long long,const int);
PST_LINK_C unsigned __builtin_mve_uqrshl_si(unsigned,int);
PST_LINK_C unsigned long long __builtin_mve_uqrshll_sat48_di(unsigned long long,int);
PST_LINK_C unsigned long long __builtin_mve_uqrshll_sat64_di(unsigned long long,int);
PST_LINK_C unsigned __builtin_mve_uqshl_si(unsigned,const int);
PST_LINK_C unsigned long long __builtin_mve_uqshll_di(unsigned long long,const int);
PST_LINK_C unsigned __builtin_mve_urshr_si(unsigned,const int);
PST_LINK_C unsigned long long __builtin_mve_urshrl_di(unsigned long long,const int);
PST_LINK_C unsigned __builtin_mve_vdwdupq_wb_uv16qi(unsigned,unsigned long long,int);
PST_LINK_C unsigned __builtin_mve_vdwdupq_wb_uv4si(unsigned,unsigned long long,int);
PST_LINK_C unsigned __builtin_mve_vdwdupq_wb_uv8hi(unsigned,unsigned long long,int);
PST_LINK_C unsigned __builtin_mve_viwdupq_wb_uv16qi(unsigned,unsigned long long,int);
PST_LINK_C unsigned __builtin_mve_viwdupq_wb_uv4si(unsigned,unsigned long long,int);
PST_LINK_C unsigned __builtin_mve_viwdupq_wb_uv8hi(unsigned,unsigned long long,int);
PST_LINK_C void __builtin_sat_imm_check(int,int,int);
#endif
#if GNU_GE(10) && GNU_LE2(12,99)
PST_LINK_C unsigned short __builtin_mve_vctp16q_mhi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp16qhi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vctp32q_mhi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp32qhi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vctp64q_mhi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp64qhi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vctp8q_mhi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp8qhi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vpnothi(unsigned short);
#endif
#if GNU_GE(10) && GNU_LE2(13,1)
PST_LINK_C unsigned __builtin_arm_ssat(int,unsigned);
PST_LINK_C unsigned __builtin_arm_ssat16(int,unsigned);
PST_LINK_C unsigned __builtin_arm_usat16(int,unsigned);
#endif
#if GNU_GE(13)
PST_LINK_C unsigned short __builtin_mve_vctp16q_mv8bi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp16qv8bi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vctp32q_mv4bi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp32qv4bi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vctp64q_mv2qi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp64qv2qi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vctp8q_mv16bi(unsigned,unsigned short);
PST_LINK_C unsigned short __builtin_mve_vctp8qv16bi(unsigned);
PST_LINK_C unsigned short __builtin_mve_vpnotv16bi(unsigned short);
#endif
#if GNU_GE2(13,2)
PST_LINK_C int __builtin_arm_ssat(int,unsigned);
PST_LINK_C int __builtin_arm_ssat16(int,unsigned);
PST_LINK_C int __builtin_arm_usat16(int,unsigned);
#endif
#if GNU_GE(14)
PST_LINK_C unsigned __builtin_arm_rbit(unsigned);
PST_LINK_C unsigned __builtin_arm_rev16si2(unsigned);
#endif
#if (GNU_GE(5) && GNU_LE2(5,4)) || (GNU_GE(6) && GNU_LE2(6,3)) || (GNU_GE(7) && GNU_LE2(7,1))
PST_LINK_C unsigned __builtin_arm_ldfscr(void);
PST_LINK_C void __builtin_arm_stfscr(unsigned);
#endif
#if GNU_GE(5) && GNU_LE2(9,99)
PST_LINK_C __edg_vector_type__(unsigned char,16) __builtin_arm_crypto_aesd(__edg_vector_type__(unsigned char,16),__edg_vector_type__(unsigned char,16));
PST_LINK_C __edg_vector_type__(unsigned char,16) __builtin_arm_crypto_aese(__edg_vector_type__(unsigned char,16),__edg_vector_type__(unsigned char,16));
PST_LINK_C __edg_vector_type__(unsigned char,16) __builtin_arm_crypto_aesimc(__edg_vector_type__(unsigned char,16));
PST_LINK_C __edg_vector_type__(unsigned char,16) __builtin_arm_crypto_aesmc(__edg_vector_type__(unsigned char,16));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha1c(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha1h(__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha1m(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha1p(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha1su0(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha1su1(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha256h(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha256h2(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha256su0(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
PST_LINK_C __edg_vector_type__(unsigned,4) __builtin_arm_crypto_sha256su1(__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4),__edg_vector_type__(unsigned,4));
#endif
#if (GNU_GE2(5,5) && GNU_LE2(5,99)) || (GNU_GE2(6,4) && GNU_LE2(6,99)) || GNU_GE2(7,2)
PST_LINK_C unsigned __builtin_arm_get_fpscr(void);
PST_LINK_C void __builtin_arm_set_fpscr(unsigned);
#endif
#if GNU_GE(6)
PST_LINK_C void __builtin_arm_lane_check(int,int);
#endif
#if GNU_GE(7)
PST_LINK_C unsigned __builtin_arm_crc32b(unsigned,unsigned char);
PST_LINK_C unsigned __builtin_arm_crc32cb(unsigned,unsigned char);
PST_LINK_C unsigned __builtin_arm_crc32ch(unsigned,unsigned short);
PST_LINK_C unsigned __builtin_arm_crc32cw(unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_crc32h(unsigned,unsigned short);
PST_LINK_C unsigned __builtin_arm_crc32w(unsigned,unsigned);
PST_LINK_C void __builtin_arm_mcr(unsigned,unsigned,int,unsigned,unsigned,unsigned);
PST_LINK_C void __builtin_arm_mcr2(unsigned,unsigned,int,unsigned,unsigned,unsigned);
PST_LINK_C void __builtin_arm_mcrr(unsigned,unsigned,long long,unsigned);
PST_LINK_C void __builtin_arm_mcrr2(unsigned,unsigned,long long,unsigned);
PST_LINK_C int __builtin_arm_mrc(unsigned,unsigned,unsigned,unsigned,unsigned);
PST_LINK_C int __builtin_arm_mrc2(unsigned,unsigned,unsigned,unsigned,unsigned);
PST_LINK_C long long __builtin_arm_mrrc(unsigned,unsigned,unsigned);
PST_LINK_C long long __builtin_arm_mrrc2(unsigned,unsigned,unsigned);
#endif
#if GNU_GE(7) && GNU_LE2(8,1)
PST_LINK_C void __builtin_arm_ldc(unsigned,unsigned,const int*);
PST_LINK_C void __builtin_arm_ldc2(unsigned,unsigned,const int*);
PST_LINK_C void __builtin_arm_ldc2l(unsigned,unsigned,const int*);
PST_LINK_C void __builtin_arm_ldcl(unsigned,unsigned,const int*);
PST_LINK_C void __builtin_arm_stc(unsigned,unsigned,int*);
PST_LINK_C void __builtin_arm_stc2(unsigned,unsigned,int*);
PST_LINK_C void __builtin_arm_stc2l(unsigned,unsigned,int*);
PST_LINK_C void __builtin_arm_stcl(unsigned,unsigned,int*);
#endif
#endif /* __GNUC__ && !__tmw_clang__ */

#ifdef __tmw_clang__
#if defined(__tmw_clang__)
PST_LINK_C unsigned __builtin_arm_crc32cd(unsigned,unsigned long long) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_crc32d(unsigned,unsigned long long) __edg_throw__();
PST_LINK_C void __builtin_arm_dbg(unsigned);
PST_LINK_C unsigned __builtin_arm_get_fpscr(void) __edg_throw__();
PST_LINK_C unsigned long long __builtin_arm_ldrexd(void*);
PST_LINK_C void __builtin_arm_mcr(unsigned,unsigned,unsigned,unsigned,unsigned,unsigned);
PST_LINK_C void __builtin_arm_mcr2(unsigned,unsigned,unsigned,unsigned,unsigned,unsigned);
PST_LINK_C void __builtin_arm_mcrr(unsigned,unsigned,unsigned long long,unsigned);
PST_LINK_C void __builtin_arm_mcrr2(unsigned,unsigned,unsigned long long,unsigned);
PST_LINK_C unsigned __builtin_arm_mrc(unsigned,unsigned,unsigned,unsigned,unsigned);
PST_LINK_C unsigned __builtin_arm_mrc2(unsigned,unsigned,unsigned,unsigned,unsigned);
PST_LINK_C unsigned long long __builtin_arm_mrrc(unsigned,unsigned,unsigned);
PST_LINK_C unsigned long long __builtin_arm_mrrc2(unsigned,unsigned,unsigned);
PST_LINK_C void __builtin_arm_prefetch(const void*,unsigned,unsigned) __edg_throw__();
PST_LINK_C int __builtin_arm_qadd(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_qadd16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_qadd8(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_qasx(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_qdbl(int) __edg_throw__();
PST_LINK_C int __builtin_arm_qsax(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_qsub(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_qsub16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_qsub8(int,int) __edg_throw__();
PST_LINK_C unsigned long long __builtin_arm_rsr64(const char*) __edg_throw__();
PST_LINK_C int __builtin_arm_sadd16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_sadd8(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_sasx(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_sel(int,int) __edg_throw__();
PST_LINK_C void __builtin_arm_set_fpscr(unsigned) __edg_throw__();
PST_LINK_C int __builtin_arm_shadd16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_shadd8(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_shasx(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_shsax(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_shsub16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_shsub8(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlabb(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlabt(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlad(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smladx(int,int,int) __edg_throw__();
PST_LINK_C long long __builtin_arm_smlald(int,int,long long) __edg_throw__();
PST_LINK_C long long __builtin_arm_smlaldx(int,int,long long) __edg_throw__();
PST_LINK_C int __builtin_arm_smlatb(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlatt(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlawb(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlawt(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlsd(int,int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smlsdx(int,int,int) __edg_throw__();
PST_LINK_C long long __builtin_arm_smlsld(int,int,long long) __edg_throw__();
PST_LINK_C long long __builtin_arm_smlsldx(int,int,long long) __edg_throw__();
PST_LINK_C int __builtin_arm_smuad(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smuadx(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smulbb(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smulbt(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smultb(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smultt(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smulwb(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smulwt(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smusd(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_smusdx(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_ssat(int,unsigned) __edg_throw__();
PST_LINK_C int __builtin_arm_ssat16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_ssax(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_ssub16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_ssub8(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_strexd(unsigned long long,void*);
PST_LINK_C int __builtin_arm_sxtab16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_sxtb16(int) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uadd16(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uadd8(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uasx(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uhadd16(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uhadd8(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uhasx(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uhsax(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uhsub16(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uhsub8(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uqadd16(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uqadd8(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uqasx(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uqsax(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uqsub16(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_uqsub8(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_usad8(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_usada8(unsigned,unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_usat(int,unsigned) __edg_throw__();
PST_LINK_C int __builtin_arm_usat16(int,int) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_usax(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_usub16(unsigned,unsigned) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_usub8(unsigned,unsigned) __edg_throw__();
PST_LINK_C int __builtin_arm_uxtab16(int,int) __edg_throw__();
PST_LINK_C int __builtin_arm_uxtb16(int) __edg_throw__();
PST_LINK_C float __builtin_arm_vcvtr_d(double,int) __edg_throw__();
PST_LINK_C float __builtin_arm_vcvtr_f(float,int) __edg_throw__();
PST_LINK_C void __builtin_arm_wsr64(const char*,unsigned long long) __edg_throw__();
#endif
#if CLANG_GE(10)
PST_LINK_C unsigned __builtin_arm_cls64(unsigned long long) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_cmse_TT(void*) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_cmse_TTA(void*) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_cmse_TTAT(void*) __edg_throw__();
PST_LINK_C unsigned __builtin_arm_cmse_TTT(void*) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vabavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vabavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vabdq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vabdq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vabdq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vadciq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vadciq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vadcq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vadcq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vandq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vandq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vandq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vbicq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vbicq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vbicq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcaddq_rot270(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcaddq_rot270_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcaddq_rot270_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcaddq_rot90(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcaddq_rot90_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcaddq_rot90_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq_rot180(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq_rot180_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq_rot270(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq_rot270_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq_rot90(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmlaq_rot90_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpcsq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpcsq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpeqq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpeqq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpgeq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpgeq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpgtq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpgtq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmphiq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmphiq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpleq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpleq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpltq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpltq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpneq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmpneq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot180(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot180_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot180_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot270(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot270_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot270_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot90(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot90_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_rot90_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcmulq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_veorq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_veorq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_veorq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vgetq_lane(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhaddq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhaddq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhaddq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhcaddq_rot270(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhcaddq_rot270_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhcaddq_rot270_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhcaddq_rot90(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhcaddq_rot90_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhcaddq_rot90_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhsubq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhsubq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vhsubq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vld1q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vld1q_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vld2q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vld4q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrbq_gather_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrbq_gather_offset_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrdq_gather_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrdq_gather_offset_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrdq_gather_shifted_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrdq_gather_shifted_offset_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrhq_gather_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrhq_gather_offset_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrhq_gather_shifted_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrhq_gather_shifted_offset_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrwq_gather_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrwq_gather_offset_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrwq_gather_shifted_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vldrwq_gather_shifted_offset_z(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxvq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminvq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavaxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavaxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmladavxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavaxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavaxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaldavxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavaxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavaxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsdavxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavaxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavaxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlsldavxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulhq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmullbq_int(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmullbq_int_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmullbq_int_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmullbq_poly(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmullbq_poly_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmullbq_poly_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulltq_int(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulltq_int_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulltq_int_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulltq_poly(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulltq_poly_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulltq_poly_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmulq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vornq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vornq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vornq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vorrq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vorrq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vorrq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vpselq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqaddq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqaddq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmulhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmulhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmulhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmulhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshlq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshlq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshlq_m_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshrnbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshrnbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshrntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshrntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshrunbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshrunbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshruntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrshruntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshlq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshlq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshlq_m_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshlq_m_r(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshlq_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshlq_r(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshluq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshluq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshrnbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshrnbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshrntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshrntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshrunbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshrunbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshruntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqshruntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqsubq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqsubq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_f16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_f32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_s16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_s32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_s64(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_s8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_u64(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vreinterpretq_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrhaddq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrhaddq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrhaddq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhaxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhaxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlaldavhxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhaxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhaxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmlsldavhxq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmulhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmulhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrmulhq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshlq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshlq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshlq_m_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshlq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshrnbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshrnbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshrntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshrntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshrq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshrq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrshrq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsetq_lane(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshllbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshllbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshllbq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlltq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlltq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlltq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq_m_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq_m_r(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq_r(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlq_x_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshrnbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshrnbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshrntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshrntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshrq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshrq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshrq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsliq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsliq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsriq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsriq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vst1q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vst1q_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vst2q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vst4q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrbq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrbq_scatter_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrbq_scatter_offset_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_base(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_base_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_base_wb(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_base_wb_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_offset_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_shifted_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrdq_scatter_shifted_offset_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrhq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrhq_scatter_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrhq_scatter_offset_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrhq_scatter_shifted_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrhq_scatter_shifted_offset_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_base(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_base_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_base_wb(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_base_wb_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_offset_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_shifted_offset(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vstrwq_scatter_shifted_offset_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsubq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsubq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsubq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vuninitializedq(int,...) __edg_throw__();
#endif
#if CLANG_GE(11)
PST_LINK_C void __builtin_arm_mve_vabsq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vabsq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vabsq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddlvaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddlvaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddlvq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddlvq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddvaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddvaq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddvq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vaddvq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vbicq_m_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vbrsrq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vbrsrq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vbrsrq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vclsq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vclsq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vclsq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vclzq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vclzq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vclzq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtmq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtnq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtpq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtq_m_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtq_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vcvtq_x_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vddupq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vddupq_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vddupq_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vddupq_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vddupq_x_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vddupq_x_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vddupq_x_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdupq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdwdupq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdwdupq_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdwdupq_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdwdupq_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdwdupq_x_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdwdupq_x_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vdwdupq_x_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vfmaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vfmaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vfmasq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vfmasq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vfmsq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vfmsq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vidupq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vidupq_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vidupq_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vidupq_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vidupq_x_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vidupq_x_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vidupq_x_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_viwdupq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_viwdupq_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_viwdupq_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_viwdupq_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_viwdupq_x_u16(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_viwdupq_x_u32(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_viwdupq_x_u8(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmvq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxnmvq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmaxvq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmavq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmavq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmvq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminnmvq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vminvq_p(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlasq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmlasq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovlbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovlbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovlbq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovltq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovltq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovltq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovnbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovnbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmovntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmvnq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmvnq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vmvnq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vnegq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vnegq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vnegq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vorrq_m_n(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqabsq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqabsq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmladhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmladhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmladhxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmladhxq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlahq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlahq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlashq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlashq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlsdhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlsdhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlsdhxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmlsdhxq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmullbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmullbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmulltq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqdmulltq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovnbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovnbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovunbq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovunbq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovuntq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqmovuntq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqnegq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqnegq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmladhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmladhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmladhxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmladhxq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlahq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlahq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlashq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlashq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlsdhq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlsdhq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlsdhxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vqrdmlsdhxq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev16q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev16q_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev16q_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev32q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev32q_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev32q_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev64q(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev64q_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrev64q_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndaq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndaq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndaq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndmq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndmq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndmq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndnq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndnq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndnq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndpq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndpq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndpq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndxq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndxq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vrndxq_x(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsbciq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsbciq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsbcq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vsbcq_m(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlcq(int,...) __edg_throw__();
PST_LINK_C void __builtin_arm_mve_vshlcq_m(int,...) __edg_throw__();
#endif
#if CLANG_GE(17)
PST_LINK_C unsigned __builtin_arm_clz64(unsigned long long) __edg_throw__();
#endif
#endif /* __tmw_clang__ */

#endif /* defined(__ARM_32BIT_STATE) */

#pragma tmw pop(builtins)
#pragma tmw code_instrumentation on
#pragma tmw emit

#endif /* _TMW_BUILTINS_ARM_32_H_ */
