%Tracer Specifies options for tracing execution of a stylesheet
%   An instance of this object is returned when you access the Tracer
%   property of an matlab.io.xml.transform.Transformer object. Use this
%   object to specify options used to trace execution of a stylesheet.
%
%   Tracer properties:
%       Enable          - Whether to enable tracing
%       OutputPath      - Path of file used to store trace output
%       TraceTemplates  - Whether to trace stylesheet template execution
%       TraceElements   - Whether to trace stylesheet element execution
%       TraceGeneration - Whether to trace stylesheet output
%       TraceSelection  - Whether to trace stylesheet selection results
%
%
%   See also matlab.io.xml.transform.Transformer.Tracer

%    Copyright 2021 MathWorks, Inc.
%    Built-in class

%{
properties
     %Enable Whether to trace execution of a stylesheet
     %    If this property is false (default), tracing is not performed.
     Enable;

     %OutputPath Path of file to be used to store trace output messages
     %    Path of file to be used to store trace output messages. If this
     %    property is empty (the default), trace messages appear in the
     %    MATLAB command window.
     OuputPath;

     %TraceTemplates Whether to trace stylesheet template execution
     %    If this property is true, the transformer emits a message that
     %    identifies the stylesheet template that it is currently
     %    executing. This property is false by default.
     TraceTemplates;

     %TraceElements Whether to trace stylesheet element execution
     %    If this property is true, the transformer emits a message that
     %    identifies the stylesheet element that it is currently executing.
     %    This property is false by default.
     TraceElements;

     %TraceSelection Whether to trace stylesheet selection results
     %    If this property is true, the transformer emits a message that
     %    identifies the result of executing a stylesheet select 
     %    expression. This property is false by default.
     TraceSelection;

     %TraceGeneration Whether to trace stylesheet output
     %    If this property is true, the transformer emits a message that
     %    specifies an output generated by a stylesheet execution. This
     %    property is false by default.
     TraceGeneration;

end
%}


