classdef WebUIAxesController  < matlab.ui.internal.controller.WebCanvasContainerController
    %
    
    %   Copyright 2015-2022 The MathWorks, Inc.
    
    properties
        
        % String properties that require no specific handling to / from
        % view.
        %
        % All of these will be forwarded as is back and forth during
        % initialization and edits.
        GenericStringProperties = {...
            'ALimMode',...
            'AlphaScale',...
            'Box', ...
            'BoxStyle',...
            'ButtonDownFcn',...
            'Clipping',...
            'ClippingStyle',...
            'ContextMenuID', ...
            'ColorScale',...
            'Layer', ...
            'DataAspectRatioMode', ...
            'CameraPositionMode',...
            'CameraTargetMode',...
            'CameraViewAngleMode',...
            'Projection',...
            'SortMethod',...
            'CameraUpVectorMode',...
            'PlotBoxAspectRatioMode', ...
            'XColorMode', ...
            'YColorMode', ...
            'ZColorMode', ...
            'CLimMode', ...
            'GridAlphaMode',...
            'MinorGridAlphaMode',...
            'XAxisLocation', ...
            'XScale',...
            'XDir', ...
            'XLimMode', ...
            'XLimitMethod', ...
            'YAxisLocation', ...
            'YScale',...
            'YDir', ...
            'YLimMode', ...
            'YLimitMethod', ...
            'ZDir', ...
            'ZLimMode', ...
            'ZLimitMethod', ...
            'ZScale',...
            'GridColorMode', ...
            'GridLineStyle', ...
            'MinorGridColorMode', ...
            'MinorGridLineStyle',...
            'XGrid', ...
            'XMinorGrid', ...
            'YGrid', ...
            'YMinorGrid', ...
            'ZGrid', ...
            'ZMinorGrid', ...
            'LineStyleOrder', ...
            'LineStyleCyclingMethod', ...
            'NextPlot', ...
            'TickDir', ...
            'TickDirMode', ...
            'TickLabelInterpreter',...
            'XMinorTick', ...
            'XTickMode', ...
            'XTickLabelMode', ...
            'YMinorTick', ...
            'YTickMode', ...
            'YTickLabelMode', ...
            'ZMinorTick',...
            'ZTickMode', ...
            'ZTickLabelMode', ...
            'FontName', ...
            'FontWeight', ...
            'PickableParts',...
            'HitTest',...
            'FontAngle', ...
            'FontUnits', ...
            'FontSmoothing',...
            'FontSizeMode',...
            'SubtitleFontWeight',...
            'TitleFontWeight',...
            'Visible', ...
            'HandleVisibility', ...
            'BusyAction', ...
            'Interruptible', ...
            'Tag', ...
            'TitleHorizontalAlignment', ...
            'XTickLabelRotationMode', ...
            'YTickLabelRotationMode', ...
            'ZTickLabelRotationMode' ...
            }
        
        GenericNumericProperties = {
            'ALim',...
            'Alphamap',...
            'LabelFontSizeMultiplier',...
            'CameraPosition',...
            'PositionConstraint',...
            'CameraTarget',...
            'CameraViewAngle',...
            'View',...
            'CameraUpVector',...
            'LineWidth', ...
            'DataAspectRatio', ...
            'PlotBoxAspectRatio', ...
            'ColorOrderIndex', ...
            'CLim', ...
            'XLim', ...
            'YLim', ...
            'ZLim', ...
            'GridAlpha', ...
            'GridLineWidth', ...
            'MinorGridAlpha', ...
            'MinorGridLineWidth', ...
            'LineStyleOrderIndex', ...
            'TickLength', ...
            'XTick', ...
            'XTickLabelRotation', ...
            'YTick', ...
            'YTickLabelRotation', ...
            'ZTick', ...
            'ZTickLabelRotation',...
            'TitleFontSizeMultiplier',...
            ... Color - related numerics
            'AmbientLightColor',...
            'Color', ...
            'Colormap', ...
            'ColorOrder', ...
            'GridColor', ...
            'MinorGridColor', ...
            'XColor', ...
            'YColor', ...
            'ZColor' ...
            }
        
    end
    
    properties(Access = 'protected')
        positionBehavior
        layoutBehavior
    end
    
    
    methods
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Constructor
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function this = WebUIAxesController( model, varargin  )
            
            % Super constructor
            this = this@matlab.ui.internal.controller.WebCanvasContainerController( model, varargin{:} );
            this.positionBehavior = matlab.ui.internal.componentframework.services.optional.PositionBehaviorAddOn(this.PropertyManagementService);
            this.layoutBehavior = matlab.ui.internal.componentframework.services.optional.LayoutBehaviorAddOn(this.PropertyManagementService);
            
        end
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      updateFontSize
        %
        %  Description: Custom method to set newFontSize.
        %
        %  Inputs :     this
        %  Outputs:     newFontSize struct-> on the Web Panel peernode
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function newFontSize = updateFontSize(this)
            newFontSize = '';
            % using try catch as this is special case for the charts
            % as charts does not have the FontUnits property which need to be
            % ignored, need to investigate and come up with better option of
            % using the WebPanelController for the charts
            try
                value = struct('FontSize', this.Model.FontSize, 'FontUnits', this.Model.FontUnits);
                newFontSize = value;
            catch e %#ok<NASGU>
                
            end
        end
        
        function constraintsStruct = updateLayoutConstraints(obj)
            constraintsStruct = obj.layoutBehavior.updateLayout(obj.Model.Layout);
        end
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      updatePosition
        %
        %  Description: Method invoked when position changes.
        %
        %  Inputs :     None.
        %  Outputs:
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function newPosValue = updatePosition( obj )
            oneOriginPosValue = obj.Model.Position;
            newPosValue = obj.positionBehavior.updatePositionInPixels(oneOriginPosValue);
        end
        
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      updateAxesVisible
        %
        %  Description: Custom method to set the Visible property on the
        %  contained Axes rather than set Visible on the whole component
        %  (as is the case with other UI components)
        %
        %  Inputs :     this
        %  Outputs:     newVisible state sent to the peer node.
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function newVisible = updateAxesVisible(this)
            newVisible = this.Model.Visible;
            this.Model.Axes.Visible = this.Model.Visible;
        end
        
    end
    
    methods( Access = 'protected' )
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      defineViewProperties
        %
        %  Description: Within the context of MVC ( Model-View-Controller )
        %               software paradigm, this is the method the "Controller"
        %               layer uses to define which properties will be consumed by
        %               the web-based user interface.
        %  Inputs:      None
        %  Outputs:     None
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function defineViewProperties( this )
            %Properties needs no mapping/updates before updating to view
            this.PropertyManagementService.defineViewProperty( 'Title' );
            this.PropertyManagementService.defineViewProperty( 'BackgroundColor' );
            this.PropertyManagementService.defineViewProperty( 'FontSize' );
            
            this.PropertyManagementService.defineViewProperty( 'XTickLabel' );
            this.PropertyManagementService.defineViewProperty( 'YTickLabel' );
            this.PropertyManagementService.defineViewProperty( 'ZTickLabel' );
            
            for idx = 1:length(this.GenericStringProperties)
                this.PropertyManagementService.defineViewProperty(this.GenericStringProperties{idx});
            end
            
            for idx = 1:length(this.GenericNumericProperties)
                this.PropertyManagementService.defineViewProperty(this.GenericNumericProperties{idx});
            end
            
            defineViewProperties@matlab.ui.internal.controller.WebCanvasContainerController(this);
        end
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      definePropertyDependencies
        %  Description: Within the context of MVC ( Model-View-Controller )
        %               software paradigm, this is the method the "Controller"
        %               layer uses to establish property dependencies between
        %               a property (or set of properties) defined by the "Model"
        %               layer and dependent "View" layer property.
        %  Inputs:      None
        %  Outputs:     None
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function definePropertyDependencies( this )
        end

        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        %  Method:      defineRequireUpdateProperties
        %  Description: Within the context of MVC ( Model-View-Controller )
        %               software paradigm, this is the method the "Controller"
        %               layer uses to establish property which needs updates
        %               before updating them to view. E.g. Position or FontSize
        %  Inputs:      None
        %  Outputs:     None
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function defineRequireUpdateProperties( this )
            this.PropertyManagementService.defineRequireUpdateProperty('FontSize');
        end
        
        function handleEvent( this, src, event )
            
            if( this.EventHandlingService.isClientEvent( event ) )
                                
                % Defer to the base class for common event processing
                handleEvent@matlab.ui.internal.controller.WebCanvasContainerController( this, src, event );
            end
        end
    end
end