
% Compression - specifies a scheme to compress the image data
%    These enumerated values should only be used when setting the
%    'Compression' tag.  Available compression schemes include
%
%       None
%       CCITTRLE     - read-only
%       CCITTFax3
%       CCITTFax4
%       LZW
%       JPEG
%       CCITTRLEW    - read-only
%       PackBits
%       SGILog
%       SGILog24
%       Deflate
%       AdobeDeflate - same as Deflate

% Copyright 2018 The MathWorks, Inc.

classdef Compression <uint32
    enumeration 
        None(1),...
        CCITTRLE(2),...
        CCITTFax3(3),...
        CCITTFax4(4),...
        LZW(5),...
        OJPEG(6),...
        JPEG(7),...
        AdobeDeflate(8), ...
        Next(32766), ...
        CCITTRLEW(32771),...
        PackBits(32773),...
        Thunderscan(32809), ...
        IT8CTPad(32895), ...
        IT8LW(32896), ...
        IT8MP(32897), ...
        IT8BL(32898), ...
        PixarFilm(32908), ...
        PixarLog(32909), ...
        Deflate(32946), ...
        DCS(32947), ...
        JBIG(34661), ...
        SGILog(34676), ...
        SGILog24(34677), ...
        JPEG2000(34712)
    end
end
