% Photometric - specifies the color space of the image data
%    This property should only be used when setting the
%    'Photometric' tag.  Supported photometric
%    interpretation schemes include
%
%       MinIsWhite
%       MinIsBlack
%       RGB
%       Palette
%       Mask
%       Separated (CMYK)
%       YCbCr
%       CIELab
%       ICCLab
%       ITULab
%       LogL
%       LogLuv
%       CFA
%       LinearRaw

% Copyright 2018 The MathWorks, Inc.
classdef Photometric < uint32
    enumeration
        MinIsWhite(0),...
            MinIsBlack(1), ...
            RGB(2), ...
            Palette(3), ...
            Mask(4), ...
            Separated(5), ...
            YCbCr(6), ...
            CIELab (8), ...
            ICCLab(9), ...
            ITULab(10), ...
            CFA(32803), ...
            LogL(32844), ...
            LogLuv(32845), ...
            LinearRaw(34892)
    end
end
