classdef HwMgrClientIconRepository < matlabshared.testmeasapps.internal.themeableiconrepository.IconRepository
    %HWMGRCLIENTICONREPOSITORY is the specialized icon-repository class for
    %all hardware manager client apps.
    %% NOTE -
    % Use this icon repository class for icons that are shipping with base
    % MATLAB (like standalone hardware manager icons) that MUST NOT -
    %
    % 1. Require toolbox to be installed
    %
    % 2. Check out a toolbox license.

    % Copyright 2023 The MathWorks, Inc.

    %% Implementing abstract properties of IconRepository
    properties (Constant)

        % A dictionary of Icon ID and corresponding icon id (new-style)

        IconDictionary = dictionary(...
            ... % ICT Device Descriptor and Device Card Icons
            "SerialDeviceCard", "serialDeviceCardWide", ...
            "TCPClientDeviceCard", "tcpipDeviceCardWide", ...
            "UDPDeviceCard", "udpDeviceCardWide", ...
            "VisaDeviceCard", "visaDeviceCardWide", ...
            ...
            ... % Icon IDs for Device Descriptors
            "SerialDeviceCard_Descriptor", "serialDeviceCardWide", ...
            "TCPClientDeviceCard_Descriptor", "tcpipDeviceCardWide", ...
            "UDPDeviceCard_Descriptor", "udpDeviceCardWide", ...
            "VisaDeviceCard_Descriptor", "visaDeviceCardWide", ...
            ...
            ... % IMAQ Device Card Icons
            "KinectDeviceCard", "kinectWide", ...
            "WebcamDeviceCard", "webcamRoundWide", ...
            "CameraDeviceCard", "shootingCameraWide" ...
            ...
            ... % Other Toolboxes - TO BE IMPLEMENTED
            )
    end
    
end