function GridOptions = gridopts(GridType)
%GRIDOPTS  Returns template for specifying grid options.
%
%    OPTSTRUCT = GRIDOPTS(GRIDTYPE) where GRIDTYPE can be one of
%    the following: 'pzmap', 'nichols', or 'nyquist'.

%   Author(s): P. Gahinet
%   Copyright 1986-2010 The MathWorks, Inc. 

switch GridType
case 'pzmap'
   % Pole/zero grids
   GridOptions = struct(...
      'Damping',NaN,...
      'Frequency',NaN,...
      'FrequencyUnits','rad/s',...
      'TimeUnits','seconds',...
      'GridLabelType','damping',...
      'SampleTime',-1,...
      'LimInclude','off',...
      'Zlevel',0);
   
case 'nichols'
   % Nichols chart
   GridOptions = struct(...
      'PhaseUnits','deg',...
      'MagUnits','dB',...
      'LimInclude','off',...
      'Zlevel',0);
   
case 'nyquist'
   % Nyquist grid
   GridOptions = struct(...
      'FrequencyUnits','rad/s',...
      'MagnitudeUnits','dB',...
      'Zlevel',0);
   
end