
classdef EgoVehicleControlCurrent < ros.Message
    %EgoVehicleControlCurrent MATLAB implementation of carla_ackermann_msgs/EgoVehicleControlCurrent
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'carla_ackermann_msgs/EgoVehicleControlCurrent' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f4947f35d6b5f0274303e776e887cd4b' % The MD5 Checksum of the message definition
        PropertyList = { 'TimeSec' 'Speed' 'SpeedAbs' 'Accel' } % List of non-constant message properties
        ROSPropertyList = { 'time_sec' 'speed' 'speed_abs' 'accel' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        TimeSec
        Speed
        SpeedAbs
        Accel
    end
    methods
        function set.TimeSec(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'EgoVehicleControlCurrent', 'TimeSec');
            obj.TimeSec = single(val);
        end
        function set.Speed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'EgoVehicleControlCurrent', 'Speed');
            obj.Speed = single(val);
        end
        function set.SpeedAbs(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'EgoVehicleControlCurrent', 'SpeedAbs');
            obj.SpeedAbs = single(val);
        end
        function set.Accel(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'EgoVehicleControlCurrent', 'Accel');
            obj.Accel = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.carla_ackermann_msgs.EgoVehicleControlCurrent.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.carla_ackermann_msgs.EgoVehicleControlCurrent(strObj);
        end
    end
end
