% mlreportgen.ppt
%
%   Use the following classes and functions to create and format PowerPoint
%   presentations.
%
%
% Content Classes
% ---------------
%
%   ContentPlaceholder          - Slide placeholder to replace with content
%   ExternalLink                - Hyperlink to location outside of presentation
%   InternalLink                - Hyperlink to a slide in presentation
%   Number                      - Number to include in a presentation
%   Paragraph                   - Formatted block of text (paragraph)
%   Picture                     - Picture to include in a presentation
%   PicturePlaceholder          - Slide placeholder to replace with picture
%   Presentation                - Create a PPT presentation
%   Slide                       - Presentation slide
%   Table                       - Table to include in a presentation
%   TableEntry                  - Table entry to include in a table row
%   TablePlaceholder            - Slide placeholder to replace with table
%   TableRow                    - Row to include in a table
%   TemplatePicture             - Picture from the template presentation
%   TemplateTable               - Table from the template presentation
%   Text                        - Text to include in a presentation
%   TextBox                     - Text box to include in a presentation
%   TextBoxPlaceholder          - Slide placeholder to replace with text
%
% Format Classes
% --------------
%
%   AutoFit                     - Scale text to fit placeholder or text box
%   BackgroundColor             - Background color of presentation element
%   Bold                        - Bold text
%   Border                      - Border of a table or table entry
%   ColSep                      - Table column separators
%   ColSpec                     - Formatting for table column
%   ColWidth                    - Table column width
%   FlowDirection               - Table column flow direction
%   FontColor                   - Font color
%   FontFamily                  - Font family
%   FontSize                    - Font size
%   HAlign                      - Horizontal alignment of paragraph
%   Italic                      - Italic text
%   NumberFormat                - Number formatting
%   RowHeight                   - Table row height
%   RowSep                      - Table row separators
%   Strike                      - Strike through text
%   Subscript                   - Subscript text
%   Superscript                 - Superscript text
%   TableStyleOptions           - Emphasize a table's rows or columns
%   TextOrientation             - Orientation of text in a table entry
%   Underline                   - Underline text
%   VAlign                      - Vertical alignment of table entry content
%
% Package Functions
% -----------------
%
%   getDefaultNumberFormat      - Get default formatting for numeric data generated by PPT API
%   setDefaultNumberFormat      - Set default formatting of numeric data generated by PPT API
%__________________________________________________________________________

%   Copyright 2019-2024 The MathWorks, Inc.
