//>>built
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(h){return{dynamic:0,normalize:function(b){return b},load:h.require}})},"xstyle/core/load-css":function(){define([],function(){function h(c){if(g.createStyleSheet){var a=g.createStyleSheet();a.cssText=c;return a.owningElement}a=g.createElement("style");a.setAttribute("type","text/css");a.appendChild(g.createTextNode(c));e.insertBefore(a,e.firstChild);return a}function b(c,a,n){var d=w[c];if(d)return f=h(d),a(f);var f=g.createElement("link");
f.type="text/css";f.rel="stylesheet";f.href=c;var x=!n||!1!==n.wait;n=(n=navigator.userAgent.match(/AppleWebKit\/(\d+\.?\d*)/))&&+n[1];if(null===f.onload&&!(536>n))f.onload=function(){f.onload=null;f.onerror=null;x&&a(f)},f.onerror=function(){console.error("Error loading stylesheet "+c);x&&a(f)};else if(x)var B=setInterval(function(){f.style&&(clearInterval(B),a(f))},15);(e||g.getElementsByTagName("head")[0]).appendChild(f);x||a(f)}var w="undefined"==typeof _css_cache?{}:_css_cache,g=document,e=g.head;
b.insertCss=h;return b})},"dijit/main":function(){define(["dojo/_base/kernel"],function(h){return h.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],function(h){return h.dojox})},"mw-browser-utils/BrowserCheck":function(){define("dojo/_base/window dojo/window dojo/dom-construct dojo/has dojo/i18n!./l10n/nls/unsupportedErrorPage ./detect/css ./detect/object".split(" "),function(h,b,w,g,e){var c={isBrowserValid:function(){var a=!0;g("quirks")?a=!1:g("css-enabled")?g("css-border-radius")?
g("css-text-overflow")?g("object-create")||(a=!1):a=!1:a=!1:a=!1;return a},displayErrorAsOverlay:function(){w.create("div",{style:{position:"absolute",left:"0%",top:"0%","background-color":"grey","-moz-opacity":"0.7",opacity:".70",filter:"alpha(opacity\x3d70)",width:"100%",height:"100%",zIndex:"90"},id:"fadeDiv"},h.body());w.create("div",{style:{position:"relative",margin:"auto","margin-top":"12.35%",width:"400px",height:"300px",padding:"10px",border:"2px solid black","background-color":"#ffffff",
"z-index":"100","font-family":"Sans-serif"},id:"unsupportedBrowser","class":"content_module"},h.body()).innerHTML=e.unsupportedError}};return{load:function(a,n,d){c.isBrowserValid()?d():a?h.global.location=a:c.displayErrorAsOverlay()}}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(h,b,w,g,e,c,a){b.add("rtl-adjust-position-for-verticalScrollBar",function(d,f){d=w.body(f);f=a.create("div",{style:{overflow:"scroll",
overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},d,"last");var x=a.create("div",{style:{overflow:"hidden",direction:"ltr"}},f,"last"),B=0!=e.position(x).x;f.removeChild(x);d.removeChild(f);return B});b.add("position-fixed-support",function(d,f){d=w.body(f);f=a.create("span",{style:{visibility:"hidden",position:"fixed",left:"1px",top:"1px"}},d,"last");var x=a.create("span",{style:{position:"fixed",left:"0",top:"0"}},f,"last"),
B=e.position(x).x!=e.position(f).x;f.removeChild(x);d.removeChild(f);return B});var n={getBox:function(d){d=d||w.doc;var f="BackCompat"==d.compatMode?w.body(d):d.documentElement,x=e.docScroll(d);if(b("touch")){var B=n.get(d);d=B.innerWidth||f.clientWidth;f=B.innerHeight||f.clientHeight}else d=f.clientWidth,f=f.clientHeight;return{l:x.x,t:x.y,w:d,h:f}},get:function(d){if(b("ie")&&n!==document.parentWindow){d.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var f=d._parentWindow;
d._parentWindow=null;return f}return d.parentWindow||d.defaultView},scrollIntoView:function(d,f){try{d=g.byId(d);var x=d.ownerDocument||w.doc,B=w.body(x),y=x.documentElement||B.parentNode,G=b("ie")||b("trident"),J=b("webkit");if(d!=B&&d!=y)if(!(b("mozilla")||G||J||b("opera")||b("trident")||b("edge"))&&"scrollIntoView"in d)d.scrollIntoView(!1);else{var R="BackCompat"==x.compatMode,S=Math.min(B.clientWidth||y.clientWidth,y.clientWidth||B.clientWidth),K=Math.min(B.clientHeight||y.clientHeight,y.clientHeight||
B.clientHeight);x=J||R?B:y;var E=f||e.position(d),u=d.parentNode;f=function(q){return 6>=G||7==G&&R?!1:b("position-fixed-support")&&"fixed"==c.get(q,"position").toLowerCase()};var T=this;J=function(q,z,r){"BODY"==q.tagName||"HTML"==q.tagName?T.get(q.ownerDocument).scrollBy(z,r):(z&&(q.scrollLeft+=z),r&&(q.scrollTop+=r))};if(!f(d))for(;u;){u==B&&(u=x);var k=e.position(u),L=f(u),M="rtl"==c.getComputedStyle(u).direction.toLowerCase();if(u==x)k.w=S,k.h=K,x==y&&(G||b("trident"))&&M&&(k.x+=x.offsetWidth-
k.w),k.x=0,k.y=0;else{var H=e.getPadBorderExtents(u);k.w-=H.w;k.h-=H.h;k.x+=H.l;k.y+=H.t;var D=u.clientWidth,N=k.w-D;0<D&&0<N&&(M&&b("rtl-adjust-position-for-verticalScrollBar")&&(k.x+=N),k.w=D);D=u.clientHeight;N=k.h-D;0<D&&0<N&&(k.h=D)}L&&(0>k.y&&(k.h+=k.y,k.y=0),0>k.x&&(k.w+=k.x,k.x=0),k.y+k.h>K&&(k.h=K-k.y),k.x+k.w>S&&(k.w=S-k.x));var l=E.x-k.x,m=E.y-k.y,v=l+E.w-k.w,p=m+E.h-k.h;if(0<v*l&&(u.scrollLeft||u==x||u.scrollWidth>u.offsetHeight)){var t=Math[0>l?"max":"min"](l,v);M&&(8==G&&!R||5<=b("trident"))&&
(t=-t);var A=u.scrollLeft;J(u,t,0);t=u.scrollLeft-A;E.x-=t}0<p*m&&(u.scrollTop||u==x||u.scrollHeight>u.offsetHeight)&&(t=Math.ceil(Math[0>m?"max":"min"](m,p)),A=u.scrollTop,J(u,0,t),t=u.scrollTop-A,E.y-=t);u=u!=x&&!L&&u.parentNode}}}catch(q){console.error("scrollIntoView: "+q),d.scrollIntoView(!1)}}};h.setObject("dojo.window",n);return n})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),function(h,b,w,g,e,
c,a,n,d){w.add("dojo-preload-i18n-Api",1);var f=h.i18n={},x=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,B=function(l,m,v,p){var t=[v+p];m=m.split("-");for(var A="",q=0;q<m.length;q++)if(A+=(A?"-":"")+m[q],!l||l[A])t.push(v+A+"/"+p),t.specificity=A;return t},y={},G=function(l,m,v){v=v?v.toLowerCase():h.locale;l=l.replace(/\./g,"/");m=m.replace(/\./g,"/");return/root/i.test(v)?l+"/nls/"+m:l+"/nls/"+v+"/"+m},J=h.getL10nName=function(l,m,v){return l=d.id+"!"+G(l,m,v)},R=function(l,m,v,p,t,A){l([m],function(q){var z=
c.clone(q.root||q.ROOT),r=B(!q._v1x&&q,t,v,p);l(r,function(){for(var C=1;C<r.length;C++)z=c.mixin(c.clone(z),arguments[C]);y[m+"/"+t]=z;z.$locale=r.specificity;A()})})},S=function(l){var m=e.extraLocale||[];m=c.isArray(m)?m:[m];m.push(l);return m},K=function(l,m,v){var p=x.exec(l),t=p[1]+"/",A=p[5]||p[4],q=t+A,z=(p=p[5]&&p[4])||h.locale||"",r=q+"/"+z;p=p?[z]:S(z);var C=p.length,V=function(){--C||v(c.delegate(y[r]))};z=l.split("*");var O="preload"==z[1];if(w("dojo-preload-i18n-Api")){if(O&&(y[l]||
(y[l]=1,k(z[2],n.parse(z[3]),1,m)),v(1)),(z=O)||(u&&T.push([l,m,v]),z=u&&!y[r]),z)return}else if(O){v(1);return}g.forEach(p,function(P){var F=q+"/"+P;w("dojo-preload-i18n-Api")&&L(F);y[F]?V():R(m,q,t,A,P,V)})};w("dojo-preload-i18n-Api");var E=f.normalizeLocale=function(l){l=l?l.toLowerCase():h.locale;return"root"==l?"ROOT":l},u=0,T=[],k=f._preloadLocalizations=function(l,m,v,p){function t(r,C){p.isXdUrl(b.toUrl(r+".js"))||v?p([r],C):N([r],C,p)}function A(r,C){for(r=r.split("-");r.length;){if(C(r.join("-")))return;
r.pop()}C("ROOT")}function q(){for(--u;!u&&T.length;)K.apply(null,T.shift())}function z(r){r=E(r);A(r,function(C){if(0<=g.indexOf(m,C)){var V=l.replace(/\./g,"/")+"_"+C;u++;t(V,function(O){for(var P in O){var F=O[P],Q=P.match(/(.+)\/([^\/]+)$/);if(Q){var aa=Q[2];Q=Q[1]+"/";if(F._localized){var Z;if("ROOT"===C){var ba=Z=F._localized;delete F._localized;ba.root=F;y[b.toAbsMid(P)]=ba}else Z=F._localized,y[b.toAbsMid(Q+aa+"/"+C)]=F;C!==r&&function(W,X,U,da){var Y=[],ca=[];A(r,function(I){da[I]&&(Y.push(b.toAbsMid(W+
I+"/"+X)),ca.push(b.toAbsMid(W+X+"/"+I)))});Y.length?(u++,p(Y,function(){for(var I=Y.length-1;0<=I;I--)U=c.mixin(c.clone(U),arguments[I]),y[ca[I]]=U;y[b.toAbsMid(W+X+"/"+r)]=c.clone(U);q()})):y[b.toAbsMid(W+X+"/"+r)]=U}(Q,aa,F,Z)}}}q()});return!0}return!1})}p=p||b;z();g.forEach(h.config.extraLocale,z)},L=function(){},M={},H={},D,N=function(l,m,v){var p=[];g.forEach(l,function(t){function A(r){D||(D=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"));
r=D(r,L,t,M);r===M?p.push(y[q]=M.result):(r instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+q,r),r={}),p.push(y[q]=/nls\/[^\/]+\/[^\/]+$/.test(q)?r:{root:r,_v1x:1}))}var q=v.toUrl(t+".js");if(y[q])p.push(y[q]);else{var z=v.syncLoadNls(t);z||(z=L(t.replace(/nls\/([^\/]*)\/([^\/]*)$/,"nls/$2/$1")));if(z)p.push(z);else if(a)a.get({url:q,sync:!0,load:A,error:function(){p.push(y[q]={})}});else try{v.getText(q,!0,A)}catch(r){p.push(y[q]={})}}});m&&m.apply(null,p)};L=function(l){for(var m,
v=l.split("/"),p=h.global[v[0]],t=1;p&&t<v.length-1;p=p[v[t++]]);p&&((m=p[v[t]])||(m=p[v[t].replace(/-/g,"_")]),m&&(y[l]=m));return m};f.getLocalization=function(l,m,v){var p,t=G(l,m,v);if(H[t])return H[t];K(t,b.isXdUrl(b.toUrl(t+".js"))?b:function(A,q){N(A,q,b)},function(A){p=H[t]=A});return p};return c.mixin(f,{dynamic:!0,normalize:function(l,m){return/^\./.test(l)?m(l):l},load:K,cache:y,getL10nName:J})})},"mw-browser-utils/detect/css":function(){define(["dojo/has"],function(h){function b(e,c){var a=
!1,n=e.charAt(0).toUpperCase()+e.slice(1),d=w.length;c=c.style;if("string"===typeof c[e])a=!0;else for(;d;)if(--d,"string"===typeof c[w[d]+n]){a=!0;break}return a}var w=["Webkit","Moz","O","ms","Khtml"],g=h.add;g("css-enabled",function(e,c,a){e=c.documentElement;var n;if(!(n=c.body)){var d=!0;n=e.insertBefore(c.createElement("body"),e.firstChild)}e=n;n=a.style.display;a.style.display="none";e.insertBefore(a,e.firstChild);c=0===a.offsetWidth;e.removeChild(a);a.style.display=n;d&&e.parentNode.removeChild(e);
return c});g("css-content-box",function(e,c,a){var n;e=c.documentElement;var d=null;if(h("css-enabled")){if(!(n=c.body)){var f=!0;n=e.insertBefore(c.createElement("body"),e.firstChild)}a.style.cssText="position: absolute; top: -4000px; width: 40px; height: 40px; border: 1px solid black;";n.insertBefore(a,n.firstChild);d=40===a.clientWidth;n.removeChild(a);a.style.cssText=""}f&&n.parentNode.removeChild(n);return d});g("css-position-fixed",function(e,c,a){var n,d=c.documentElement,f=null;if(h("css-enabled")){e=
a.cloneNode(!1);if(!(n=c.body)){var x=!0;n=d.insertBefore(c.createElement("body"),d.firstChild)}c=n.style.cssText;n.style.cssText="padding:0;margin:0";a.style.cssText="position:fixed;top:42px";n.insertBefore(e,n.firstChild);n.insertBefore(a,e);f=a.offsetTop!==e.offsetTop;n.removeChild(a);n.removeChild(e);n.style.cssText=c;a.style.cssText=""}x&&n.parentNode.removeChild(n);return f});g("css-rgba",function(e,c,a){e=/^rgba/;c=null;if(h("css-enabled"))try{a.style.color="rgba(1,1,1,0.5)",c=e.test(a.style.color),
a.style.color=""}catch(n){}return c});g("css-border-radius",function(e,c,a){return b("borderRadius",a)});g("css-box-shadow",function(e,c,a){return b("boxShadow",a)});g("css-box-sizing",function(e,c,a){return b("boxSizing",a)});g("css-opacity",function(e,c,a){return b("opacity",a)});g("css-opacity-filter",function(e,c){return!h("css-opacity")&&"undefined"!==typeof c.documentElement.filters});g("css-resize",function(e,c,a){return b("resize",a)});g("css-selectable",function(e,c,a){return b("userSelect",
a)});g("css-style-float",function(e,c,a){return b("styleFloat",a)});g("css-pointerevents",function(e,c,a){return b("pointerEvents",a)});g("css-text-overflow",function(e,c,a){return b("textOverflow",a)});g("css-text-shadow",function(e,c,a){return b("textShadow",a)});g("css-transform",function(e,c,a){return b("transform",a)});return h})},"mw-browser-utils/detect/object":function(){define(["dojo/has"],function(h){var b=h.add,w={}.toString,g=Object;b("object-create",function(){return"[object Function]"===
w.call(g.create)});b("object-getprototypeof",function(){return"[object Function]"===w.call(g.getPrototypeOf)});b("object-seal",function(){return"[object Function]"===w.call(g.seal)});b("object-freeze",function(){return"[object Function]"===w.call(g.freeze)});b("object-issealed",function(){return"[object Function]"===w.call(g.isSealed)});b("object-isfrozen",function(){return"[object Function]"===w.call(g.isFrozen)});b("object-keys",function(){return"[object Function]"===w.call(g.keys)});b("object-preventextensions",
function(){return"[object Function]"===w.call(g.preventExtensions)});b("object-isextensible",function(){return"[object Function]"===w.call(g.isExtensible)});b("object-defineproperty",function(){return"[object Function]"===w.call(g.defineProperty)});b("object-defineproperties",function(){return"[object Function]"===w.call(g.defineProperties)});b("object-getownpropertydescriptor",function(){return"[object Function]"===w.call(g.getOwnPropertyDescriptor)});b("object-getownpropertynames",function(){return"[object Function]"===
w.call(g.getOwnPropertyNames)});b("object-es5",function(){return h("object-create")&&h("object-defineproperties")&&h("object-defineproperty")&&h("object-freeze")&&h("object-getownpropertydescriptor")&&h("object-getownpropertynames")&&h("object-getprototypeof")&&h("object-isextensible")&&h("object-isfrozen")&&h("object-issealed")&&h("object-keys")&&h("object-preventextensions")&&h("object-seal")});return h})},"*now":function(h){h(['dojo/i18n!*preload*installer_login/nls/browsercheck*["ja-jp","ko-kr","zh-cn","en-us","ROOT"]'])}}});
define("installer_login/browsercheck",[],1);