function mRoot = addOrientationMenu(this)
%addOrientationMenu Add a menu option for setting the plot axes orientation.
% Used by time and frequency domain data plots.

%  Copyright 2013-2014 The MathWorks, Inc.

AxGrid = this.AxesGrid;
mRoot = uimenu('Parent', AxGrid.UIContextMenu, ...
   'Label',getString(message('Controllib:plots:strOrientation')),...
   'Tag','orientation');
mSub = [...
   uimenu('Parent',mRoot, ...
   'Label',getString(message('Controllib:plots:strOrientation1')), ...
   'Tag','2row',...
   'Callback',{@localOrientation AxGrid '2row'});...
   uimenu('Parent',mRoot, ...
   'Label',getString(message('Controllib:plots:strOrientation2')), ...
   'Tag','2col',...
   'Callback',{@localOrientation AxGrid '2col'});...
   uimenu('Parent',mRoot, ...
   'Label',getString(message('Controllib:plots:strOrientation3')), ...
   'Tag','1row',...
   'Callback',{@localOrientation AxGrid '1row'});...
   uimenu('Parent',mRoot, ...
   'Label',getString(message('Controllib:plots:strOrientation4')), ...
   'Tag','1col',...
   'Callback',{@localOrientation AxGrid '1col'})];

% Initialize submenus
% Listen to changes in the axesgroup property of the AxesGrid
L = addOrientationListener(AxGrid, mSub);
set(mRoot,'UserData',L);

Or = AxGrid.Orientation;
if strcmp(Or,'2row')
   set(mSub(1),'checked','on');
elseif strcmp(Or,'2col')
   set(mSub(2),'checked','on');
elseif strcmp(Or,'1row')
   set(mSub(3),'checked','on');
else
   set(mSub(4),'checked','on');
end

%--------------------------------------------------------------------------
function localOrientation(~,~,AxGrid,Type)
% Reorient the plot axes in desired layout

AxGrid.Orientation = Type;
