function [sharedoptim, fulloptim] = uselargeoptimstruct
% Check to see if the large options structure should be returned.

%   Copyright 2008-2022 The MathWorks, Inc.

fulloptim = license('test','Optimization_Toolbox');

sharedoptim = fulloptim || ...
              license('test','Curve_Fitting_Toolbox') || ...
              license('test','Statistics_Toolbox') || ...
              license('test','Simulink_Control_Design') || ...
              license('test','Video_and_Image_Blockset') || ...
              license('test','Identification_Toolbox') || ...
              license('test','Antenna_Toolbox') || ...
              license('test','Fixed_Point_Toolbox') || ...
              license('test','Image_Toolbox') || ...
              license('test','Lidar_Toolbox') || ...
              license('test','Sensor_Fusion_and_Tracking');