function tableData = init_db_table_data
% Initialize a containers.Map describing the database tables.

%   Copyright 2013-2024 The MathWorks, Inc.

    tableData = containers.Map;
    
    % Names of the languages that may be associated with a file. Files may
    % have at most one language. Provides some information about the type
    % of data stored in the file.
    tableData('Language') = {...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT', ...
        'Name TEXT UNIQUE' };

    % Types of symbols (built-in, MEX-file, MATLAB function, etc.)
    % recognized by the dependency analysis algorithms.
    % The Value of each symbol type in the Symbol_Type table is
    % identical to the numeric value of the enumeration class
    % matlab.depfun.internal.MatlabType.    
    tableData('Symbol_Type') = { ...
        'Name TEXT UNIQUE' ...
        'Value INTEGER UNIQUE' };
            
    % Types of proxies
    tableData('Proxy_Type') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Type INTEGER UNIQUE' ...
        'FOREIGN KEY(Type) REFERENCES Symbol_Type(Value)' };
  
    % Type of environment to which an application may be deployed.
    % Exclusion and inclusion lists vary by target. GUIs that run in the
    % MATLAB target are prohibited in the MCR target, for example.
    tableData('Target') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name TEXT UNIQUE' };
    
    % File system locations -- ordered lists of Path_Items form
    % component paths.
    tableData('Path_Item') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT', ...
        'Location TEXT'};
    
    % A file on the disk. 
    tableData('File') = {...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Path TEXT UNIQUE' ...
        'Language INTEGER' ...
        'Type INTEGER' ...
        'Symbol TEXT' ...
        'FOREIGN KEY(Language) REFERENCES Language(ID)' ...
        'FOREIGN KEY(Type) REFERENCES Symbol_Type(Value)' };
    
    % Proxy-Principals table
    % Proxy: class constructor/fake class constructor
    % Principals: class methods, class schema, ...
    %             package functions, package schema, etc.
    tableData('Proxy_Principal') = { ...
        'Proxy INTEGER', ...
        'Principal INTEGER', ...
        'FOREIGN KEY(Proxy) REFERENCES File(ID) ON DELETE CASCADE' ...
        'FOREIGN KEY(Principal) REFERENCES File(ID) ON DELETE CASCADE' };
    
    % The immediate dependencies of each file. A list, for example,
    % of all the functions mentioned by name in the text of the client file.
    tableData('Level0_Use_Graph') = { ...
        'Client INTEGER' ...
        'Dependency INTEGER' ...
        'FOREIGN KEY(Client) REFERENCES File(ID) ON DELETE CASCADE' ...
        'FOREIGN KEY(Dependency) REFERENCES File(ID) ON DELETE CASCADE' };
    
    % All the dependencies of each file. This table flattens the tree
    % represented by the Level0_Use_Graph. Some clients may have hundreds
    % or thousands of dependencies. This is usually the biggest table in
    % any given database.
    tableData('Proxy_Closure') = { ...
        'Client INTEGER' ...
        'Dependency INTEGER' ...
        'FOREIGN KEY(Client) REFERENCES File(ID) ON DELETE CASCADE' ...
        'FOREIGN KEY(Dependency) REFERENCES File(ID) ON DELETE CASCADE' };
    
    % Paths of file that cannot be deployed, for one reason or another.
    % Kept separate from the File table for ease of management. (And this
    % way, we know that Exclude_Files never ship.)
    tableData('Exclude_File') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Path TEXT UNIQUE' };
    
    % Per-component, per-target exclusion list.
    tableData('Exclusion_List') = { ...
        'Target INTEGER' ...
        'File INTEGER' ...
        'FOREIGN KEY(Target) REFERENCES Target(ID)' ...
        'FOREIGN KEY(File) REFERENCES Exclude_File(ID)' };
    
    %
    % Component-level dependency tables
    %
    tableData('Required_Components') = { ...
        'ID INTEGER PRIMARY KEY AUTOINCREMENT' ...
        'Name Text UNIQUE', ...
        };
    
    tableData('File_Components') = { ...
        'File INTEGER', ...
        'Component INTEGER', ...
        'FOREIGN KEY(File) REFERENCES File(ID) ON DELETE CASCADE', ...
        'FOREIGN KEY(Component) REFERENCES Required_Components(ID)' ...
        };
    
    tableData('Proxy_Component_Closure') = { ...
        'Proxy INTEGER', ...
        'Component INTEGER', ...
        'FOREIGN KEY(Proxy) REFERENCES File(ID) ON DELETE CASCADE', ...
        'FOREIGN KEY(Component) REFERENCES Required_Components(ID)' ...
        };

    tableData('File_Builtins') = { ...
        'File INTEGER', ...
        'Builtin Text', ...
        'FOREIGN KEY(File) REFERENCES File(ID) ON DELETE CASCADE' ...
        };

    tableData('Enriched_File_Components') = { ...
        'File INTEGER', ...
        'Component INTEGER', ...
        'FOREIGN KEY(File) REFERENCES File(ID) ON DELETE CASCADE', ...
        'FOREIGN KEY(Component) REFERENCES Required_Components(ID)' ...
        };
end

% LocalWords:  AUTOINCREMENT IXF
