function result = mostFrequentlyUsedFileReadingTools()
% This data file contains information about most frequently call file
% reading functions and their default input file extension.
% This list covers MATLAB functions for importing data from text files,
% spread sheets, images, audio and video files, and XML files.
% 
% The data is not stored in an XML file because XMLREAD relies on Java.

%   Copyright 2016-2020 The MathWorks, Inc.

persistent list

    if isempty(list)
        list = containers.Map({ 'audioinfo' ...
                                'audioread' ...
                                'builtin' ...
                                'csvread' ...
                                'daqread' ...
                                'dlmread' ...
                                'fileread' ...
                                'fopen' ...
                                'imfinfo' ...
                                'importdata' ...
                                'imread' ...
                                'load' ...
                                'matfile' ...
                                'mmfileinfo' ...
                                'open' ...
                                'readstruct' ...
                                'readtable' ...
                                'type' ...
                                'VideoReader' ...
                                'xlsfinfo' ...
                                'xlsread' ...
                                'xmlread' ...
                                'xslt' ...
                              }, ...
                              { {} ... % audioinfo
                                {} ... % audioread
                                {} ... % builtin
                                {} ... % csvread
                                {} ... % daqread
                                {} ... % dlmread
                                {} ... % fileread
                                {} ... % fopen
                                {} ... % imfinfo
                                {} ... % importdata
                                {} ... % imread
                                {'.mat'} ... % load
                                {'.mat'} ... % matfile
                                {} ... % mmfileinfo
                                {} ... % open
                                {} ... % readstruct
                                {'.txt'} ... % readtable
                                {} ... % type
                                {} ... % VideoReader
                                {'.xls' '.xlsx' '.xlsm' '.xltx' '.xltm'} ... % xlsfinfo
                                {'.xls' '.xlsx' '.xlsm' '.xltx' '.xltm'} ... % xlsread
                                {} ... % xmlread
                                {} ... % xslt
                              });
        if matlab.depfun.internal.requirementsConstants.isSimulinkCompilerAccessible
            mdl_ext = matlab.depfun.internal.requirementsConstants.simulinkModelExt;
            list('Simulink.SimulationInput') = mdl_ext;                    % Simulink.SimulationInput
            list('SimulationInput') = mdl_ext;                             % In case Simulink.SimulationInput is imported.
            list('simulink.compiler.getDefaultSimulationInput') = mdl_ext; % simulink.compiler.getDefaultSimulationInput
            list('getDefaultSimulationInput') = mdl_ext;                   % In case simulink.compiler.getDefaultSimulationInput is imported.
        end
    end
    
    result = list;
end

