function pairs = oom_component_data()
% This function returns pairs of Out-Of-Model components and their
% run-time circular dependencies.

pairs = { 'shared_controllib_engine' 'control'; ...
          'shared_optimlib'          'optim'; ...
          'stats'                    'optim'; ...
          'signal'                   'dsp'; ...
          'signal'                   'filterdesign'; ...
          'filterdesign'             'dsp'; ...
          'shared_orbit'             'satcom'};