classdef Constants
    %CONSTANTS contains constants for the Communication log section.

    % Copyright 2021 The MathWorks, Inc.

    properties (Constant)
        TableParentGrid = struct( ...
            'ColumnWidth', "1x", ...
            'RowHeight', "1x", ...
            'Padding', [0, 0, 0, 0] ...
            )

        ColumnNames = ["Action", "Data", "Size", "Data Type", "Time"]

        Table = struct( ...
            'RowName', {cell.empty}, ...
            'ColumnEditable', [false, false, false, false, false], ...
            'ColumnName', matlabshared.transportapp.internal.appspace.communicationlog.Constants.ColumnNames', ...
            'FontSize', 12, ...
            'ColumnWidth', ["2x", "20x", "1x", "2x", "4x"], ...
            'RowStriping', 'off', ...
            "Tag", 'CommunicationLogTable')

        DataColumn = 2
        SizeColumn = 3
        RowDataDelimiter = " "

        ContextMenuLabels = string(message("transportapp:toolstrip:export:SelectedRowButtonLabel").getString)
    end
end