classdef JSONParsingInputs < matlab.io.internal.FunctionInterface ...
        & matlab.io.internal.common.properties.GetFunctionNameProvider ...
        & matlab.io.json.internal.read.parameter.AllowCommentsProvider ...
        & matlab.io.json.internal.read.parameter.AllowInfAndNaNProvider ...
        & matlab.io.json.internal.read.parameter.AllowTrailingCommasProvider ...
        & matlab.io.json.internal.read.parameter.OverflowToInfinityProvider ...
        & matlab.io.json.internal.read.parameter.UseFullPrecisionProvider ...
%

% Copyright 2024 The MathWorks, Inc.

    methods (Hidden)
        function S = buildJSONParsingOptionsStruct(func)
            S = struct(AllowComments=func.AllowComments, ...
                       AllowInfAndNaN=func.AllowInfAndNaN, ...
                       AllowTrailingCommas=func.AllowTrailingCommas, ...
                       OverflowToInfinity=func.OverflowToInfinity, ...
                       UseFullPrecision=func.UseFullPrecision);
        end
    end
end
