%mlreportgen.dom.setDefaultNumberFormat Sets the default formatting of
%numeric data generated by the DOM API
%    mlreportgen.dom.setDefaultNumberFormat(FormatString) sets the sprintf   
%    format string used by default to format numeric data generated by the 
%    DOM API. The format string must use one of the following conversion characters:
%    %f, %e, %E, %g, %G.    
%
%    The format string must be an sprintf number format string.  
%    See https://www.mathworks.com/help/matlab/ref/sprintf.html
%    
%
%    setDefaultNumberFormat arguments:
%        FormatString -  a character vector or string scalar that specifies 
%                        an sprintf number format string with the
%                        following formatting operators - %f, %e, %E, %g,
%                        %G.
%
%    Example:
%
%    % Set default number format
%     import mlreportgen.dom.*
% 
%     rpt = Document("Report with setDefaultNumberFormat","pdf");
% 
%     setDefaultNumberFormat("%0.2f");
%
%     n = Number(pi);
%     append(rpt,n);
% 
%     close(rpt);
%     rptview(rpt);
%
%    See also mlreportgen.dom.Number, mlreportgen.dom.NumberFormat,
%    mlreportgen.dom.getDefaultNumberFormat

%    Copyright 2020 MathWorks, Inc.
%    Built-in function