function c = getCharacteristics(~,PlotType)
%getCharacteristics Gets the characteristics associated with the plot type
% for the data source

%  Copyright 2013-2016 The MathWorks, Inc.

%#function iodatapack.TimePeakAmpData
%#function iodatapack.TimePeakAmpView
%#function iodatapack.MeanValueData
%#function iodatapack.MeanValueView
%#function iodatapack.FreqPeakGainData
%#function iodatapack.FreqPeakGainView

switch PlotType
   case 'time'
      c(1) = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strPeakValue'), ...
         'CharacteristicID', 'PeakValue', ...
         'CharacteristicData', 'iodatapack.TimePeakAmpData',...
         'CharacteristicView', 'iodatapack.TimePeakAmpView', ...
         'CharacteristicGroup', 'Characteristic');
      c(2) = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strMeanValue'), ...
         'CharacteristicID', 'MeanValue', ...
         'CharacteristicData', 'iodatapack.MeanValueData',...
         'CharacteristicView', 'iodatapack.MeanValueView', ...
         'CharacteristicGroup', 'Characteristic');
   case 'frequency'
      c(1) = struct(...
         'CharacteristicLabel', ctrlMsgUtils.message('Controllib:plots:strPeakValue'), ...
         'CharacteristicID', 'PeakResponse', ...
         'CharacteristicData', 'iodatapack.FreqPeakGainData',...
         'CharacteristicView', 'iodatapack.FreqPeakGainView', ...
         'CharacteristicGroup', 'Characteristic');
   otherwise
      c = [];
end
