%mlreportgen.dom.enableDOCXUpdateOnOpen Update document fields when document is opened
%    mlreportgen.dom.enableDOCXUpdateOnOpen(tf) determines whether the document fields
%    are updated when the DOCX document, generated by the DOM API, is opened.
%    This function is not document specific. Calling this function applies to any
%    generated document until the end of the MATLAB session, or until calling 
%    this function again.
%
%    enableDOCXUpdateOnOpen arguments:
%        tf           -  Whether to update the document fields upon opening the document
%                        true           -  update the fields when the document is opened
%                        false(default) -  do not update the fields when the document is opened
%
%    Example:
%
%     import mlreportgen.dom.*
% 
%     enableDOCXUpdateOnOpen(true);
%
%     rpt = Document("Report with update fields enabled","docx");
%
%     append(rpt,TOC);
%     append(rpt,Heading1("Chapter 1"));
%     append(rpt,"Chapter 1 content");
% 
%     close(rpt);
%     rptview(rpt);
%
%    See also mlreportgen.dom.Document

%    Copyright 2022 MathWorks, Inc.
%    Built-in function